Repository vufind-org/vufind, pull requests merged in 2023-12, with the labels that each got.

#3245 Fix option processing bug introduced in #2995.
  harvest/batch-import-marc.sh
Labels: bugfix

#3246 Fix filtered facet pagination
  module/VuFind/src/VuFind/Search/Base/HideFacetValueListener.php
  module/VuFind/src/VuFind/Search/Solr/Results.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchFacetsTest.php
  module/VuFindSearch/src/VuFindSearch/Backend/Solr/Response/Json/RecordCollection.php
Labels: bugfix

#3252 Expand Mink test to exercise more button after sorting facets.
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchFacetsTest.php
Labels: tests

#3253 VUFIND-1342 Update browse commands for new browse project layout
  import/browse-indexing.jar
  index-alphabetic-browse.bat
  index-alphabetic-browse.sh
  solr/vufind/jars/browse-handler.jar
Labels: dependencies

#3204 Responsive table for search history.
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/bootstrap.less
  themes/bootstrap3/less/components/search.less
  themes/bootstrap3/scss/bootstrap.scss
  themes/bootstrap3/scss/components/search.scss
  themes/bootstrap3/templates/search/history-table.phtml
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
Labels: accessibility

#3263 Enclose search history label in span to avoid collapsing of white space.
  themes/bootstrap3/templates/search/history-table.phtml
Labels: bugfix

#3261 Make minor tweaks to styles for improved Bootstrap 5 compatibility.
  themes/bootprint3/css/compiled.css
  themes/bootprint3/less/common.less
  themes/bootprint3/less/variables.less
  themes/bootprint3/scss/common.scss
  themes/bootprint3/scss/variables.scss
  themes/sandal/css/compiled.css
  themes/sandal/less/sandal.less
  themes/sandal/scss/sandal.scss
Labels: improvement, small

#3272 Combined: Fix include_recommendations = true setting.
  module/VuFind/src/VuFind/Controller/CombinedController.php
Labels: bugfix, small

#3264 Combined: Keep standard recommendations that are not overridden
  module/VuFind/src/VuFind/Controller/AbstractSearch.php
Labels: bugfix

#3255 Add support for Primo REST API.
  config/vufind/Primo.ini
  module/VuFind/src/VuFind/RecordDriver/Primo.php
  module/VuFind/src/VuFind/Search/Base/Options.php
  module/VuFind/src/VuFind/Search/Factory/PrimoBackendFactory.php
  module/VuFind/src/VuFind/Search/Primo/Params.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/Blender/ParamsTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/Primo/ParamsTest.php
  module/VuFindSearch/src/VuFindSearch/Backend/Primo/Backend.php
  module/VuFindSearch/src/VuFindSearch/Backend/Primo/Connector.php
  module/VuFindSearch/src/VuFindSearch/Backend/Primo/ConnectorInterface.php
  module/VuFindSearch/src/VuFindSearch/Backend/Primo/RestConnector.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/Primo/BackendTest.php
Labels: improvement, architecture

#3207 Increase contrast in form elements.
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/components/form.less
  themes/bootstrap3/scss/components/form.scss
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal/less/common.less
  themes/sandal/scss/common.scss
Labels: accessibility
