Repository vufind-org/vufind, pull requests merged in 2023-10, with the labels that each got.

#3108 accessibility: refine search facets to ul.
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/js/facets.js
  themes/bootstrap3/less/components/sidebar.less
  themes/bootstrap3/scss/components/sidebar.scss
  themes/bootstrap3/templates/Recommend/SideFacets/cluster-list.phtml
  themes/bootstrap3/templates/search/facet-list.phtml
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
Labels: accessibility

#3076 Fix record tab heading level
  themes/bootstrap3/js/record.js
  themes/bootstrap3/templates/RecordTab/holdingsils.phtml
  themes/bootstrap3/templates/RecordTab/holdingsils/electronic.phtml
  themes/bootstrap3/templates/record/view.phtml
Labels: accessibility

#3162 Only update FOLIO location cache data when appropriate.
  module/VuFind/src/VuFind/ILS/Driver/Folio.php
Labels: bugfix

#3129 Accessible cart update announcements
  themes/bootstrap3/templates/header.phtml
Labels: accessibility

#3182 Add setting to allow deep searching within collections.
  config/vufind/HierarchyDefault.ini
  config/vufind/HierarchyFlat.ini
  module/VuFind/src/VuFind/Hierarchy/Driver/ConfigurationBased.php
  module/VuFind/src/VuFind/RecordTab/CollectionList.php
  module/VuFind/src/VuFind/Search/SolrCollection/Params.php
Labels: improvement

#3183 Remove unused imports
  import/index_java/src/org/vufind/index/CreatorTools.java
  import/index_java/src/org/vufind/index/FieldSpecTools.java
  import/index_java/src/org/vufind/index/FormatCalculator.java
  import/index_java/src/org/vufind/index/FullTextTools.java
  import/index_java/src/org/vufind/index/GeoTools.java
  import/index_java/src/org/vufind/index/IllustrationTools.java
  import/index_java/src/org/vufind/index/LccnTools.java
  import/index_java/src/org/vufind/index/ReadingProgramTools.java
  import/index_java/src/org/vufind/index/UpdateDateTools.java
  import/index_java/src/org/vufind/index/WorkKeys.java
Labels: improvement
