Repository vufind-org/vufind, pull requests merged in 2023-11, with the labels that each got.

#3189 Optional dataMethod params for RecordDataFormatter
  module/VuFind/src/VuFind/View/Helper/Root/RecordDataFormatter.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/RecordDataFormatterTest.php
Labels: improvement

#3185 Fix Java 9 deprecation warnings
  import/index_java/src/org/vufind/index/CallNumberTools.java
  import/index_java/src/org/vufind/index/DatabaseManager.java
Labels: improvement

#3181 Updated jQuery to Javascript for button disable on submit
  themes/bootstrap3/js/common.js
Labels: improvement, small

#3126 Add option to return an HTMLElement from the icon helper
  themes/bootstrap3/js/common.js
Labels: improvement

#3175 Accessibility: Use $headTitle as <h1> on results
  themes/bootstrap3/templates/combined/results.phtml
  themes/bootstrap3/templates/search/results.phtml
Labels: improvement, accessibility, small

#3098 Add option to enable facet filters for advanced search facets
  config/vufind/facets.ini
  module/VuFind/src/VuFind/AjaxHandler/GetFacetData.php
  module/VuFind/src/VuFind/AjaxHandler/GetSideFacets.php
  module/VuFind/src/VuFind/AjaxHandler/GetSideFacetsFactory.php
  module/VuFind/src/VuFind/Controller/AbstractSearch.php
  module/VuFind/src/VuFind/Controller/AbstractSolrSearch.php
  module/VuFind/src/VuFind/Recommend/SideFacets.php
  module/VuFind/src/VuFind/Search/Base/Options.php
  module/VuFind/src/VuFind/Search/Solr/HierarchicalFacetHelper.php
  module/VuFind/tests/unit-tests/src/VuFindTest/AjaxHandler/GetFacetDataTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/Solr/HierarchicalFacetHelperTest.php
  module/VuFindApi/src/VuFindApi/Controller/SearchApiController.php
Labels: improvement, small

#3197 Add an option to always display the "Reset Filters" button.
  config/vufind/Blender.ini
  config/vufind/EDS.ini
  config/vufind/Primo.ini
  config/vufind/Search2.ini
  config/vufind/Summon.ini
  config/vufind/searches.ini
  config/vufind/website.ini
  module/VuFind/src/VuFind/Search/Base/Options.php
  module/VuFind/src/VuFind/Search/EDS/Options.php
  module/VuFind/src/VuFind/Search/Primo/Options.php
  module/VuFind/src/VuFind/Search/Solr/Options.php
  module/VuFind/src/VuFind/Search/Summon/Options.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchFacetsTest.php
  themes/bootstrap3/templates/search/filters.phtml
Labels: new feature

#2952 Adding optional virtual keyboard to searchbox
  build.xml
  config/vufind/searchbox.ini
  module/VuFind/src/VuFind/View/Helper/Root/SearchBox.php
  package.json
  themes/bootprint3/css/compiled.css
  themes/bootprint3/less/search.less
  themes/bootprint3/scss/search.scss
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/css/vendor/simple-keyboard/index.css
  themes/bootstrap3/js/searchbox_controls.js
  themes/bootstrap3/js/vendor/simple-keyboard-layouts/index.js
  themes/bootstrap3/js/vendor/simple-keyboard/index.js
  themes/bootstrap3/less/bootstrap.less
  themes/bootstrap3/less/components/keyboard.less
  themes/bootstrap3/less/components/search.less
  themes/bootstrap3/scss/bootstrap.scss
  themes/bootstrap3/scss/components/keyboard.scss
  themes/bootstrap3/scss/components/search.scss
  themes/bootstrap3/templates/layout/layout.phtml
  themes/bootstrap3/templates/search/searchbox.phtml
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal/less/search.less
  themes/sandal/scss/keyboard.scss
  themes/sandal/scss/search.scss
Labels: new feature

#3160 Recommend databases based on result facets
  config/vufind/EDS.ini
  config/vufind/LibGuidesAPI.ini
  config/vufind/searches.ini
  languages/en.ini
  module/VuFind/src/VuFind/Connection/LibGuides.php
  module/VuFind/src/VuFind/Recommend/Databases.php
  module/VuFind/src/VuFind/Recommend/DatabasesFactory.php
  module/VuFind/src/VuFind/Recommend/PluginManager.php
  themes/bootstrap3/templates/Recommend/Databases.phtml
Labels: new feature

#2933 Language labels matching MARC standard
  import/translation_maps/language_map.properties
Labels: improvement, small

#3216 Databases: Include search query matches
  config/vufind/EDS.ini
  module/VuFind/src/VuFind/Recommend/Databases.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Recommend/DatabasesTest.php
Labels: new feature, small

#3221 Virtual keyboard: Avoid !important with more specific selectors, escape attrs properly.
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/js/searchbox_controls.js
  themes/bootstrap3/less/components/keyboard.less
  themes/bootstrap3/scss/components/keyboard.scss
  themes/bootstrap3/templates/search/searchbox.phtml
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
Labels: improvement, small

#3224 Fix deprecation warnings in tests; make PHPUnit more strict.
  module/VuFind/tests/phpunit.xml
  module/VuFind/tests/unit-tests/src/VuFindTest/Recommend/SummonResultsTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Recommend/WebResultsTest.php
Labels: tests

#3219 Combined: Fix scope of search cart form
  themes/bootstrap3/templates/combined/results.phtml
Labels: bugfix

#3225 Fix searchbox_controls init function if textInput or resetButton are not defined
  themes/bootstrap3/js/searchbox_controls.js
Labels: bugfix

#3193 Configurable fields for RecordDataFormatter
  config/vufind/RecordDataFormatter.ini
  module/VuFind/src/VuFind/View/Helper/Root/RecordDataFormatter.php
  module/VuFind/src/VuFind/View/Helper/Root/RecordDataFormatterFactory.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/RecordDataFormatterTest.php
Labels: new feature, small

#3229 Databases: Use LibGuides alternate names field
  config/vufind/EDS.ini
  module/VuFind/src/VuFind/Connection/LibGuides.php
  module/VuFind/src/VuFind/Recommend/Databases.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Recommend/DatabasesTest.php
  themes/bootstrap3/templates/Recommend/Databases.phtml
Labels: improvement, small

#3236 MySQL port configurable in build.xml
  build.xml
Labels: improvement, small

#3228 Fix hierarchical facet expand/collapse buttons with mobile Safari.
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/components/search.less
  themes/bootstrap3/less/components/sidebar.less
  themes/bootstrap3/scss/components/search.scss
  themes/bootstrap3/scss/components/sidebar.scss
  themes/bootstrap3/theme.config.php
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
Labels: bugfix

#3238 EPF: Add embargo description
  themes/bootstrap3/templates/RecordDriver/EPF/result-list/full-text-links.phtml
Labels: improvement

#3094 FOLIO: Display bound-with titles
  config/vufind/Demo.ini
  languages/en.ini
  module/VuFind/src/VuFind/ILS/Driver/Demo.php
  module/VuFind/src/VuFind/ILS/Driver/Folio.php
  module/VuFind/tests/fixtures/folio/responses/get-holding-checkedout.json
  module/VuFind/tests/fixtures/folio/responses/get-holding-empty-statements.json
  module/VuFind/tests/fixtures/folio/responses/get-holding-multi-volume.json
  module/VuFind/tests/fixtures/folio/responses/get-holding-sorted.json
  module/VuFind/tests/fixtures/folio/responses/get-holding.json
  module/VuFind/tests/unit-tests/src/VuFindTest/ILS/Driver/FolioTest.php
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/components/record.less
  themes/bootstrap3/scss/components/record.scss
  themes/bootstrap3/templates/RecordTab/holdingsils.phtml
  themes/bootstrap3/templates/RecordTab/holdingsils/boundwith.phtml
  themes/bootstrap3/templates/RecordTab/holdingsils/extended.phtml
  themes/bootstrap3/templates/RecordTab/holdingsils/standard.phtml
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
Labels: new feature

#3240 Sierra: Fix batch retrieval of items and bibs.
  module/VuFind/src/VuFind/ILS/Driver/SierraRest.php
Labels: bugfix

#3241 Disabled session writes for Ajax tabs and getResultCount
  module/VuFind/src/VuFind/AjaxHandler/GetResultCount.php
  module/VuFind/src/VuFind/AjaxHandler/GetResultCountFactory.php
  module/VuFind/src/VuFind/Controller/AbstractRecord.php
Labels: bugfix
