Repository vufind-org/vufind, pull requests merged in 2024-09, with the labels that each got.

#3835 [VUFIND-1557] Eliminate ReturnTypeWillChange annotations.
  module/VuFind/src/VuFind/Db/Service/SessionService.php
  module/VuFind/src/VuFind/Db/Service/SessionServiceInterface.php
  module/VuFind/src/VuFind/Db/Table/Session.php
  module/VuFind/src/VuFind/OAuth2/Entity/AccessTokenEntity.php
  module/VuFind/src/VuFind/OAuth2/Entity/AuthCodeEntity.php
  module/VuFind/src/VuFind/OAuth2/Entity/RefreshTokenEntity.php
  module/VuFind/src/VuFind/Session/AbstractBase.php
  module/VuFind/src/VuFind/Session/Database.php
  module/VuFind/src/VuFind/Session/File.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Session/DatabaseTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Session/FileTest.php
  module/VuFindSearch/src/VuFindSearch/Backend/Solr/Response/Json/NamedList.php
  module/VuFindSearch/src/VuFindSearch/Response/AbstractRecordCollection.php
Labels: improvement

#3901 Fix some missing UserEntityInterface references.
  module/VuFind/src/VuFind/OAuth2/Entity/UserEntity.php
  themes/bootstrap3/templates/myresearch/schedulesearch.phtml
  themes/bootstrap3/templates/record/comments-list.phtml
  themes/bootstrap5/templates/myresearch/schedulesearch.phtml
  themes/bootstrap5/templates/record/comments-list.phtml
Labels: bugfix

#3904 ConfigManager.java: add default local dir support; modernize comments.
  import/index_java/src/org/vufind/index/ConfigManager.java
Labels: improvement

#3903 Use correct id in scheduled search list.
  module/VuFind/src/VuFind/Search/History.php
Labels: bugfix

#3900 Simplify formatting of DateTime for display.
  module/VuFind/src/VuFind/View/Helper/Root/Config.php
  themes/bootstrap3/templates/admin/feedback/home.phtml
  themes/bootstrap3/templates/record/comments-list.phtml
  themes/bootstrap5/templates/admin/feedback/home.phtml
  themes/bootstrap5/templates/record/comments-list.phtml
Labels: bugfix

#3899 Add Permissions dev tool; improve dev tool navigation.
  module/VuFind/src/VuFind/Role/PermissionManager.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Role/PermissionManagerTest.php
  module/VuFindDevTools/config/module.config.php
  module/VuFindDevTools/src/VuFindDevTools/Controller/DevtoolsController.php
  themes/bootstrap3/templates/devtools/deminify.phtml
  themes/bootstrap3/templates/devtools/home.phtml
  themes/bootstrap3/templates/devtools/icon.phtml
  themes/bootstrap3/templates/devtools/language.phtml
  themes/bootstrap3/templates/devtools/permissions.phtml
  themes/bootstrap5/templates/devtools/deminify.phtml
  themes/bootstrap5/templates/devtools/home.phtml
  themes/bootstrap5/templates/devtools/icon.phtml
  themes/bootstrap5/templates/devtools/language.phtml
  themes/bootstrap5/templates/devtools/permissions.phtml
Labels: improvement

#3910 Add an option to use a separate admin theme
  config/vufind/config.ini
  module/VuFindAdmin/config/module.config.php
  module/VuFindTheme/src/VuFindTheme/Initializer.php
Labels: new feature

#3421 KohaRest: add option to include recalls in patron holds page
  config/vufind/KohaRest.ini
  module/VuFind/src/VuFind/ILS/Driver/KohaRest.php
Labels: new feature

#3907 FOLIO: only pull due dates from open loans.
  module/VuFind/src/VuFind/ILS/Driver/Folio.php
  module/VuFind/tests/fixtures/folio/responses/get-holding-checkedout.json
Labels: bugfix

#3888 Use local password hash service instead of laminas-crypt.
  module/VuFind/config/module.config.php
  module/VuFind/src/VuFind/Auth/Database.php
  module/VuFind/src/VuFind/Auth/DatabaseFactory.php
  module/VuFind/src/VuFind/Auth/PluginManager.php
  module/VuFind/src/VuFind/Controller/InstallController.php
  module/VuFind/src/VuFind/Crypt/PasswordHasher.php
Labels: architecture

#3905 Make it possible to retrieve user's saved searches only
  module/VuFind/src/VuFind/Db/Service/SearchService.php
  module/VuFind/src/VuFind/Db/Service/SearchServiceInterface.php
Labels: improvement

#3882 Add session key permission provider
  config/vufind/permissions.ini
  module/VuFind/config/module.config.php
  module/VuFind/src/VuFind/Role/DynamicRoleProviderFactory.php
  module/VuFind/src/VuFind/Role/PermissionProvider/PluginManager.php
  module/VuFind/src/VuFind/Role/PermissionProvider/PluginManagerFactory.php
  module/VuFind/src/VuFind/Role/PermissionProvider/SessionKey.php
  module/VuFind/src/VuFind/Role/PermissionProvider/SessionKeyFactory.php
  module/VuFindDevTools/src/VuFindDevTools/Controller/DevtoolsController.php
  themes/bootstrap3/templates/devtools/permissions.phtml
  themes/bootstrap5/templates/devtools/permissions.phtml
Labels: new feature

#3913 Add file extensions to BibTeX and RIS exports
  config/vufind/export.ini
Labels: improvement

#3881 Introduce option to display shorter author data on EDS item detail page
  config/vufind/EDS.ini
  themes/bootstrap3/css/EDS.css
  themes/bootstrap3/templates/RecordDriver/EDS/core.phtml
  themes/bootstrap5/css/EDS.css
  themes/bootstrap5/templates/RecordDriver/EDS/core.phtml
Labels: improvement

#3916 KohaRest: Fix getConfig for holdings.
  module/VuFind/src/VuFind/ILS/Driver/KohaRest.php
Labels: bugfix

#3917 Add a couple of Finnish and Swedish holding status translations.
  languages/HoldingStatus/fi.ini
  languages/HoldingStatus/sv.ini
Labels: improvement

#3926 Update chrome-mink-driver and add a focus workaround for autocomplete tests
  composer.json
  composer.lock
  module/VuFind/src/VuFindTest/Feature/AutocompleteTrait.php
  module/VuFind/src/VuFindTest/Integration/MinkTestCase.php
Labels: tests

#3924 Fixing offcanvas in combination with sticky elements
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/components/offcanvas.less
  themes/bootstrap3/scss/components/offcanvas.scss
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/scss/components/offcanvas.scss
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal5/css/compiled.css
Labels: bugfix

#3838 [VUFIND-1701] Display FOLIO holdings record information
  config/vufind/Folio.ini
  languages/HoldingStatus/en.ini
  module/VuFind/src/VuFind/ILS/Driver/Folio.php
  module/VuFind/src/VuFind/ILS/Logic/AvailabilityStatus.php
  module/VuFind/src/VuFind/ILS/Logic/AvailabilityStatusInterface.php
Labels: new feature, new language strings

#3931 Fix deduplication in ParamBag to avoid messing with array params
  module/VuFindSearch/src/VuFindSearch/ParamBag.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/ParamBagTest.php
Labels: bugfix

#3853 Fix: Bootstrap 5 theme carets
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/scss/bs3-compat.scss
  themes/sandal/css/compiled.css
  themes/sandal/less/search.less
  themes/sandal/scss/search.scss
  themes/sandal5/css/compiled.css
  themes/sandal5/scss/search.scss
Labels: bugfix

#3760 Clarify use of getWorkKeys in documentation
  import/marc.properties
  import/marc_local.properties
Labels: documentation

#3911 Simplify DynamicRoleProvider with constructor property promotion.
  module/VuFind/src/VuFind/Role/DynamicRoleProvider.php
Labels: improvement

#3936 Ensure boundWithRecords is clear each time through the loop
  module/VuFind/src/VuFind/ILS/Driver/Folio.php
Labels: bugfix

#3885 Signature fix of Solr's backend terms method
  module/VuFindSearch/src/VuFindSearch/Backend/Solr/Backend.php
Labels: bugfix

#3934 Bootstrap 5: Fix btn-primary colors.
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/scss/bs3-compat.scss
  themes/sandal5/css/compiled.css
Labels: bugfix

#3939 Add supported token endpoint auth methods to OIDC well-known configuration.
  module/VuFind/src/VuFind/Controller/OAuth2Controller.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/OAuth2Test.php
Labels: improvement

#3932 Preprocess query string before normalization
  module/VuFindSearch/src/VuFindSearch/Backend/Solr/QueryBuilder.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/Solr/QueryBuilderTest.php
Labels: improvement

#3834 [VUFIND-1665] Persist limit value in DefaultRecord search links.
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/ContainerLinksTest.php
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/link-author.phtml
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/link-journaltitle.phtml
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/link-publisher.phtml
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/link-series.phtml
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/link-subject.phtml
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/link-title.phtml
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/link-author.phtml
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/link-journaltitle.phtml
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/link-publisher.phtml
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/link-series.phtml
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/link-subject.phtml
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/link-title.phtml
Labels: improvement

#3935 Disable jumpto for last search urls
  module/VuFind/src/VuFind/Search/UrlQueryHelper.php
  module/VuFind/src/VuFind/View/Helper/Root/SearchMemory.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/JumpToRecordTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/SearchMemoryTest.php
Labels: improvement

#3940 Fix confirm button title attributes.
  themes/bootstrap3/templates/_ui/components/confirm-button.phtml
  themes/bootstrap3/templates/checkouts/history.phtml
  themes/bootstrap3/templates/holds/list.phtml
  themes/bootstrap5/templates/_ui/components/confirm-button.phtml
  themes/bootstrap5/templates/checkouts/history.phtml
  themes/bootstrap5/templates/holds/list.phtml
Labels: bugfix

#3933 Auto-select single pickup location for a request group
  themes/bootstrap3/js/hold.js
  themes/bootstrap5/js/hold.js
Labels: improvement

#3912 Update local_theme_example to use Bootstrap5 theme.
  themes/local_theme_example/css/compiled.css
  themes/local_theme_example/scss/compiled.scss
  themes/local_theme_example/scss/custom.scss
  themes/local_theme_example/scss/home-page.scss
  themes/local_theme_example/templates/search/home.phtml
  themes/local_theme_example/theme.config.php
Labels: improvement

#3944 Minor InstallController improvements/fixes.
  module/VuFind/src/VuFind/Controller/InstallController.php
  themes/bootstrap3/templates/install/fixbasicconfig.phtml
  themes/bootstrap3/templates/install/fixcache.phtml
  themes/bootstrap3/templates/install/fixdatabase.phtml
  themes/bootstrap3/templates/install/fixils.phtml
  themes/bootstrap3/templates/install/fixsolr.phtml
  themes/bootstrap3/templates/install/fixsslcerts.phtml
  themes/bootstrap3/templates/install/home.phtml
  themes/bootstrap5/templates/install/fixbasicconfig.phtml
  themes/bootstrap5/templates/install/fixcache.phtml
  themes/bootstrap5/templates/install/fixdatabase.phtml
  themes/bootstrap5/templates/install/fixils.phtml
  themes/bootstrap5/templates/install/fixsolr.phtml
  themes/bootstrap5/templates/install/fixsslcerts.phtml
  themes/bootstrap5/templates/install/home.phtml
Labels: bugfix, improvement

#3949 Ensure that user cards are synchronized on login.
  module/VuFind/src/VuFind/Auth/AbstractBase.php
  module/VuFind/src/VuFind/Auth/CAS.php
  module/VuFind/src/VuFind/Auth/LDAP.php
  module/VuFind/src/VuFind/Auth/Shibboleth.php
  module/VuFind/src/VuFind/Auth/SimulatedSSO.php
Labels: bugfix

#3952 Update multi-filter selection translation
  languages/en.ini
  languages/fr.ini
Labels: new language strings

#3953 Update setup-node GitHub action to v4.
  .github/workflows/ci.yaml
Labels: tooling

#3956 Update translations for 10.1 release - Portuguese (Brazilian)
  languages/HoldingStatus/pt-br.ini
  languages/ILSMessages/pt-br.ini
  languages/ISO639-3/pt-br.ini
  languages/WorldCatFormats/pr-br.ini
  languages/pt-br.ini
Labels: new language strings

#3938 Google cover loader: support multiple IDs.
  module/VuFind/src/VuFind/Content/Covers/Google.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Content/Covers/GoogleTest.php
Labels: improvement

#3959 Write check:scss task results to temp dir
  Gruntfile.js
Labels: tooling

#3961 Fix range slider label with deferred facets.
  module/VuFind/src/VuFind/AjaxHandler/GetSideFacets.php
Labels: bugfix

#3967 Updated translation for 10.1 release - Mongolian
  languages/HoldingStatus/mn.ini
  languages/ILSMessages/mn.ini
  languages/WorldCatFormats/mn.ini
  languages/mn.ini
Labels: i18n

#3968 Enable parallel execution with php-cs-fixer.
  tests/vufind.php-cs-fixer.php
  tests/vufind_templates.php-cs-fixer.php
Labels: tooling

#3970 Update translations for 10.1 release - Finnish
  languages/HoldingStatus/fi.ini
  languages/ILSMessages/fi.ini
  languages/WorldCatFormats/fi.ini
  languages/fi.ini
Labels: i18n
