Repository vufind-org/vufind, pull requests merged in 2024-11, with the labels that each got.

#4049 Replace RemoteAddress with UserIpReader in EmailAuthenticator.
  module/VuFind/config/module.config.php
  module/VuFind/src/VuFind/Auth/EmailAuthenticator.php
  module/VuFind/src/VuFind/Auth/EmailAuthenticatorFactory.php
  module/VuFind/src/VuFind/Http/PhpEnvironment/RemoteAddressFactory.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/EmailAuthenticatorTest.php
Labels: bugfix

#4050 Add option to hide hierarchy preview in mobile
  config/vufind/config.ini
  module/VuFind/src/VuFind/RecordTab/HierarchyTree.php
  themes/bootstrap3/js/hierarchy_tree.js
  themes/bootstrap3/templates/RecordTab/collectionhierarchytree.phtml
  themes/bootstrap5/js/hierarchy_tree.js
  themes/bootstrap5/templates/RecordTab/collectionhierarchytree.phtml
Labels: improvement

#4052 Fix setPrintBtnHash when print button is not present.
  themes/bootstrap3/js/record.js
  themes/bootstrap5/js/record.js
Labels: bugfix

#4051 Add function to detect multi facet selection configuration
  themes/bootstrap3/js/facets.js
  themes/bootstrap5/js/facets.js
Labels: bugfix

#4053 Fixing selection checkbox padding
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/components/search.less
  themes/bootstrap3/scss/components/search.scss
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/scss/components/search.scss
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal5/css/compiled.css
Labels: bugfix

#4023 Add default values for instructor/course/department instead of empty string
  config/vufind/reserves.ini
  languages/Reserves/en.ini
  languages/en.ini
  module/VuFind/src/VuFind/Autocomplete/SolrReserves.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/IndexReservesCommand.php
  module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Util/IndexReservesCommandTest.php
  themes/bootstrap3/templates/search/reserves.phtml
  themes/bootstrap3/templates/search/reservesresults.phtml
  themes/bootstrap3/templates/search/reservessearch.phtml
  themes/bootstrap5/templates/search/reserves.phtml
  themes/bootstrap5/templates/search/reservesresults.phtml
  themes/bootstrap5/templates/search/reservessearch.phtml
Labels: improvement

#4054 justify-content for navbar-left in bs-compat.scss
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/scss/bs3-compat.scss
  themes/local_theme_example/css/compiled.css
  themes/sandal5/css/compiled.css
Labels: bugfix

#4059 Tolerate missing cat_pass_enc value in user row.
  module/VuFind/src/VuFind/Db/Row/User.php
Labels: bugfix

#3758 Display status of item locations by status priority.
  module/VuFind/src/VuFind/AjaxHandler/GetItemStatuses.php
  module/VuFind/src/VuFind/ILS/Logic/AvailabilityStatus.php
  module/VuFind/src/VuFind/View/Helper/Root/AvailabilityStatus.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/HoldingsTest.php
  themes/bootstrap3/js/check_item_statuses.js
  themes/bootstrap3/templates/ajax/itemCallnumber.phtml
  themes/bootstrap3/templates/ajax/itemLocationList.phtml
  themes/bootstrap3/templates/layout/js-icons.phtml
  themes/bootstrap3/theme.config.php
  themes/bootstrap5/js/check_item_statuses.js
  themes/bootstrap5/templates/ajax/itemCallnumber.phtml
  themes/bootstrap5/templates/ajax/itemLocationList.phtml
  themes/bootstrap5/templates/layout/js-icons.phtml
  themes/bootstrap5/theme.config.php
Labels: improvement, architecture

#4067 Fix record view without sidebar
  themes/bootstrap3/templates/record/view.phtml
  themes/bootstrap5/templates/record/view.phtml
Labels: bugfix

#4070 Updated alphabrowse jars
  import/browse-indexing.jar
  solr/vufind/jars/browse-handler.jar
Labels: bugfix

#4058 Use active class also for checkbox facets to allow styling
  themes/bootprint3/css/compiled.css
  themes/bootprint3/less/bootprint.less
  themes/bootprint3/scss/bootprint.scss
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/js/facets.js
  themes/bootstrap3/less/components/sidebar.less
  themes/bootstrap3/scss/components/sidebar.scss
  themes/bootstrap3/templates/Recommend/SideFacets.phtml
  themes/bootstrap3/templates/Recommend/SideFacets/checkbox-filters.phtml
  themes/bootstrap3/templates/Recommend/SideFacetsDeferred.phtml
  themes/bootstrap3/templates/search/advanced/layout.phtml
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/js/facets.js
  themes/bootstrap5/scss/components/sidebar.scss
  themes/bootstrap5/templates/Recommend/SideFacets.phtml
  themes/bootstrap5/templates/Recommend/SideFacets/checkbox-filters.phtml
  themes/bootstrap5/templates/Recommend/SideFacetsDeferred.phtml
  themes/bootstrap5/templates/search/advanced/layout.phtml
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal/less/sandal.less
  themes/sandal/scss/sandal.scss
  themes/sandal5/css/compiled.css
  themes/sandal5/scss/sandal.scss
Labels: improvement

#4072 Fix setting of Mailer from address override.
  module/VuFind/src/VuFind/Mailer/Factory.php
Labels: bugfix

#4073 Allow only non-empty value as from address in EmailSettingsTrait.
  module/VuFind/src/VuFind/Config/Feature/EmailSettingsTrait.php
Labels: improvement

#3981 Classify eJournals as journals
  import/index_java/src/org/vufind/index/FormatCalculator.java
  import/translation_maps/format_map.properties
  import/translation_maps/format_map_level0.properties
  import/translation_maps/format_map_level1.properties
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AdvancedSearchTest.php
Labels: improvement, indexing

#4075 Remove unused and obsolete Flash content.
  themes/bootstrap3/images/flash/audio_player.swf
  themes/bootstrap3/images/flash/config.txt
  themes/bootstrap5/images/flash/audio_player.swf
  themes/bootstrap5/images/flash/config.txt
Labels: small

#4077 Fix reply-to name handling in form email handler.
  module/VuFind/src/VuFind/Form/Handler/Email.php
Labels: bugfix

#4069 Support optional x-api-key header in EDS API requests
  config/vufind/EDS.ini
  module/VuFind/src/VuFind/Search/Factory/EdsBackendFactory.php
  module/VuFindSearch/src/VuFindSearch/Backend/EDS/ApiException.php
  module/VuFindSearch/src/VuFindSearch/Backend/EDS/Base.php
Labels: improvement

#4071 Add class for components
  module/VuFind/src/VuFind/View/Helper/Root/Component.php
  themes/bootstrap3/templates/_ui/components/confirm-button.phtml
  themes/bootstrap3/templates/_ui/components/hide-offcanvas-button.phtml
  themes/bootstrap3/templates/_ui/components/menu-button.phtml
  themes/bootstrap3/templates/_ui/components/show-sidebar-button.phtml
  themes/bootstrap5/templates/_ui/components/confirm-button.phtml
  themes/bootstrap5/templates/_ui/components/hide-offcanvas-button.phtml
  themes/bootstrap5/templates/_ui/components/menu-button.phtml
  themes/bootstrap5/templates/_ui/components/show-sidebar-button.phtml
Labels: improvement

#4085 Fix checkbox facets getting mixed with exclude facets
  module/VuFind/src/VuFind/Search/Base/Params.php
  module/VuFind/src/VuFind/Search/EDS/Params.php
  module/VuFind/src/VuFind/Search/Primo/Params.php
  module/VuFind/src/VuFind/Search/Summon/Params.php
Labels: bugfix

#4086 Fix a mistake in Finnish translation for renewal summary.
  languages/fi.ini
Labels: i18n

#4087 Fix range facet init with deferred side facets.
  themes/bootstrap3/js/facets.js
  themes/bootstrap5/js/facets.js
Labels: bugfix

#4092 Fix web search highlighting broken by #3610.
  module/VuFind/src/VuFind/Search/Factory/SolrWebBackendFactory.php
Labels: bugfix

#4094 Add missing filter controls to course reserves.
  themes/bootstrap3/templates/search/reservessearch.phtml
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/templates/search/reservessearch.phtml
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal/less/search.less
  themes/sandal/scss/search.scss
  themes/sandal5/css/compiled.css
  themes/sandal5/scss/search.scss
Labels: bugfix

#4091 Fix range facets and add tests.
  module/VuFind/src/VuFindTest/Feature/SearchFacetFilterTrait.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AdvancedSearchTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchFacetsTest.php
  themes/bootstrap3/js/facets.js
  themes/bootstrap5/js/facets.js
Labels: bugfix

#4097 Improve subject indexing (omit numeric subfields)
  import/index_java/src/org/vufind/index/FieldSpecTools.java
  import/marc.properties
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AlphabrowseTest.php
Labels: indexing

#4100 Improve Finnish and Swedish translations of multi-facet apply button
  languages/fi.ini
  languages/sv.ini
Labels: i18n

#4099 Disable autocomplete for multi-facet selection toggle.
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/components/sidebar.less
  themes/bootstrap3/scss/components/sidebar.scss
  themes/bootstrap3/templates/Recommend/SideFacets/multiFacetsSelection.phtml
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/scss/components/sidebar.scss
  themes/bootstrap5/templates/Recommend/SideFacets/multiFacetsSelection.phtml
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal5/css/compiled.css
Labels: bugfix

#4102 Eliminate mutable configs from tests
  module/VuFind/tests/integration-tests/src/VuFindTest/Auth/ShibbolethTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/CASTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/LDAPTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/MultiAuthTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/SIP2Test.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Recommend/ConsortialVuFindTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Recommend/LibGuidesProfileTest.php
Labels: tests

#4090 Allow copying to clipboard in HTML format
  themes/bootstrap3/templates/Helpers/copy-to-clipboard-button.phtml
  themes/bootstrap5/templates/Helpers/copy-to-clipboard-button.phtml
Labels: improvement

#4106 Configurable permanent links
  config/vufind/config.ini
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/RecordTest.php
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/toolbar.phtml
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/toolbar.phtml
Labels: improvement, small

#4093 index-alphabetic-browse.sh: minor fix and improvements
  index-alphabetic-browse.sh
Labels: bugfix, improvement

#4107 Include badge in facet link.
  module/VuFind/src/VuFindTest/Feature/SearchFacetFilterTrait.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchFacetsTest.php
  themes/bootstrap3/templates/Recommend/SideFacets/checkbox-filters.phtml
  themes/bootstrap3/templates/Recommend/SideFacets/single-facet.phtml
  themes/bootstrap5/templates/Recommend/SideFacets/checkbox-filters.phtml
  themes/bootstrap5/templates/Recommend/SideFacets/single-facet.phtml
Labels: bugfix

#4110 Drop remnants of IE support.
  module/VuFindTheme/tests/unit-tests/src/VuFindTest/ThemeResourceContainerTest.php
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/js/vendor/flot/excanvas.min.js
  themes/bootstrap3/less/components/record.less
  themes/bootstrap3/scss/components/record.scss
  themes/bootstrap3/templates/Recommend/PubDateVisAjax.phtml
  themes/bootstrap3/templates/layout/layout.phtml
  themes/bootstrap3/theme.config.php
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/js/vendor/flot/excanvas.min.js
  themes/bootstrap5/scss/components/record.scss
  themes/bootstrap5/templates/Recommend/PubDateVisAjax.phtml
  themes/bootstrap5/templates/layout/layout.phtml
  themes/bootstrap5/theme.config.php
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal5/css/compiled.css
Labels: architecture

#4104 Reduce use of Config objects in CspHeaderGenerator
  module/VuFind/src/VuFind/Security/CspHeaderGenerator.php
Labels: architecture

#4115 Simplify config reading in MultiIdpConfigurationLoader.
  module/VuFind/src/VuFind/Auth/Shibboleth/MultiIdPConfigurationLoader.php
Labels: architecture

#4118 Stop using laminas-config-specific exceptions.
  module/VuFind/src/VuFind/ILS/Driver/AbstractMultiDriver.php
  module/VuFind/tests/unit-tests/src/VuFindTest/ILS/Driver/AbstractMultiDriverTestCase.php
  module/VuFind/tests/unit-tests/src/VuFindTest/ILS/Driver/ComposedDriverTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/ILS/Driver/MultiBackendTest.php
Labels: architecture

#4120 Fix AJAX facet handling issues.
  module/VuFind/src/VuFind/AjaxHandler/GetSideFacets.php
  themes/bootstrap3/js/facets.js
  themes/bootstrap5/js/facets.js
Labels: bugfix

#4126 Primo REST: Add record attribute and CDI full text search support.
  config/vufind/Primo.ini
  languages/RecordAttribute/en.ini
  languages/RecordAttribute/fi.ini
  languages/RecordAttribute/sv.ini
  languages/aliases.ini
  languages/ar.ini
  languages/bn.ini
  languages/ca.ini
  languages/cs.ini
  languages/cy.ini
  languages/de.ini
  languages/el.ini
  languages/en.ini
  languages/es.ini
  languages/eu.ini
  languages/fi.ini
  languages/fr.ini
  languages/ga.ini
  languages/gl.ini
  languages/hi.ini
  languages/hr.ini
  languages/hy.ini
  languages/it.ini
  languages/ja.ini
  languages/mi.ini
  languages/mn.ini
  languages/nl.ini
  languages/pl.ini
  languages/pt-br.ini
  languages/pt.ini
  languages/ru.ini
  languages/se.ini
  languages/sv.ini
  languages/tr.ini
  languages/uk.ini
  languages/vi.ini
  module/VuFind/src/VuFind/Search/Factory/PrimoBackendFactory.php
  module/VuFindSearch/src/VuFindSearch/Backend/Primo/Backend.php
  module/VuFindSearch/src/VuFindSearch/Backend/Primo/Response/RecordCollectionFactory.php
  module/VuFindSearch/src/VuFindSearch/Backend/Primo/RestConnector.php
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/components/record.less
  themes/bootstrap3/scss/components/record.scss
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/core.phtml
  themes/bootstrap3/templates/RecordDriver/EDS/core.phtml
  themes/bootstrap3/templates/RecordDriver/EPF/core.phtml
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/scss/components/record.scss
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/core.phtml
  themes/bootstrap5/templates/RecordDriver/EDS/core.phtml
  themes/bootstrap5/templates/RecordDriver/EPF/core.phtml
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal5/css/compiled.css
Labels: improvement
