Repository vufind-org/vufind, pull requests merged in 2024-01, with the labels that each got.

#3249 Translation aliasing
  languages/CreatorRoles/aliases.ini
  languages/CreatorRoles/ar.ini
  languages/CreatorRoles/bn.ini
  languages/CreatorRoles/ca.ini
  languages/CreatorRoles/cs.ini
  languages/CreatorRoles/cy.ini
  languages/CreatorRoles/de.ini
  languages/CreatorRoles/el.ini
  languages/CreatorRoles/en.ini
  languages/CreatorRoles/es.ini
  languages/CreatorRoles/eu.ini
  languages/CreatorRoles/fi.ini
  languages/CreatorRoles/fr.ini
  languages/CreatorRoles/ga.ini
  languages/CreatorRoles/hi.ini
  languages/CreatorRoles/hr.ini
  languages/CreatorRoles/hy.ini
  languages/CreatorRoles/it.ini
  languages/CreatorRoles/ja.ini
  languages/CreatorRoles/mn.ini
  languages/CreatorRoles/nl.ini
  languages/CreatorRoles/pl.ini
  languages/CreatorRoles/pt-br.ini
  languages/CreatorRoles/ru.ini
  languages/CreatorRoles/sv.ini
  languages/CreatorRoles/tr.ini
  languages/CreatorRoles/uk.ini
  languages/CreatorRoles/vi.ini
  module/VuFind/src/VuFind/I18n/Translator/Loader/ExtendedIni.php
  module/VuFind/tests/fixtures/language/aliases/Domain/aliases.ini
  module/VuFind/tests/fixtures/language/aliases/Domain/en-gb.ini
  module/VuFind/tests/fixtures/language/aliases/Domain/en.ini
  module/VuFind/tests/fixtures/language/aliases/aliases.ini
  module/VuFind/tests/fixtures/language/aliases/en-gb.ini
  module/VuFind/tests/fixtures/language/aliases/en.ini
  module/VuFind/tests/fixtures/language/circularaliases/Domain/aliases.ini
  module/VuFind/tests/fixtures/language/circularaliases/aliases.ini
  module/VuFind/tests/fixtures/language/circularaliases/en.ini
  module/VuFind/tests/unit-tests/src/VuFindTest/I18n/Translator/Loader/ExtendedIniTest.php
  module/VuFindConsole/src/VuFindConsole/Command/Language/AbstractCommand.php
  module/VuFindDevTools/src/VuFindDevTools/LanguageHelper.php
  module/VuFindDevTools/tests/unit-tests/src/VuFindTest/LanguageHelperTest.php
  themes/bootstrap3/templates/devtools/language.phtml
Labels: new feature

#3269 New items improvements
  config/vufind/facets.ini
  config/vufind/searches.ini
  module/VuFind/src/VuFind/Controller/AbstractSolrSearch.php
  module/VuFind/src/VuFind/Controller/Plugin/NewItems.php
  module/VuFind/src/VuFind/Controller/SearchController.php
  module/VuFind/src/VuFind/Search/Base/FacetCache.php
  module/VuFind/src/VuFind/Search/Solr/Params.php
  themes/bootstrap3/templates/search/advanced/solr-facets.phtml
  themes/bootstrap3/templates/search/advanced/solr.phtml
  themes/bootstrap3/templates/search/controls/showing.phtml
  themes/bootstrap3/templates/search/newitem.phtml
Labels: bugfix, new feature

#3276 Handling bad MARC records
  composer.json
  composer.lock
  languages/cs.ini
  languages/en.ini
  module/VuFind/src/VuFind/RecordDriver/Feature/MarcAdvancedTrait.php
  themes/bootstrap3/templates/RecordTab/staffviewmarc.phtml
Labels: bugfix

#3287 Summon: throw exception if record not found
  module/VuFindSearch/src/VuFindSearch/Backend/Summon/Backend.php
Labels: bugfix, small

#3258 Combined: Display noresults recommendations in bento box or sidebar
  config/vufind/combined.ini
  module/VuFind/src/VuFind/Controller/CombinedController.php
  themes/bootstrap3/templates/combined/results-list.phtml
Labels: new feature

#3283 Refactor deferred recommendation modules into one template
  themes/bootstrap3/templates/Recommend/AbstractSearchObjectDeferred.phtml
  themes/bootstrap3/templates/Recommend/EDSResultsDeferred.phtml
  themes/bootstrap3/templates/Recommend/EPFResultsDeferred.phtml
  themes/bootstrap3/templates/Recommend/LibGuidesAZResultsDeferred.phtml
  themes/bootstrap3/templates/Recommend/LibGuidesResultsDeferred.phtml
  themes/bootstrap3/templates/Recommend/OpenLibrarySubjectsDeferred.phtml
  themes/bootstrap3/templates/Recommend/SummonBestBetsDeferred.phtml
  themes/bootstrap3/templates/Recommend/SummonDatabasesDeferred.phtml
  themes/bootstrap3/templates/Recommend/SummonResultsDeferred.phtml
Labels: improvement, small

#3200 Add ISO 639-3 language code translations.
  composer.json
  composer.lock
  config/vufind/facets.ini
  languages/ISO639-3/aliases.ini
  languages/ISO639-3/ar.ini
  languages/ISO639-3/bn.ini
  languages/ISO639-3/ca.ini
  languages/ISO639-3/cs.ini
  languages/ISO639-3/cy.ini
  languages/ISO639-3/da.ini
  languages/ISO639-3/de.ini
  languages/ISO639-3/el.ini
  languages/ISO639-3/en-gb.ini
  languages/ISO639-3/en.ini
  languages/ISO639-3/es.ini
  languages/ISO639-3/eu.ini
  languages/ISO639-3/fi.ini
  languages/ISO639-3/fr.ini
  languages/ISO639-3/ga.ini
  languages/ISO639-3/gl.ini
  languages/ISO639-3/he.ini
  languages/ISO639-3/hi.ini
  languages/ISO639-3/hr.ini
  languages/ISO639-3/hy.ini
  languages/ISO639-3/it.ini
  languages/ISO639-3/ja.ini
  languages/ISO639-3/mn.ini
  languages/ISO639-3/nl-be.ini
  languages/ISO639-3/nl.ini
  languages/ISO639-3/pl.ini
  languages/ISO639-3/pt-br.ini
  languages/ISO639-3/pt.ini
  languages/ISO639-3/ru.ini
  languages/ISO639-3/se.ini
  languages/ISO639-3/sl.ini
  languages/ISO639-3/sv.ini
  languages/ISO639-3/tr.ini
  languages/ISO639-3/uk.ini
  languages/ISO639-3/vi.ini
  languages/ISO639-3/zh-cn.ini
  languages/ISO639-3/zh.ini
  module/VuFind/src/VuFind/I18n/Translator/Loader/ExtendedIni.php
  module/VuFind/src/VuFind/View/Helper/Root/RecordDataFormatterFactory.php
  package.json
  util/i18n/create_language_translations.js
  util/i18n/update_language_names_from_lexvo.php
Labels: architecture

#3295 Refactor versions search to fix deferred facets and simplify code.
  module/VuFind/config/module.config.php
  module/VuFind/src/VuFind/Controller/Feature/RecordVersionsSearchTrait.php
  module/VuFind/src/VuFind/Record/VersionsHelper.php
  module/VuFind/src/VuFind/Record/VersionsHelperFactory.php
  module/VuFind/src/VuFind/RecordDriver/Feature/VersionAwareTrait.php
  module/VuFind/src/VuFind/Search/QueryAdapter.php
  module/VuFind/src/VuFind/Search/UrlQueryHelper.php
  module/VuFind/src/VuFind/View/Helper/Root/RecordLinker.php
  module/VuFind/tests/fixtures/searches/advanced/min
  module/VuFind/tests/fixtures/searches/advanced/min-legacy
  module/VuFind/tests/fixtures/searches/basic/min
  module/VuFind/tests/fixtures/searches/basic/min-legacy
  module/VuFind/tests/fixtures/searches/workkeys/min
  module/VuFind/tests/fixtures/searches/workkeys/query
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/QueryAdapterTest.php
  module/VuFindSearch/src/VuFindSearch/Backend/Solr/Backend.php
  module/VuFindSearch/src/VuFindSearch/Command/WorkExpressionsCommand.php
  module/VuFindSearch/src/VuFindSearch/Feature/WorkExpressionsInterface.php
  module/VuFindSearch/src/VuFindSearch/Query/WorkKeysQuery.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Command/WorkExpressionsCommandTest.php
Labels: architecture

#3292 Add a view helper for bulk options, checkboxes and cart controls.
  module/VuFind/src/VuFind/Controller/AbstractSearch.php
  module/VuFind/src/VuFind/Controller/CombinedController.php
  module/VuFind/src/VuFind/Search/Combined/Options.php
  module/VuFind/src/VuFind/Search/Combined/OptionsFactory.php
  module/VuFind/src/VuFind/Search/Options/PluginManager.php
  module/VuFind/src/VuFind/View/Helper/Root/SearchSettings.php
  module/VuFind/src/VuFind/View/Helper/Root/SearchSettingsFactory.php
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/result-grid.phtml
  themes/bootstrap3/templates/combined/results-list.phtml
  themes/bootstrap3/templates/combined/results.phtml
  themes/bootstrap3/templates/combined/stack-distributed.phtml
  themes/bootstrap3/templates/combined/stack-grid.phtml
  themes/bootstrap3/templates/combined/stack-left.phtml
  themes/bootstrap3/templates/combined/stack-right.phtml
  themes/bootstrap3/templates/search/bulk-action-buttons.phtml
  themes/bootstrap3/templates/search/list-list.phtml
  themes/bootstrap3/templates/search/results.phtml
  themes/root/theme.config.php
Labels: architecture

#3270 Search a consortial VuFind instance, i.e. ReShare
  config/vufind/ExternalVuFind.ini
  config/vufind/searches.ini
  languages/en.ini
  module/VuFind/config/module.config.php
  module/VuFind/src/VuFind/Connection/ExternalVuFind.php
  module/VuFind/src/VuFind/Recommend/ConsortialVuFind.php
  module/VuFind/src/VuFind/Recommend/ConsortialVuFindDeferred.php
  module/VuFind/src/VuFind/Recommend/ConsortialVuFindFactory.php
  module/VuFind/src/VuFind/Recommend/PluginManager.php
  module/VuFind/tests/fixtures/externalvufind/search
  module/VuFind/tests/unit-tests/src/VuFindTest/Recommend/ConsortialVuFindTest.php
  themes/bootstrap3/templates/Recommend/ConsortialVuFind.phtml
Labels: new feature

#3299 Add tests for the getItems function in the EDS driver
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordDriver/EDSTest.php
Labels: tests

#3251 Add translations for keyboard layouts.
  config/vufind/searchbox.ini
  languages/KeyboardLayout/aliases.ini
  languages/KeyboardLayout/en-gb.ini
  languages/KeyboardLayout/en.ini
  languages/KeyboardLayout/nl-be.ini
  languages/KeyboardLayout/nl.ini
  languages/KeyboardLayout/pt-br.ini
  languages/KeyboardLayout/pt.ini
  languages/KeyboardLayout/zh-cn.ini
  languages/KeyboardLayout/zh.ini
  themes/bootstrap3/templates/search/searchbox.phtml
Labels: improvement

#3288 XCNCIP2: Handle ItemUseRestrictionType
  config/vufind/XCNCIP2.ini
  module/VuFind/src/VuFind/ILS/Driver/XCNCIP2.php
  module/VuFind/tests/unit-tests/src/VuFindTest/ILS/Driver/XCNCIP2Test.php
Labels: improvement, small

#3303 Throw exception when full MARC record is missing.
  module/VuFind/src/VuFind/RecordDriver/Feature/MarcReaderTrait.php
Labels: bugfix

#3302 Add complete unit tests for EDS driver
  module/VuFind/src/VuFind/RecordDriver/EDS.php
  module/VuFind/tests/fixtures/eds/dissertation-record.json
  module/VuFind/tests/fixtures/eds/invalid-pubformat-record.json
  module/VuFind/tests/fixtures/eds/no-container-end-page.json
  module/VuFind/tests/fixtures/eds/publication-details-no-date.json
  module/VuFind/tests/fixtures/eds/publication-details-unmatched-format.json
  module/VuFind/tests/fixtures/eds/valid-eds-record-2.json
  module/VuFind/tests/fixtures/eds/valid-eds-record.json
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordDriver/EDSTest.php
Labels: tests

#2929 Add an option to update search results without loading the full page.
  config/vufind/Blender.ini
  config/vufind/BrowZine.ini
  config/vufind/EDS.ini
  config/vufind/EIT.ini
  config/vufind/EPF.ini
  config/vufind/LibGuides.ini
  config/vufind/LibGuidesAPI.ini
  config/vufind/Primo.ini
  config/vufind/RecordTabs.ini
  config/vufind/Search2.ini
  config/vufind/authority.ini
  config/vufind/reserves.ini
  config/vufind/searches.ini
  module/VuFind/src/VuFind/AjaxHandler/GetSearchResults.php
  module/VuFind/src/VuFind/AjaxHandler/GetSearchResultsFactory.php
  module/VuFind/src/VuFind/AjaxHandler/PluginManager.php
  module/VuFind/src/VuFind/Controller/AbstractSearch.php
  module/VuFind/src/VuFind/Search/Base/Options.php
  module/VuFind/src/VuFind/Search/Base/Params.php
  module/VuFind/src/VuFindTest/Feature/SearchSortTrait.php
  module/VuFind/src/VuFindTest/Integration/MinkTestCase.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AdvancedSearchTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AuthorControllerTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/BasicSearchTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/JumpToRecordTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/RecordActionsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchFacetsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchLimitTest.php
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/js/common.js
  themes/bootstrap3/js/search.js
  themes/bootstrap3/less/components/search.less
  themes/bootstrap3/scss/components/search.scss
  themes/bootstrap3/templates/Helpers/analytics.phtml
  themes/bootstrap3/templates/Helpers/openurl.phtml
  themes/bootstrap3/templates/RecordTab/versions.phtml
  themes/bootstrap3/templates/combined/results-ajax.phtml
  themes/bootstrap3/templates/layout/layout.phtml
  themes/bootstrap3/templates/search/controls/limit.phtml
  themes/bootstrap3/templates/search/controls/showing.phtml
  themes/bootstrap3/templates/search/controls/sort.phtml
  themes/bootstrap3/templates/search/facet-list.phtml
  themes/bootstrap3/templates/search/list-grid.phtml
  themes/bootstrap3/templates/search/list-list.phtml
  themes/bootstrap3/templates/search/pagination.phtml
  themes/bootstrap3/templates/search/pagination_simple.phtml
  themes/bootstrap3/templates/search/results-list.phtml
  themes/bootstrap3/templates/search/results-scripts.phtml
  themes/bootstrap3/templates/search/results.phtml
  themes/bootstrap3/theme.config.php
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
Labels: improvement

#3298 Raise minimum PHP version to 8.1; add 8.3 to GitHub Actions.
  .github/workflows/ci.yaml
  composer.json
  composer.lock
  module/VuFind/tests/fixtures/spell/query6
  module/VuFind/tests/fixtures/spell/spell6
  module/VuFind/tests/unit-tests/src/VuFindTest/Controller/InstallControllerTest.php
  module/VuFindSearch/tests/fixtures/eds/response/autocomplete
  tests/vufind.php-cs-fixer.php
  tests/vufind_templates.php-cs-fixer.php
  themes/bootstrap3/templates/combined/stack-distributed.phtml
  themes/bootstrap3/templates/combined/stack-grid.phtml
  themes/bootstrap3/templates/combined/stack-left.phtml
  themes/bootstrap3/templates/combined/stack-right.phtml
Labels: php, tooling

#3306 PHPUnit 10 prep: Fix naming of abstract test classes.
  module/VuFind/src/VuFindTest/Unit/AbstractMakeTagTestCase.php
  module/VuFind/src/VuFindTest/Unit/AjaxHandlerTestCase.php
  module/VuFind/tests/unit-tests/src/VuFindTest/AjaxHandler/CheckRequestIsValidTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/AjaxHandler/CommentRecordTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/AjaxHandler/DoiLookupTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/AjaxHandler/GetResolverLinksTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/AjaxHandler/KeepAliveTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/AjaxHandler/RecommendTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/ILS/Driver/AbstractMultiDriverTestCase.php
  module/VuFind/tests/unit-tests/src/VuFindTest/ILS/Driver/ComposedDriverTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/ILS/Driver/MultiBackendTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/OAuth2/Repository/AbstractTokenRepositoryTestCase.php
  module/VuFind/tests/unit-tests/src/VuFindTest/OAuth2/Repository/AccessTokenRepositoryTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/OAuth2/Repository/AuthCodeRepositoryTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/OAuth2/Repository/IdentityRepositoryTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/OAuth2/Repository/RefreshTokenRepositoryTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/OAuth2/Repository/ScopeRepositoryTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/MakeLinkTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/MakeTagTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/PrintArrayHtmlTest.php
Labels: tooling, tests

#3256 JS: HTML escape update
  themes/bootstrap3/js/check_save_statuses.js
  themes/bootstrap3/js/common.js
  themes/bootstrap3/js/pubdate_vis.js
Labels: improvement

#3305 Switch PHPUnit tests to use static data providers.
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AlphabrowseTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AuthorControllerTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/BasicSearchTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/BlendedSearchTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/FavoritesTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/HoldingsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/IlsActionsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/RecordActionsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchFacetsTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/AjaxHandler/DoiLookupTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/DatabaseUnitTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Captcha/ImageFactoryTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Config/PathResolverTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Content/Covers/KohaTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Crypt/Base62Test.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Form/FormTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/I18n/ExtendedIniNormalizerTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/I18n/Locale/LocaleSettingsTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/OAuth2/Repository/IdentityRepositoryTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/OAuth2/Repository/ScopeRepositoryTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Recommend/SwitchTabTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Recommend/SwitchTypeTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordDriver/DefaultRecordTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordDriver/EDSTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordTab/ComponentPartsTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordTab/FormatsTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordTab/HoldingsWorldCatTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordTab/PreviewTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordTab/TOCTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordTab/UserCommentsTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordTab/VersionsTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/Blender/OptionsTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/QueryAdapterTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/Solr/ParamsTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Service/Feature/RetryTraitTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/UrlHighlight/VuFindHighlighterTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/FlashmessagesTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/HoldingsTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/HtmlSafeJsonEncodeTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/IconTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/MakeTagTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/PrintArrayHtmlTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/RecordDataFormatterTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/RecordTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/SearchMemoryTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/SearchTabsTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/XSLT/Import/VuFindTest.php
  module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Util/PurgeCachedRecordCommandTest.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/Blender/BackendTest.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/Primo/BackendTest.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/Solr/LuceneSyntaxHelperTest.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/Solr/QueryBuilderTest.php
  tests/vufind.php-cs-fixer.php
Labels: tooling, tests

#3308 Implement responsive table for fines.
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/bootstrap.less
  themes/bootstrap3/scss/bootstrap.scss
  themes/bootstrap3/templates/myresearch/fines.phtml
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
Labels: accessibility, small

#3304 Apply recommended php-cs-fixer rules for PHP 8.1.
  module/VuFind/src/VuFind/Cache/Manager.php
  module/VuFind/src/VuFind/Sitemap/AbstractFile.php
  module/VuFind/tests/bootstrap.php
  module/VuFindTheme/tests/unit-tests/src/VuFindTest/CssPreCompilerTest.php
  tests/vufind.php-cs-fixer.php
  tests/vufind_templates.php-cs-fixer.php
Labels: improvement, tooling

#3315 Accessibility: Use ul/li for recommendation module lists
  themes/bootstrap3/templates/Recommend/Databases.phtml
  themes/bootstrap3/templates/Recommend/EDSResults.phtml
  themes/bootstrap3/templates/Recommend/EPFResults.phtml
  themes/bootstrap3/templates/Recommend/LibGuidesAZResults.phtml
  themes/bootstrap3/templates/Recommend/LibGuidesResults.phtml
  themes/bootstrap3/templates/Recommend/SummonResults.phtml
Labels: accessibility

#3319 Reset "Select all" when search results are updated.
  themes/bootstrap3/js/search.js
Labels: bugfix

#3322 Remove obsolete CLI CSS builder tool.
  util/cssBuilder.php
Labels: bugfix

#3318 Language tool: ISO639-3 text domain should be optional.
  module/VuFindDevTools/src/VuFindDevTools/LanguageHelper.php
Labels: tooling, small

#3277 Refactor hierarchy tree to an HTML-based one.
  config/vufind/HierarchyDefault.ini
  config/vufind/HierarchyFlat.ini
  module/VuFind/src/VuFind/Controller/HierarchyController.php
  module/VuFind/src/VuFind/Hierarchy/Driver/AbstractBase.php
  module/VuFind/src/VuFind/Hierarchy/Driver/ConfigurationBased.php
  module/VuFind/src/VuFind/Hierarchy/TreeDataFormatter/PluginManager.php
  module/VuFind/src/VuFind/Hierarchy/TreeDataFormatter/Xml.php
  module/VuFind/src/VuFind/Hierarchy/TreeDataSource/AbstractBase.php
  module/VuFind/src/VuFind/Hierarchy/TreeDataSource/PluginManager.php
  module/VuFind/src/VuFind/Hierarchy/TreeDataSource/XMLFile.php
  module/VuFind/src/VuFind/Hierarchy/TreeRenderer/AbstractBase.php
  module/VuFind/src/VuFind/Hierarchy/TreeRenderer/HTMLTree.php
  module/VuFind/src/VuFind/Hierarchy/TreeRenderer/HTMLTreeFactory.php
  module/VuFind/src/VuFind/Hierarchy/TreeRenderer/JSTree.php
  module/VuFind/src/VuFind/Hierarchy/TreeRenderer/PluginManager.php
  module/VuFind/src/VuFind/RecordTab/AbstractBase.php
  module/VuFind/src/VuFind/RecordTab/CollectionHierarchyTree.php
  module/VuFind/src/VuFind/RecordTab/HierarchyTree.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/CollectionsTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordTab/CollectionHierarchyTreeTest.php
  module/VuFind/xsl/Hierarchy/CollectionTree.xsl
  module/VuFind/xsl/Hierarchy/RecordTree.xsl
  module/VuFindConsole/src/VuFindConsole/Command/Util/CreateHierarchyTreesCommand.php
  module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Util/CreateHierarchyTreesCommandTest.php
  themes/bootprint3/css/compiled.css
  themes/bootprint3/less/bootprint.less
  themes/bootprint3/scss/bootprint.scss
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/js/hierarchyTree.js
  themes/bootstrap3/js/hierarchy_tree.js
  themes/bootstrap3/js/vendor/jsTree/jstree.min.js
  themes/bootstrap3/less/bootstrap.less
  themes/bootstrap3/less/components/js-tree.less
  themes/bootstrap3/less/components/sidebar.less
  themes/bootstrap3/less/components/trees.less
  themes/bootstrap3/package.json
  themes/bootstrap3/scss/bootstrap.scss
  themes/bootstrap3/scss/components/js-tree.scss
  themes/bootstrap3/scss/components/sidebar.scss
  themes/bootstrap3/scss/components/trees.scss
  themes/bootstrap3/templates/Recommend/SideFacets/facet.phtml
  themes/bootstrap3/templates/RecordTab/collectionhierarchytree.phtml
  themes/bootstrap3/templates/RecordTab/hierarchytree.phtml
  themes/bootstrap3/templates/hierarchy/tree.phtml
  themes/bootstrap3/theme.config.php
  themes/bootstrap3/tools/copyDependencies.mjs
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal/less/sandal.less
  themes/sandal/scss/sandal.scss
  util/createHierarchyTrees.php
Labels: improvement, architecture

#3307 Add translations for service type
  languages/ServiceType/de.ini
  languages/ServiceType/en.ini
  themes/bootstrap3/templates/ajax/resolverLink.phtml
Labels: improvement, small

#3317 Add Māori language support.
  config/vufind/config.ini
  languages/ISO639-3/mi.ini
  languages/mi.ini
  languages/native.ini
Labels: new feature

#3323 Fix work key UTF-8 trimming bug.
  module/VuFind/src/VuFind/XSLT/Import/VuFindWorkKeys.php
  module/VuFind/tests/unit-tests/src/VuFindTest/XSLT/Import/VuFindWorkKeysTest.php
Labels: bugfix

#3325 Fix hierarchical facet filters in advanced search.
  module/VuFind/src/VuFind/Controller/AbstractSolrSearch.php
Labels: bugfix

#3321 Bootprint3 theme: fix alignment of advanced search delete icon.
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/components/advanced-search.less
  themes/bootstrap3/scss/components/advanced-search.scss
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
Labels: bugfix, small

#3309 Refactored Search Tabs
  module/VuFind/src/VuFind/Controller/CombinedController.php
  module/VuFind/src/VuFind/Controller/Plugin/ResultScroller.php
  module/VuFind/src/VuFind/Recommend/PubDateVisAjax.php
  module/VuFind/src/VuFind/Search/Base/Results.php
  module/VuFind/src/VuFind/Search/SearchTabsHelper.php
  module/VuFind/src/VuFind/View/Helper/Root/SearchTabs.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/SearchTabsTest.php
  module/VuFindApi/src/VuFindApi/Formatter/FacetFormatter.php
  themes/bootstrap3/js/resultcount.js
  themes/bootstrap3/templates/combined/stack-distributed.phtml
  themes/bootstrap3/templates/combined/stack-grid.phtml
  themes/bootstrap3/templates/combined/stack-left.phtml
  themes/bootstrap3/templates/combined/stack-right.phtml
  themes/bootstrap3/templates/search/searchTabs.phtml
Labels: architecture, small

#3244 Improve Overdrive Staff View
  module/VuFind/src/VuFind/RecordDriver/SolrOverdrive.php
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordDriver/SolrOverdriveTest.php
  themes/bootstrap3/templates/RecordDriver/SolrOverdrive/core.phtml
  themes/bootstrap3/templates/RecordTab/staffviewoverdrive.phtml
Labels: bugfix

#3327 Fix tag sorting in PostgreSQL.
  module/VuFind/src/VuFind/Db/Table/Resource.php
Labels: bugfix

#3316 Usernames should be consistently case-insensitive.
  module/VuFind/src/VuFind/Db/Table/User.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AccountActionsTest.php
Labels: improvement, small

#3329 Add missing Koha cover configuration line.
  module/VuFind/src/VuFind/Content/Covers/PluginManager.php
Labels: bugfix

#3332 Add a test for hierarchical facets in advanced search.
  module/VuFind/src/VuFindTest/Feature/SearchFacetFilterTrait.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AdvancedSearchTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchFacetsTest.php
Labels: tests

#3331 Simplify MultiAuthTest.
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/MultiAuthTest.php
Labels: small, tests

#3337 Handle %size% token when using local file in coverimages
  module/VuFind/src/VuFind/Content/Covers/LocalFile.php
  module/VuFind/tests/fixtures/content/covers/localfile/0739313126.gif
  module/VuFind/tests/fixtures/content/covers/localfile/9780739313121.jpg
  module/VuFind/tests/fixtures/content/covers/localfile/invalidsize/x.gif
  module/VuFind/tests/fixtures/content/covers/localfile/small/x.gif
  module/VuFind/tests/unit-tests/src/VuFindTest/Content/Covers/LocalFileTest.php
Labels: bugfix

#3335 Closing lightbox after returning from SSO
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/HoldsTest.php
  themes/bootstrap3/js/lightbox.js
Labels: bugfix

#3339 Refactored hold login
  module/VuFind/config/module.config.php
  module/VuFind/src/VuFind/Controller/MyResearchController.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/HoldsTest.php
  themes/bootstrap3/js/lightbox.js
  themes/bootstrap3/templates/RecordTab/holdingsils.phtml
Labels: improvement

#3340 Improve browscap.ini error handling.
  module/VuFind/src/VuFind/Auth/LoginTokenManager.php
Labels: improvement

#3341 Eliminate deprecated setMethods and setMethodsExcept calls.
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordDriver/DefaultRecordTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/NormalizedSearchTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/SearchNormalizerTest.php
  module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Language/ImportLokaliseCommandTest.php
Labels: tests

#3346 Fix/improve theme selector behavior; add Mink test.
  module/VuFind/src/VuFind/Auth/LoginTokenManager.php
  module/VuFind/src/VuFind/Auth/LoginTokenManagerFactory.php
  module/VuFind/src/VuFind/Bootstrapper.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/BasicTest.php
  module/VuFindTheme/src/VuFindTheme/Initializer.php
  themes/bootstrap3/templates/header.phtml
Labels: bugfix

#3349 Add Mink test to cover different session settings.
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AccountActionsTest.php
Labels: tests

#3347 UrlQueryHelper::asHiddenFields, nullcoalesce null values in htmlspecialchars
  module/VuFind/src/VuFind/Search/UrlQueryHelper.php
Labels: small

#3348 FOLIO: Improve json_log_file behavior/documentation
  config/vufind/Folio.ini
  module/VuFind/src/VuFind/ILS/Driver/AbstractAPI.php
Labels: improvement

#3333 Fix account menu dropdown and sandal's account notification icon.
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/js/account_ajax.js
  themes/bootstrap3/less/bootstrap.less
  themes/bootstrap3/scss/bootstrap.scss
  themes/bootstrap3/templates/header.phtml
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal/less/sandal.less
  themes/sandal/scss/sandal.scss
Labels: bugfix

#3351 Simplify mock returns in LoginTokenManagerTest.
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/LoginTokenManagerTest.php
Labels: tests

#3353 Simplify and type Auth tests.
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/LDAPTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/SIP2Test.php
Labels: tests

#3262 INN-Reach Account Integration
  config/vufind/SierraRest.ini
  module/VuFind/src/VuFind/ILS/Driver/SierraRest.php
Labels: new feature

#3344 HierarchyAwareTrait: cast return value of getters into arrays
  module/VuFind/src/VuFind/RecordDriver/Feature/HierarchyAwareTrait.php
Labels: small

#3326 Make sandal font size more uniform.
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/less/bootstrap.less
  themes/bootstrap3/scss/bootstrap.scss
  themes/sandal/css/compiled.css
  themes/sandal/less/common.less
  themes/sandal/less/sandal.less
  themes/sandal/less/search.less
  themes/sandal/less/variables.less
  themes/sandal/scss/common.scss
  themes/sandal/scss/sandal.scss
  themes/sandal/scss/search.scss
  themes/sandal/scss/variables.scss
Labels: improvement

#3350 PHPUnit: Eliminate deprecated withConsecutive calls.
  module/VuFind/src/VuFindTest/Feature/WithConsecutiveTrait.php
  module/VuFind/tests/unit-tests/src/VuFindTest/CartTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/ChannelProvider/AlphaBrowseTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/ChannelProvider/SimilarItemsTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Content/Covers/BokinfoTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/ExportTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/ILS/Driver/GeniePlusTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Record/LoaderTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordTab/MapTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordTab/TOCTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/Solr/InjectHighlightingListenerTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Sitemap/Plugin/Index/CursorMarkIdFetcherTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Sitemap/Plugin/Index/TermsIdFetcherTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Sitemap/Plugin/IndexTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/RecordTest.php
  module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Import/WebCrawlCommandTest.php
  module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Install/InstallCommandTest.php
  module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Language/ImportLokaliseCommandTest.php
  module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Util/AbstractExpireCommandTest.php
  module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Util/DedupeCommandTest.php
  module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Util/IndexReservesCommandTest.php
  module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Util/SwitchDbHashCommandTest.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/Blender/BackendTest.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/LibGuides/BackendTest.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/Solr/ConnectorTest.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/Summon/BackendTest.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Command/RandomCommandTest.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Command/RetrieveBatchCommandTest.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/SearchServiceTest.php
Labels: tests

#3354 Tweak Mink tests, part 2
  module/VuFind/src/VuFindTest/Feature/AutoRetryTrait.php
  module/VuFind/src/VuFindTest/Feature/DemoDriverTestTrait.php
  module/VuFind/src/VuFindTest/Integration/MinkTestCase.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AccountActionsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AdvancedSearchTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/ApiTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/FeedbackTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/HoldsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/IlsActionsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/LibraryCardsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/ListViewsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/RecordActionsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SsoTest.php
Labels: tests

#3356 Adjust PHPUnit .gitignore for forward compatibility.
  .gitignore
Labels: tooling

#3358 Refactor search minification, change QueryAdapter to a concrete class.
  module/VuFind/src/VuFind/Search/Base/Params.php
  module/VuFind/src/VuFind/Search/Base/Results.php
  module/VuFind/src/VuFind/Search/EDS/Params.php
  module/VuFind/src/VuFind/Search/EDS/QueryAdapter.php
  module/VuFind/src/VuFind/Search/Minified.php
  module/VuFind/src/VuFind/Search/QueryAdapter.php
  module/VuFind/src/VuFind/Search/QueryAdapterInterface.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/Base/ParamsTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/NormalizedSearchTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/QueryAdapterTest.php
Labels: architecture

#3064 Autocomplete: reorganize modules and update to v2.1.8
  themes/bootstrap3/js/common.js
  themes/bootstrap3/js/searchbox_controls.js
  themes/bootstrap3/js/vendor/autocomplete.js
  themes/bootstrap3/package.json
Labels: bugfix

#3362 Make account cache test more robust.
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AccountMenuTest.php
Labels: tests

#3364 Tweak hierarchy tree tab a bit.
  themes/bootstrap3/js/hierarchy_tree.js
  themes/bootstrap3/templates/RecordTab/hierarchytree.phtml
Labels: improvement

#3369 Use StorageInterface instead of AbstractAdapter for cache hints.
  module/VuFind/src/VuFind/Recommend/Databases.php
  module/VuFind/src/VuFind/Recommend/LibGuidesProfile.php
  module/VuFind/src/VuFind/View/Helper/Root/ProxyUrl.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Config/YamlReaderTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Recommend/DatabasesTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Recommend/LibGuidesProfileTest.php
  module/VuFindSearch/src/VuFindSearch/Backend/EDS/Backend.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/Blender/BackendTest.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/EDS/BackendTest.php
Labels: architecture, small

#3372 Fix logging of warnings in Mink tests.
  module/VuFind/src/VuFindTest/Integration/MinkTestCase.php
Labels: tests
