Repository vufind-org/vufind, pull requests merged in 2024-03, with the labels that each got.

#3461 Work around illegal characters in translation keys.
  module/VuFind/src/VuFind/I18n/Translator/TranslatorAwareTrait.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/TranslateTest.php
Labels: improvement

#3457 RecordActionsTest: simplify click call.
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/RecordActionsTest.php
Labels: tests

#3466 Sanitize keys during language normalization.
  languages/ISO639-3/aliases.ini
  languages/ISO639-3/de.ini
  languages/ISO639-3/en.ini
  languages/ISO639-3/fr.ini
  module/VuFind/src/VuFind/I18n/ExtendedIniNormalizer.php
  module/VuFind/src/VuFind/I18n/Translator/TranslatorAwareTrait.php
  module/VuFind/tests/unit-tests/src/VuFindTest/I18n/ExtendedIniNormalizerTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/TranslateTest.php
Labels: improvement

#3470 Fix illegal token value in js-translations.phtml
  themes/bootstrap3/templates/layout/js-translations.phtml
Labels: bugfix

#3472 Remove code deprecated in v9.x.
  module/VuFind/src/VuFind/Auth/AbstractBase.php
  module/VuFind/src/VuFind/Recommend/SearchObject.php
  module/VuFindSearch/src/VuFindSearch/Backend/EDS/Backend.php
  module/VuFindSearch/src/VuFindSearch/Backend/EDS/Base.php
Labels: architecture

#3467 Fix broken translation string.
  languages/ISO639-3/de.ini
Labels: bugfix

#3468 Prevent accidental commit of Mink test theme.
  .gitignore
Labels: tooling

#3469 Pop up holdings catalog login in lightbox.
  themes/bootstrap3/templates/RecordTab/holdingsils.phtml
Labels: improvement

#3459 Deprecate isLoggedIn() method.
  module/VuFind/src/VuFind/AjaxHandler/AbstractIlsAndUserActionFactory.php
  module/VuFind/src/VuFind/AjaxHandler/AbstractRelaisActionFactory.php
  module/VuFind/src/VuFind/AjaxHandler/CommentRecordFactory.php
  module/VuFind/src/VuFind/AjaxHandler/DeleteRecordCommentFactory.php
  module/VuFind/src/VuFind/AjaxHandler/GetRecordTagsFactory.php
  module/VuFind/src/VuFind/AjaxHandler/GetSaveStatusesFactory.php
  module/VuFind/src/VuFind/AjaxHandler/GetSearchResultsFactory.php
  module/VuFind/src/VuFind/AjaxHandler/TagRecordFactory.php
  module/VuFind/src/VuFind/Auth/ILSAuthenticator.php
  module/VuFind/src/VuFind/Auth/Manager.php
  module/VuFind/src/VuFind/Bootstrapper.php
  module/VuFind/src/VuFind/Controller/AbstractBase.php
  module/VuFind/src/VuFind/Controller/IndexController.php
  module/VuFind/src/VuFind/Controller/MyResearchController.php
  module/VuFind/src/VuFind/Controller/Plugin/Permission.php
  module/VuFind/src/VuFind/Log/LoggerFactory.php
  module/VuFind/src/VuFind/View/Helper/Root/AccountMenu.php
  module/VuFind/src/VuFind/View/Helper/Root/Auth.php
  module/VuFind/src/VuFindTest/Unit/AjaxHandlerTestCase.php
  module/VuFind/tests/unit-tests/src/VuFindTest/AjaxHandler/CheckRequestIsValidTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/AjaxHandler/CommentRecordTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/ILSAuthenticatorTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/ManagerTest.php
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/data-tags.phtml
  themes/bootstrap3/templates/RecordDriver/SolrOverdrive/core.phtml
  themes/bootstrap3/templates/RecordTab/holdingsils.phtml
  themes/bootstrap3/templates/RecordTab/usercomments.phtml
  themes/bootstrap3/templates/checkouts/history.phtml
  themes/bootstrap3/templates/header.phtml
  themes/bootstrap3/templates/holds/list.phtml
  themes/bootstrap3/templates/layout/layout.phtml
  themes/bootstrap3/templates/myresearch/bulk-action-buttons.phtml
  themes/bootstrap3/templates/myresearch/cataloglogin.phtml
  themes/bootstrap3/templates/myresearch/checkedout.phtml
  themes/bootstrap3/templates/myresearch/editlist.phtml
  themes/bootstrap3/templates/myresearch/fines.phtml
  themes/bootstrap3/templates/myresearch/illrequests.phtml
  themes/bootstrap3/templates/myresearch/menu.phtml
  themes/bootstrap3/templates/myresearch/mylist.phtml
  themes/bootstrap3/templates/myresearch/newpassword.phtml
  themes/bootstrap3/templates/myresearch/profile.phtml
  themes/bootstrap3/templates/myresearch/schedulesearch.phtml
  themes/bootstrap3/templates/myresearch/storageretrievalrequests.phtml
  themes/bootstrap3/templates/record/comments-list.phtml
  themes/bootstrap3/templates/record/rating.phtml
  themes/bootstrap3/templates/search/history.phtml
Labels: architecture

#3471 Implement text domain fallback in translator.
  module/VuFind/src/VuFind/I18n/Translator/TranslatorAwareTrait.php
  module/VuFind/src/VuFind/View/Helper/Root/TransEsc.php
  module/VuFind/src/VuFind/View/Helper/Root/TransEscAttr.php
  module/VuFind/src/VuFind/View/Helper/Root/TransEscWithPrefix.php
  module/VuFind/src/VuFind/View/Helper/Root/Translate.php
  module/VuFind/src/VuFind/View/Helper/Root/TranslationEmpty.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/TranslateTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/TranslationEmptyTest.php
Labels: improvement

#3474 Fix check for OpenURL resolver URL.
  module/VuFind/src/VuFind/View/Helper/Root/OpenUrl.php
Labels: bugfix

#3456 Clean up unused code and variables.
  config/application.php
  module/VuFind/src/VuFind/Auth/AlmaDatabase.php
  module/VuFind/src/VuFind/Auth/ShibbolethFactory.php
  module/VuFind/src/VuFind/RecordDriver/EDS.php
  module/VuFind/src/VuFind/RecordDriver/Feature/MarcAdvancedTrait.php
  module/VuFind/src/VuFind/RecordDriver/SolrOverdrive.php
  module/VuFind/tests/bootstrap.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Auth/ShibbolethTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/CartTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/RecordActionsTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/ManagerTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Db/Table/UserListTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Hierarchy/TreeDataFormatter/JsonTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/I18n/Translator/Loader/ExtendedIniTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/ILS/Driver/AbstractMultiDriverTestCase.php
  module/VuFind/tests/unit-tests/src/VuFindTest/ILS/Driver/FolioTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/ILS/Driver/MultiBackendTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/ILS/Driver/XCNCIP2Test.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Mailer/MailerTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Recommend/DatabasesTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Record/CacheTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordDriver/EDSTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/Solr/ResultsTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Sitemap/Plugin/Index/TermsIdFetcherTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/CspTest.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/SwitchDbHashCommand.php
  module/VuFindSearch/src/VuFindSearch/Backend/Blender/Backend.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/BrowZine/Response/RecordCollectionFactoryTest.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/EDS/Response/RecordCollectionFactoryTest.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/EIT/Response/XML/RecordCollectionFactoryTest.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/LibGuides/Response/RecordCollectionFactoryTest.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/Primo/Response/RecordCollectionFactoryTest.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/Solr/BackendTest.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/Solr/ConnectorTest.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/Solr/Response/Json/RecordCollectionFactoryTest.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/Summon/Response/RecordCollectionFactoryTest.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/WorldCat/Response/XML/RecordCollectionFactoryTest.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Command/SearchCommandTest.php
  module/VuFindTheme/src/VuFindTheme/Initializer.php
  module/VuFindTheme/src/VuFindTheme/View/Helper/Slot.php
  module/VuFindTheme/tests/unit-tests/src/VuFindTest/View/Helper/SlotTest.php
Labels: bugfix, improvement

#3475 Encrypt existing library cards during security setup.
  module/VuFind/src/VuFind/Controller/Feature/SecureDatabaseTrait.php
  module/VuFind/src/VuFind/Controller/InstallController.php
  module/VuFind/src/VuFind/Db/Row/User.php
  module/VuFind/src/VuFind/Db/Table/UserCard.php
Labels: bugfix

#3476 Add library card support to switch_db_hash command.
  config/vufind/config.ini
  module/VuFindConsole/src/VuFindConsole/Command/Util/SwitchDbHashCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/SwitchDbHashCommandFactory.php
  module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Util/SwitchDbHashCommandTest.php
Labels: bugfix

#3481 Fix date validation in OAI server.
  module/VuFind/src/VuFind/OAI/Server.php
Labels: bugfix

#3482 Fix sandal search tabs hover color in search results etc.
  themes/sandal/css/compiled.css
  themes/sandal/less/sandal.less
  themes/sandal/scss/sandal.scss
Labels: improvement

#3487 Sandal theme: Fix style on facet more/less button.
  themes/sandal/css/compiled.css
  themes/sandal/less/sandal.less
  themes/sandal/scss/sandal.scss
Labels: bugfix

#3458 [VUFIND-1583] Add account menu to catalog login screens
  module/VuFind/src/VuFind/Controller/MyResearchController.php
  themes/bootstrap3/templates/myresearch/cataloglogin.phtml
Labels: improvement, small

#3483 Sandal: Fix wonky focus highlight in the search field.
  themes/sandal/css/compiled.css
  themes/sandal/less/sandal.less
  themes/sandal/scss/sandal.scss
Labels: bugfix

#3484 Rename offcanvas to vufind-offcanvas to avoid clash with Bootstrap 5.
  module/VuFind/src/VuFind/View/Helper/Bootstrap3/LayoutClass.php
  themes/bootprint3/css/compiled.css
  themes/bootprint3/less/search.less
  themes/bootprint3/scss/search.scss
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/css/vendor/bootstrap-rtl.min.css
  themes/bootstrap3/js/common.js
  themes/bootstrap3/less/bootstrap.less
  themes/bootstrap3/less/components/offcanvas.less
  themes/bootstrap3/less/components/search.less
  themes/bootstrap3/less/components/sidebar.less
  themes/bootstrap3/scss/bootstrap.scss
  themes/bootstrap3/scss/components/offcanvas.scss
  themes/bootstrap3/scss/components/search.scss
  themes/bootstrap3/scss/components/sidebar.scss
  themes/bootstrap3/templates/Recommend/SideFacets.phtml
  themes/bootstrap3/templates/Recommend/SideFacetsDeferred.phtml
  themes/bootstrap3/templates/checkouts/history.phtml
  themes/bootstrap3/templates/holds/list.phtml
  themes/bootstrap3/templates/layout/layout.phtml
  themes/bootstrap3/templates/myresearch/checkedout.phtml
  themes/bootstrap3/templates/myresearch/edit.phtml
  themes/bootstrap3/templates/myresearch/editlist.phtml
  themes/bootstrap3/templates/myresearch/fines.phtml
  themes/bootstrap3/templates/myresearch/illrequests.phtml
  themes/bootstrap3/templates/myresearch/menu.phtml
  themes/bootstrap3/templates/myresearch/mylist.phtml
  themes/bootstrap3/templates/myresearch/profile.phtml
  themes/bootstrap3/templates/myresearch/schedulesearch.phtml
  themes/bootstrap3/templates/myresearch/storageretrievalrequests.phtml
  themes/bootstrap3/templates/search/history.phtml
  themes/bootstrap3/templates/search/results.phtml
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
Labels: improvement

#3489 Clarify language and menu interface for saved items.
  config/vufind/AccountMenu.yaml
  languages/ar.ini
  languages/bn.ini
  languages/ca.ini
  languages/cs.ini
  languages/cy.ini
  languages/da.ini
  languages/de.ini
  languages/el.ini
  languages/en.ini
  languages/es.ini
  languages/eu.ini
  languages/fi.ini
  languages/fr.ini
  languages/ga.ini
  languages/gl.ini
  languages/he.ini
  languages/hi.ini
  languages/hr.ini
  languages/hy.ini
  languages/it.ini
  languages/ja.ini
  languages/mi.ini
  languages/mn.ini
  languages/nl.ini
  languages/pl.ini
  languages/pt-br.ini
  languages/pt.ini
  languages/ru.ini
  languages/se.ini
  languages/sl.ini
  languages/sv.ini
  languages/tr.ini
  languages/uk.ini
  languages/vi.ini
  languages/zh-cn.ini
  languages/zh.ini
  module/VuFind/src/VuFind/Controller/MyResearchController.php
  module/VuFind/src/VuFind/Favorites/FavoritesService.php
  module/VuFind/src/VuFind/View/Helper/Root/AccountMenu.php
  themes/bootstrap3/templates/cart/save.phtml
  themes/bootstrap3/templates/myresearch/edit.phtml
  themes/bootstrap3/templates/myresearch/menu.phtml
  themes/bootstrap3/templates/myresearch/mylist.phtml
  themes/bootstrap3/templates/record/save.phtml
Labels: improvement

#3496 Add translation for Citations record field.
  languages/en.ini
  languages/fi.ini
  languages/sv.ini
Labels: improvement

#3495 Fix displaying of explain after paging and improve looks.
  module/VuFind/src/VuFind/AjaxHandler/GetSearchResults.php
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/js/common.js
  themes/bootstrap3/less/components/explain.less
  themes/bootstrap3/less/components/search.less
  themes/bootstrap3/scss/components/explain.scss
  themes/bootstrap3/scss/components/search.scss
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/result-list.phtml
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal/less/search.less
  themes/sandal/scss/search.scss
Labels: bugfix

#3500 Rename UserAccountInterface to UserEntityInterface.
  module/VuFind/src/VuFind/Auth/Manager.php
  module/VuFind/src/VuFind/Db/Entity/UserEntityInterface.php
  module/VuFind/src/VuFind/Db/Row/User.php
  module/VuFind/src/VuFind/View/Helper/Root/Auth.php
Labels: improvement

#3485 Introduce UserService to centralize logic.
  module/VuFind/config/module.config.php
  module/VuFind/src/VuFind/Controller/AbstractBase.php
  module/VuFind/src/VuFind/Controller/InstallController.php
  module/VuFind/src/VuFind/Db/Row/User.php
  module/VuFind/src/VuFind/Db/Service/AbstractDbService.php
  module/VuFind/src/VuFind/Db/Service/AbstractDbServiceFactory.php
  module/VuFind/src/VuFind/Db/Service/DbServiceAwareInterface.php
  module/VuFind/src/VuFind/Db/Service/DbServiceAwareTrait.php
  module/VuFind/src/VuFind/Db/Service/PluginManager.php
  module/VuFind/src/VuFind/Db/Service/UserService.php
  module/VuFind/src/VuFind/Db/Service/UserServiceFactory.php
  module/VuFind/src/VuFind/ServiceManager/ServiceInitializer.php
  module/VuFind/src/VuFindTest/Feature/LiveDatabaseTrait.php
  module/VuFind/tests/unit-tests/src/VuFindTest/OAuth2/Repository/IdentityRepositoryTest.php
Labels: architecture

#3508 Add an option to run psql without sudo.
  build.xml
Labels: tooling

#3501 Fix and clean up persistent login.
  config/vufind/config.ini
  module/VuFind/sql/migrations/pgsql/10.0/001-add-login-token-table.sql
  module/VuFind/sql/mysql.sql
  module/VuFind/sql/pgsql.sql
  module/VuFind/src/VuFind/Auth/LoginTokenManager.php
  module/VuFind/src/VuFind/Auth/Manager.php
  module/VuFind/src/VuFind/Db/Table/LoginToken.php
  module/VuFind/src/VuFind/Exception/LoginToken.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/LoginTokenManagerTest.php
Labels: bugfix

#3513 [9.1] Fix conditional filter listener to check the backend id.
  module/VuFind/src/VuFind/Search/Factory/AbstractSolrBackendFactory.php
  module/VuFind/src/VuFind/Search/Solr/InjectConditionalFilterListener.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/Solr/ConditionalFilterListenerTest.php
Labels: bugfix

#3514 Fix login token grouping.
  module/VuFind/src/VuFind/Db/Table/LoginToken.php
Labels: bugfix

#3490 Use Symfony/Console attributes for forward-compatibility.
  module/VuFindConsole/src/VuFindConsole/Command/Compile/ThemeCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Generate/DynamicRouteCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Generate/ExtendClassCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Generate/ExtendServiceCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Generate/NonTabRecordActionCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Generate/PluginCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Generate/RecordRouteCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Generate/StaticRouteCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Generate/ThemeCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Generate/ThemeMixinCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Harvest/HarvestOaiCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Harvest/MergeMarcCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Import/ImportCsvCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Import/ImportXslCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Import/WebCrawlCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Install/InstallCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Language/AddUsingTemplateCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Language/CopyStringCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Language/DeleteCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Language/ImportLokaliseCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Language/NormalizeCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/ScheduledSearch/NotifyCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/AbstractCssBuilderCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/BrowscapCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/CleanUpRecordCacheCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/CommitCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/CreateHierarchyTreesCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/DedupeCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/DeletesCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/ExpireAccessTokensCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/ExpireAuthHashesCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/ExpireExternalSessionsCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/ExpireLoginTokensCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/ExpireSearchesCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/ExpireSessionsCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/IndexReservesCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/LintMarcCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/OptimizeCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/PurgeCachedRecordCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/ScssBuilderCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/SitemapCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/SuppressedCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/SwitchDbHashCommand.php
Labels: improvement, dependencies

#3517 Use ::class instead of hard-coded class strings.
  module/VuFind/src/VuFind/Controller/Plugin/Permission.php
  module/VuFind/src/VuFind/Controller/UpgradeController.php
  module/VuFind/src/VuFind/Search/RecommendListener.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Recommend/SummonResultsTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Recommend/SummonTopicsTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Recommend/WebResultsTest.php
Labels: improvement

#3497 [VUFIND-1547] Standardize event namespace for search backend.
  module/VuFind/src/VuFind/Bootstrapper.php
  module/VuFind/src/VuFind/Search/BackendManager.php
  module/VuFind/src/VuFind/Search/Base/HideFacetValueListener.php
  module/VuFind/src/VuFind/Search/Factory/BlenderBackendFactory.php
  module/VuFind/src/VuFind/Search/Primo/InjectOnCampusListener.php
  module/VuFind/src/VuFind/Search/SearchRunner.php
  module/VuFind/src/VuFind/Search/Solr/AbstractErrorListener.php
  module/VuFind/src/VuFind/Search/Solr/CustomFilterListener.php
  module/VuFind/src/VuFind/Search/Solr/DeduplicationListener.php
  module/VuFind/src/VuFind/Search/Solr/DefaultParametersListener.php
  module/VuFind/src/VuFind/Search/Solr/FilterFieldConversionListener.php
  module/VuFind/src/VuFind/Search/Solr/HierarchicalFacetListener.php
  module/VuFind/src/VuFind/Search/Solr/InjectConditionalFilterListener.php
  module/VuFind/src/VuFind/Search/Solr/InjectHighlightingListener.php
  module/VuFind/src/VuFind/Search/Solr/InjectSpellingListener.php
  module/VuFind/src/VuFind/Search/Solr/MultiIndexListener.php
  module/VuFind/src/VuFindTest/Feature/SearchServiceTrait.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/Base/HideFacetValueListenerTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/Primo/OnCampusListenerTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/Solr/ConditionalFilterListenerTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/Solr/CustomFilterListenerTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/Solr/DefaultParametersListenerTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/Solr/FilterFieldConversionListenerTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/Solr/InjectHighlightingListenerTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/Solr/MultiIndexListenerTest.php
  module/VuFindSearch/src/VuFindSearch/Backend/Blender/Backend.php
  module/VuFindSearch/src/VuFindSearch/Feature/SearchBackendEventManagerTrait.php
  module/VuFindSearch/src/VuFindSearch/Service.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/Blender/BackendTest.php
Labels: architecture

#3510 Upgrade to endroid/qr-code v5.
  composer.json
  composer.lock
  module/VuFind/src/VuFind/QRCode/Loader.php
Labels: dependencies

#3525 Create asset pipeline cache directory on demand.
  module/VuFindTheme/src/VuFindTheme/View/Helper/ConcatTrait.php
Labels: improvement

#3480 Upgrade to Solr 9.5.0.
  build.xml
  import/browse-indexing.jar
  solr/vufind/authority/conf/solrconfig.xml
  solr/vufind/biblio/conf/solrconfig.xml
  solr/vufind/jars/browse-handler.jar
  solr/vufind/reserves/conf/solrconfig.xml
  solr/vufind/website/conf/solrconfig.xml
Labels: dependencies

#3529 [VUFIND-1639] Improve ILS error handling during installation process.
  module/VuFind/src/VuFind/Controller/InstallController.php
Labels: bugfix

#3532 Make custom status handling in NoILS driver more robust.
  module/VuFind/src/VuFind/ILS/Driver/NoILS.php
Labels: improvement

#3511 Upgrade deprecated GitHub Actions tasks.
  .github/workflows/ci.yaml
Labels: tooling

#3527 Upgrade to jQuery 3.7.1.
  themes/bootstrap3/js/vendor/jquery.min.js
  themes/bootstrap3/package.json
  themes/bootstrap3/tools/copyDependencies.mjs
Labels: dependencies

#3526 [VUFIND-1618] Eliminate setlocale() call from Bootstrapper.
  module/VuFind/src/VuFind/Bootstrapper.php
  module/VuFind/src/VuFind/Service/CurrencyFormatter.php
  module/VuFind/src/VuFind/Service/CurrencyFormatterFactory.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Service/CurrencyFormatterTest.php
Labels: architecture

#3521 Use components and icon helper with offcanvas, fix issues.
  module/VuFind/src/VuFind/View/Helper/Root/Config.php
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/components/offcanvas.less
  themes/bootstrap3/less/components/search.less
  themes/bootstrap3/scss/components/offcanvas.scss
  themes/bootstrap3/scss/components/search.scss
  themes/bootstrap3/templates/Recommend/SideFacets.phtml
  themes/bootstrap3/templates/Recommend/SideFacetsDeferred.phtml
  themes/bootstrap3/templates/_ui/components/hide-offcanvas-button.phtml
  themes/bootstrap3/templates/_ui/components/show-account-menu-button.phtml
  themes/bootstrap3/templates/_ui/components/show-search-sidebar-button.phtml
  themes/bootstrap3/templates/_ui/components/show-sidebar-button.phtml
  themes/bootstrap3/templates/checkouts/history.phtml
  themes/bootstrap3/templates/holds/list.phtml
  themes/bootstrap3/templates/myresearch/checkedout.phtml
  themes/bootstrap3/templates/myresearch/edit.phtml
  themes/bootstrap3/templates/myresearch/editlist.phtml
  themes/bootstrap3/templates/myresearch/fines.phtml
  themes/bootstrap3/templates/myresearch/illrequests.phtml
  themes/bootstrap3/templates/myresearch/menu.phtml
  themes/bootstrap3/templates/myresearch/mylist.phtml
  themes/bootstrap3/templates/myresearch/profile.phtml
  themes/bootstrap3/templates/myresearch/schedulesearch.phtml
  themes/bootstrap3/templates/myresearch/storageretrievalrequests.phtml
  themes/bootstrap3/templates/search/history.phtml
  themes/bootstrap3/templates/search/results.phtml
  themes/bootstrap3/theme.config.php
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
Labels: improvement

#3538 Improve CartController redirect validation.
  module/VuFind/src/VuFind/Controller/CartController.php
Labels: improvement

#3361 Convert DOM events to stored functions
  themes/bootstrap3/js/cart.js
  themes/bootstrap3/js/common.js
  themes/bootstrap3/js/cookie.js
  themes/bootstrap3/js/lightbox.js
  themes/bootstrap3/js/search.js
Labels: architecture, small

#3544 Databases & ConsortialVuFind: Fix bug in advanced search
  module/VuFind/src/VuFind/Recommend/ConsortialVuFind.php
  module/VuFind/src/VuFind/Recommend/Databases.php
Labels: bugfix

#3512 Print prompt trigger fixes
  themes/bootstrap3/js/check_item_statuses.js
  themes/bootstrap3/js/check_save_statuses.js
  themes/bootstrap3/js/trigger_print.js
Labels: bugfix
