Repository vufind-org/vufind, pull requests merged in 2024-04, with the labels that each got.

#3549 Fix OAI-PMH server date validation on PHP 8.1.
  module/VuFind/src/VuFind/OAI/Server.php
Labels: bugfix

#3542 Improve table layout and text wrapping on narrow screens.
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/bootstrap.less
  themes/bootstrap3/less/components/search.less
  themes/bootstrap3/scss/bootstrap.scss
  themes/bootstrap3/scss/components/search.scss
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal/less/sandal.less
  themes/sandal/scss/sandal.scss
Labels: improvement

#3545 Add confirm button component
  module/VuFind/src/VuFind/View/Helper/Root/Component.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/LibraryCardsTest.php
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/bootstrap.less
  themes/bootstrap3/less/components/icons.less
  themes/bootstrap3/scss/bootstrap.scss
  themes/bootstrap3/scss/components/icons.scss
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/list-entry.phtml
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/toolbar.phtml
  themes/bootstrap3/templates/_ui/components/confirm-button.phtml
  themes/bootstrap3/templates/cart/cart.phtml
  themes/bootstrap3/templates/channels/channelList.phtml
  themes/bootstrap3/templates/checkouts/history.phtml
  themes/bootstrap3/templates/holds/list.phtml
  themes/bootstrap3/templates/librarycards/home.phtml
  themes/bootstrap3/templates/myresearch/checkedout.phtml
  themes/bootstrap3/templates/myresearch/illrequests.phtml
  themes/bootstrap3/templates/myresearch/mylist.phtml
  themes/bootstrap3/templates/myresearch/storageretrievalrequests.phtml
  themes/bootstrap3/templates/search/filters.phtml
  themes/bootstrap3/templates/search/searchbox.phtml
  themes/local_theme_example/css/compiled.css
  themes/local_theme_example/templates/search/home.phtml
  themes/sandal/css/compiled.css
Labels: architecture

#3551 VUFIND-1669: Change advanced search tips to ul/li
  themes/bootstrap3/templates/search/advanced/layout.phtml
Labels: accessibility

#3554 AccessTokenEntityInterface: Replace setUserId with setUser.
  module/VuFind/config/module.config.php
  module/VuFind/src/VuFind/Db/Entity/AccessTokenEntityInterface.php
  module/VuFind/src/VuFind/Db/Row/AccessToken.php
  module/VuFind/src/VuFind/OAuth2/Repository/AbstractTokenRepository.php
  module/VuFind/src/VuFind/OAuth2/Repository/AccessTokenRepository.php
  module/VuFind/src/VuFind/OAuth2/Repository/AuthCodeRepository.php
  module/VuFind/src/VuFind/OAuth2/Repository/RefreshTokenRepository.php
  module/VuFind/src/VuFind/OAuth2/Repository/RepositoryWithAccessTokenAndUserServicesFactory.php
  module/VuFind/tests/unit-tests/src/VuFindTest/OAuth2/Repository/AbstractTokenRepositoryTestCase.php
  module/VuFind/tests/unit-tests/src/VuFindTest/OAuth2/Repository/AccessTokenRepositoryTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/OAuth2/Repository/AuthCodeRepositoryTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/OAuth2/Repository/RefreshTokenRepositoryTest.php
Labels: architecture

#3560 Fix unwanted hiding of checkboxes on user account pages
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/components/search.less
  themes/bootstrap3/scss/components/search.scss
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
Labels: bugfix

#3515 CSV importer: Inject dependencies into static callback classes.
  module/VuFind/src/VuFind/CSV/Importer.php
  module/VuFind/tests/fixtures/csv/test-injection.ini
  module/VuFind/tests/unit-tests/src/VuFindTest/CSV/ImporterTest.php
Labels: bugfix

#3559 Reflect possible null return from ->current().
  module/VuFind/src/VuFind/Db/Table/AuthHash.php
  module/VuFind/src/VuFind/Db/Table/ChangeTracker.php
  module/VuFind/src/VuFind/Db/Table/ExternalSession.php
  module/VuFind/src/VuFind/Db/Table/OaiResumption.php
  module/VuFind/src/VuFind/Db/Table/Ratings.php
  module/VuFind/src/VuFind/Db/Table/Search.php
  module/VuFind/src/VuFind/Db/Table/User.php
Labels: improvement

#3486 Make user field for oauth subject configurable
  config/vufind/OAuth2Server.yaml
  languages/aliases.ini
  languages/de.ini
  languages/en.ini
  module/VuFind/src/VuFind/Controller/OAuth2Controller.php
  module/VuFind/src/VuFind/Controller/OAuth2ControllerFactory.php
  module/VuFind/src/VuFind/Db/Entity/UserEntityInterface.php
  module/VuFind/src/VuFind/Db/Row/User.php
  module/VuFind/src/VuFind/Db/Service/UserService.php
  module/VuFind/src/VuFind/Db/Service/UserServiceInterface.php
  module/VuFind/src/VuFind/Db/Table/User.php
  module/VuFind/src/VuFind/OAuth2/Entity/UserEntity.php
  module/VuFind/src/VuFind/OAuth2/Repository/AbstractTokenRepository.php
  module/VuFind/src/VuFind/OAuth2/Repository/AccessTokenRepository.php
  module/VuFind/src/VuFind/OAuth2/Repository/AuthCodeRepository.php
  module/VuFind/src/VuFind/OAuth2/Repository/IdentityRepository.php
  module/VuFind/src/VuFind/OAuth2/Repository/RefreshTokenRepository.php
  module/VuFind/src/VuFind/OAuth2/Repository/TokenRepositoryFactory.php
  module/VuFind/tests/unit-tests/src/VuFindTest/OAuth2/Repository/AbstractTokenRepositoryTestCase.php
  module/VuFind/tests/unit-tests/src/VuFindTest/OAuth2/Repository/AccessTokenRepositoryTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/OAuth2/Repository/AuthCodeRepositoryTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/OAuth2/Repository/IdentityRepositoryTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/OAuth2/Repository/RefreshTokenRepositoryTest.php
  themes/bootstrap3/templates/oauth2/authorize.phtml
Labels: new feature

#3572 Fix bug: handler-specific default sorts broken.
  module/VuFind/src/VuFindTest/Integration/MinkTestCase.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchSortTest.php
  themes/bootstrap3/templates/search/searchbox.phtml
Labels: bugfix

#3534 Fix broken combined AJAX DOI functionality.
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/CombinedSearchTest.php
  themes/bootstrap3/js/common.js
Labels: bugfix, tests

#3562 Add menu button support for target and lightbox
  themes/bootstrap3/templates/_ui/components/menu-button.phtml
Labels: improvement

#3579 Update CodeQL workflow configuration.
  .github/codeql/codeql-config.yml
  .github/workflows/codeql.yml
Labels: tooling

#3565 Hide bulk action buttons in mobile sizes.
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/ResponsivenessTest.php
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/components/search.less
  themes/bootstrap3/scss/components/search.scss
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
Labels: bugfix

#3583 fix: turn mobile drop-ups into drop-downs
  themes/bootstrap3/templates/_ui/components/menu-button.phtml
Labels: bugfix

#3566 [VUFIND-1640] Eliminate submit inputs named "submit"
  module/VuFind/src/VuFind/Controller/AbstractBase.php
  module/VuFind/src/VuFind/Controller/AbstractRecord.php
  module/VuFind/src/VuFind/Controller/CartController.php
  module/VuFind/src/VuFind/Controller/FeedbackController.php
  module/VuFind/src/VuFind/Controller/InstallController.php
  module/VuFind/src/VuFind/Controller/LibraryCardsController.php
  module/VuFind/src/VuFind/Controller/MyResearchController.php
  module/VuFind/src/VuFind/Controller/SearchController.php
  module/VuFind/src/VuFind/Controller/UpgradeController.php
  module/VuFind/src/VuFind/Form/Form.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AccountActionsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/BulkTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/CartTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/FavoritesTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Form/FormTest.php
  themes/bootstrap3/js/lightbox.js
  themes/bootstrap3/templates/Auth/Database/recovery.phtml
  themes/bootstrap3/templates/Helpers/email-form-fields.phtml
  themes/bootstrap3/templates/RecordTab/collectionlist.phtml
  themes/bootstrap3/templates/admin/maintenance/home.phtml
  themes/bootstrap3/templates/cart/export-success.phtml
  themes/bootstrap3/templates/cart/export.phtml
  themes/bootstrap3/templates/cart/save.phtml
  themes/bootstrap3/templates/install/fixdatabase.phtml
  themes/bootstrap3/templates/librarycards/editcard.phtml
  themes/bootstrap3/templates/myresearch/account.phtml
  themes/bootstrap3/templates/myresearch/changeemail.phtml
  themes/bootstrap3/templates/myresearch/delete.phtml
  themes/bootstrap3/templates/myresearch/deleteaccount.phtml
  themes/bootstrap3/templates/myresearch/edit.phtml
  themes/bootstrap3/templates/myresearch/editlist.phtml
  themes/bootstrap3/templates/myresearch/newpassword.phtml
  themes/bootstrap3/templates/myresearch/profile.phtml
  themes/bootstrap3/templates/oai/home.phtml
  themes/bootstrap3/templates/primo/advanced.phtml
  themes/bootstrap3/templates/record/addtag.phtml
  themes/bootstrap3/templates/record/rating.phtml
  themes/bootstrap3/templates/record/save.phtml
  themes/bootstrap3/templates/record/sms.phtml
  themes/bootstrap3/templates/search/newitem.phtml
  themes/bootstrap3/templates/search/reserves.phtml
  themes/bootstrap3/templates/upgrade/fixanonymoustags.phtml
  themes/bootstrap3/templates/upgrade/fixduplicatetags.phtml
  themes/bootstrap3/templates/upgrade/fixmetadata.phtml
  themes/bootstrap3/templates/upgrade/getdbcredentials.phtml
Labels: architecture

#3590 Add an option to specify sort order conditions for extra params in searchspecs.
  config/vufind/searchspecs.yaml
  module/VuFindSearch/src/VuFindSearch/Backend/BrowZine/QueryBuilder.php
  module/VuFindSearch/src/VuFindSearch/Backend/EDS/QueryBuilder.php
  module/VuFindSearch/src/VuFindSearch/Backend/EIT/QueryBuilder.php
  module/VuFindSearch/src/VuFindSearch/Backend/LibGuides/QueryBuilder.php
  module/VuFindSearch/src/VuFindSearch/Backend/Pazpar2/QueryBuilder.php
  module/VuFindSearch/src/VuFindSearch/Backend/Primo/QueryBuilder.php
  module/VuFindSearch/src/VuFindSearch/Backend/Solr/Backend.php
  module/VuFindSearch/src/VuFindSearch/Backend/Solr/QueryBuilder.php
  module/VuFindSearch/src/VuFindSearch/Backend/Solr/QueryBuilderInterface.php
  module/VuFindSearch/src/VuFindSearch/Backend/Summon/QueryBuilder.php
  module/VuFindSearch/src/VuFindSearch/Backend/WorldCat/QueryBuilder.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/Solr/QueryBuilderTest.php
Labels: new feature

#3587 Use UserEntityInterface in ExternalAuthController.
  module/VuFind/src/VuFind/Controller/ExternalAuthController.php
Labels: architecture

#3586 Simplify createEmailViewModel; leverage UserEntityInterface.
  module/VuFind/src/VuFind/Controller/AbstractBase.php
Labels: architecture

#3573 Fix visibility of off-canvas toggles.
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/ResponsivenessTest.php
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/components/offcanvas.less
  themes/bootstrap3/scss/components/offcanvas.scss
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
Labels: bugfix

#3596 KohaRest: Fix getDepartments for Koha 23.11+
  module/VuFind/src/VuFind/ILS/Driver/KohaRest.php
Labels: improvement

#3594 Expand use of CommentsService/Interface.
  module/VuFind/src/VuFind/AjaxHandler/DeleteRecordComment.php
  module/VuFind/src/VuFind/AjaxHandler/DeleteRecordCommentFactory.php
  module/VuFind/src/VuFind/Controller/AbstractRecord.php
  module/VuFind/src/VuFind/Db/Row/User.php
  module/VuFind/src/VuFind/Db/Service/CommentsService.php
  module/VuFind/src/VuFind/Db/Service/CommentsServiceInterface.php
  module/VuFind/src/VuFind/Db/Table/Comments.php
  module/VuFind/src/VuFind/RecordDriver/AbstractBase.php
  module/VuFindAdmin/src/VuFindAdmin/Controller/SocialstatsController.php
  module/VuFindAdmin/tests/unit-tests/src/VuFindTest/Controller/SocialstatsControllerTest.php
  themes/bootstrap3/templates/record/comments-list.phtml
Labels: architecture

#3602 Improve HttpRequestTrait for tests.
  module/VuFind/src/VuFindTest/Feature/HttpRequestTrait.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/OAuth2Test.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/ShibbolethLogoutNotificationTest.php
Labels: tests

#3609 VUFIND-1658 - Sandal theme: applied filter contrast is too low on home page
  themes/sandal/css/compiled.css
  themes/sandal/less/search.less
  themes/sandal/scss/search.scss
Labels: bugfix

#3606 VUFIND-1657: Fix cover loader when cache disabled
  module/VuFind/src/VuFind/Captcha/ImageFactory.php
  module/VuFind/src/VuFind/Cover/CachingProxy.php
  module/VuFind/src/VuFind/Cover/CachingProxyFactory.php
  module/VuFind/src/VuFind/Cover/LoaderFactory.php
Labels: bugfix

#3611 Fix CSS variable handling in lessToSass conversion
  Gruntfile.js
  themes/bootstrap3/less/components/cookie-consent/abstracts/light-color-scheme.less
  themes/bootstrap3/less/components/cookie-consent/core/base.less
  themes/bootstrap3/scss/components/cookie-consent/abstracts/light-color-scheme.scss
  themes/bootstrap3/scss/components/cookie-consent/core/base.scss
  themes/sandal/scss/common.scss
Labels: tooling

#3610 Fix Solr highlighting in Blender.
  module/VuFind/src/VuFind/RecordDriver/PluginManager.php
  module/VuFind/src/VuFind/Search/Solr/InjectHighlightingListener.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/Solr/InjectHighlightingListenerTest.php
  module/VuFindSearch/src/VuFindSearch/Backend/Solr/Response/Json/RecordCollectionFactory.php
Labels: bugfix

#3605 Expand use of UserEntityInterface in AJAX handlers
  module/VuFind/src/VuFind/AjaxHandler/AbstractIlsAndUserAction.php
  module/VuFind/src/VuFind/AjaxHandler/AbstractRelaisAction.php
  module/VuFind/src/VuFind/AjaxHandler/CommentRecord.php
  module/VuFind/src/VuFind/AjaxHandler/DeleteRecordComment.php
  module/VuFind/src/VuFind/AjaxHandler/GetRecordTags.php
  module/VuFind/src/VuFind/AjaxHandler/GetSearchResults.php
  module/VuFind/src/VuFind/AjaxHandler/GetUserFines.php
  module/VuFind/src/VuFind/AjaxHandler/RelaisInfo.php
  module/VuFind/src/VuFind/AjaxHandler/RelaisOrder.php
  module/VuFind/tests/unit-tests/src/VuFindTest/AjaxHandler/RelaisAvailabilityTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/AjaxHandler/RelaisInfoTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/AjaxHandler/RelaisOrderTest.php
Labels: architecture

#3612 Fix types in RatingsService::addOrUpdateRating().
  module/VuFind/src/VuFind/Db/Service/RatingsService.php
  module/VuFind/src/VuFind/Db/Service/RatingsServiceInterface.php
Labels: bugfix

#3613 Use UserEntityInterface in feedback forms
  module/VuFind/src/VuFind/Controller/FeedbackController.php
  module/VuFind/src/VuFind/Form/Handler/Database.php
  module/VuFind/src/VuFind/Form/Handler/Email.php
  module/VuFind/src/VuFind/Form/Handler/HandlerInterface.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Form/Handler/DatabaseTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Form/Handler/EmailTest.php
Labels: architecture

#3619 Sierra: Fix volume extraction and callnumber element in holdings.
  module/VuFind/src/VuFind/ILS/Driver/SierraRest.php
Labels: bugfix

#3620 Fix type handling/annotation related to encrypted passwords.
  module/VuFind/src/VuFind/Auth/ILSAuthenticator.php
  module/VuFind/src/VuFind/Db/Row/User.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/ILSAuthenticatorTest.php
Labels: bugfix

#3622 Use UserEntityInterface in profile template (and related code)
  module/VuFind/src/VuFind/Db/Entity/UserEntityInterface.php
  module/VuFind/src/VuFind/Db/Row/User.php
  module/VuFind/src/VuFind/View/Helper/Root/Auth.php
  themes/bootstrap3/templates/librarycards/selectcard.phtml
  themes/bootstrap3/templates/myresearch/profile.phtml
Labels: architecture
