Repository vufind-org/vufind, pull requests merged in 2024-12, with the labels that each got.

#4105 EDS API: Additional Headers to enable EBSCO to assist with BOT protection
  config/vufind/EDS.ini
  module/VuFind/src/VuFind/Search/Factory/EdsBackendFactory.php
  module/VuFindSearch/src/VuFindSearch/Backend/EDS/Base.php
Labels: new feature

#4122 Extra events for lightbox
  themes/bootstrap3/js/lightbox.js
  themes/bootstrap5/js/lightbox.js
Labels: improvement

#4096 Course reserves: minor quality of life improvements
  config/vufind/config.ini
  languages/en.ini
  themes/bootstrap3/templates/search/reservesresults.phtml
  themes/bootstrap3/templates/search/reservessearch.phtml
  themes/bootstrap5/templates/search/reservesresults.phtml
  themes/bootstrap5/templates/search/reservessearch.phtml
Labels: improvement, new language strings

#4128 Fix a timing issue in checkbox facet tests.
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchFacetsTest.php
Labels: bugfix, tests

#4127 Fix timing issue in RecordCoverImageTest.
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/RecordCoverImageTest.php
  themes/bootstrap3/js/covers.js
  themes/bootstrap5/js/covers.js
Labels: bugfix, tests

#4111 Improve selection of a full star in rating.
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/components/record.less
  themes/bootstrap3/scss/components/record.scss
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/scss/components/record.scss
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal5/css/compiled.css
Labels: bugfix

#4113 Simplify LibGuidesProfile config handling and test; fix types.
  module/VuFind/src/VuFind/Recommend/LibGuidesProfile.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Recommend/LibGuidesProfileTest.php
Labels: bugfix, improvement

#4130 Fix sidebar margins and padding on narrow screens
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/components/search.less
  themes/bootstrap3/less/components/sidebar.less
  themes/bootstrap3/scss/components/search.scss
  themes/bootstrap3/scss/components/sidebar.scss
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/scss/components/search.scss
  themes/bootstrap5/scss/components/sidebar.scss
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal/less/sandal.less
  themes/sandal/scss/sandal.scss
  themes/sandal5/css/compiled.css
  themes/sandal5/scss/sandal.scss
Labels: bugfix

#4131 Include dimension data in image test failure message.
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/RecordCoverImageTest.php
Labels: tests

#4135 Remove image test logic
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/RecordCoverImageTest.php
  themes/bootstrap3/js/covers.js
  themes/bootstrap5/js/covers.js
Labels: improvement

#4134 FOLIO: fix missing item ID bug for title-level requests
  module/VuFind/src/VuFind/ILS/Driver/Folio.php
Labels: bugfix

#4136 Reduce warnings from combined-search.js.
  themes/bootstrap3/js/combined-search.js
  themes/bootstrap5/js/combined-search.js
Labels: bugfix

#4137 Display search errors correctly in combined search mode.
  module/VuFind/src/VuFind/Controller/AbstractSearch.php
  module/VuFind/src/VuFind/Controller/CombinedController.php
  themes/bootstrap3/templates/combined/results-list.phtml
  themes/bootstrap5/templates/combined/results-list.phtml
Labels: bugfix

#4138 Remove unused VuFind\Config\Reader\CacheDecorator class.
  module/VuFind/src/VuFind/Config/Reader/CacheDecorator.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Config/Reader/CacheDecoratorTest.php
Labels: architecture

#4139 Remove IniReaderTrait.
  module/VuFind/src/VuFind/Config/Feature/IniReaderTrait.php
  module/VuFind/src/VuFind/Config/PathResolverFactory.php
  module/VuFind/src/VuFind/Config/PluginFactory.php
Labels: architecture

#4141 Update phing and laminas-mvc.
  composer.json
  composer.lock
Labels: dependencies

#4147 Fix actual problem with hiding combined search elements.
  themes/bootstrap3/js/combined-search.js
  themes/bootstrap5/js/combined-search.js
Labels: bugfix

#4145 Remove direct dependency on laminas-config.
  composer.json
  composer.lock
Labels: architecture

#4148 Eliminate laminas-dom dependency.
  composer.json
  composer.lock
  module/VuFind/src/VuFind/Resolver/Driver/Redi.php
Labels: architecture

#4152 Fix bug: lightbox covers interfered with preview links
  themes/bootstrap3/js/preview.js
  themes/bootstrap5/js/preview.js
Labels: bugfix

#4146 Replace Laminas\Loader with Composer autoloading.
  composer.json
  composer.lock
  module/VuFind/Module.php
  module/VuFind/tests/bootstrap.php
  module/VuFindAdmin/Module.php
  module/VuFindApi/Module.php
  module/VuFindConsole/Module.php
  module/VuFindConsole/src/VuFindConsole/Command/Install/InstallCommand.php
  module/VuFindDevTools/Module.php
  module/VuFindLocalTemplate/Module.php
  module/VuFindSearch/Module.php
  module/VuFindTheme/Module.php
Labels: architecture

#4149 Phing: Adjust PostgreSQL database ownership for compatibility with v16
  build.xml
Labels: tooling, tests

#4150 Bug fixes related to favorite list creation.
  themes/bootstrap3/templates/myresearch/editlist.phtml
  themes/bootstrap3/templates/record/save.phtml
  themes/bootstrap5/templates/myresearch/editlist.phtml
  themes/bootstrap5/templates/record/save.phtml
Labels: bugfix

#4155 Fix selected option highlighting in theme menu.
  module/VuFindTheme/src/VuFindTheme/Initializer.php
Labels: bugfix

#4119 Better use of call numbers for similar items
  import/index_java/src/org/vufind/index/CallNumberTools.java
  import/marc.properties
  module/VuFind/tests/fixtures/misc/testbug2.json
  module/VuFindSearch/tests/fixtures/blender/response/solr/search-author.json
  module/VuFindSearch/tests/fixtures/blender/response/solr/search-title.json
  module/VuFindSearch/tests/fixtures/blender/response/solr/search.json
  module/VuFindSearch/tests/fixtures/solr/response/morelikethis
  module/VuFindSearch/tests/fixtures/solr/response/multi-record
  module/VuFindSearch/tests/fixtures/solr/response/multi-record-part1
  module/VuFindSearch/tests/fixtures/solr/response/multi-record-part2
  module/VuFindSearch/tests/fixtures/solr/response/multi-record-part3
  solr/vufind/biblio/conf/schema.xml
Labels: indexing

#4079 RateLimiter: Use Cloudflare Turnstile to detect bots
  config/vufind/RateLimiter.yaml
  config/vufind/contentsecuritypolicy.ini
  module/VuFind/config/module.config.php
  module/VuFind/src/VuFind/Bootstrapper.php
  module/VuFind/src/VuFind/Cache/Manager.php
  module/VuFind/src/VuFind/Controller/TurnstileController.php
  module/VuFind/src/VuFind/Controller/TurnstileControllerFactory.php
  module/VuFind/src/VuFind/RateLimiter/RateLimiterManager.php
  module/VuFind/src/VuFind/RateLimiter/RateLimiterManagerFactory.php
  module/VuFind/src/VuFind/RateLimiter/Turnstile/Turnstile.php
  module/VuFind/src/VuFind/RateLimiter/Turnstile/TurnstileFactory.php
  module/VuFind/tests/unit-tests/src/VuFindTest/RateLimiter/Turnstile/TurnstileTest.php
  themes/bootstrap3/templates/turnstile/challenge.phtml
  themes/bootstrap5/templates/turnstile/challenge.phtml
Labels: new feature

#4157 Add helpful exception message when custom XSLT class is missing.
  module/VuFind/src/VuFind/XSLT/Importer.php
Labels: improvement

#4159 Fix bug with multiple call number message handling
  module/VuFind/src/VuFind/AjaxHandler/GetItemStatuses.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/HoldingsTest.php
Labels: bugfix

#4158 Improve theme initializer
  module/VuFindTheme/src/VuFindTheme/Initializer.php
  module/VuFindTheme/src/VuFindTheme/Mobile.php
  module/VuFindTheme/tests/unit-tests/src/VuFindTest/ThemeMobileTest.php
Labels: architecture

#4095 Improve New Items breadcrumbs/search form.
  themes/bootstrap3/templates/search/newitem.phtml
  themes/bootstrap3/templates/search/newitemresults.phtml
  themes/bootstrap5/templates/search/newitem.phtml
  themes/bootstrap5/templates/search/newitemresults.phtml
Labels: improvement

#4161 [VUFIND-1713] Refactor custom CSRF logic for compatibility with future laminas-validator releases
  composer.json
  composer.lock
  module/VuFind/src/VuFind/Validator/SessionCsrf.php
Labels: dependencies, architecture

#4162 Upgrade MySQL JDBC .jar; raise minimum MySQL requirement to 8.
  import/index_java/src/org/vufind/index/DatabaseManager.java
  import/lib_local/mysql-connector-j-9.1.0.jar
  import/lib_local/mysql-connector-java-5.1.48-bin.jar
Labels: dependencies

#4163 Fix account tooltip with Bootstrap 5.
  themes/bootstrap5/js/account_ajax.js
Labels: bugfix

#4144 Fix lightbox close button on narrow screens.
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/components/lightbox.less
  themes/bootstrap3/scss/components/lightbox.scss
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/scss/bs3-compat.scss
  themes/bootstrap5/scss/components/lightbox.scss
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal5/css/compiled.css
Labels: bugfix

#4065 Remove innerHTML assignments from js
  themes/bootstrap3/js/account_ajax.js
  themes/bootstrap3/js/cart.js
  themes/bootstrap3/js/channels.js
  themes/bootstrap3/js/check_item_statuses.js
  themes/bootstrap3/js/common.js
  themes/bootstrap3/js/hierarchy_tree.js
  themes/bootstrap3/js/list_item_selection.js
  themes/bootstrap3/js/polyfills.js
  themes/bootstrap3/js/record_versions.js
  themes/bootstrap3/js/search.js
  themes/bootstrap3/templates/combined/results-list.phtml
  themes/bootstrap3/theme.config.php
  themes/bootstrap5/js/account_ajax.js
  themes/bootstrap5/js/cart.js
  themes/bootstrap5/js/channels.js
  themes/bootstrap5/js/check_item_statuses.js
  themes/bootstrap5/js/common.js
  themes/bootstrap5/js/hierarchy_tree.js
  themes/bootstrap5/js/list_item_selection.js
  themes/bootstrap5/js/polyfills.js
  themes/bootstrap5/js/record_versions.js
  themes/bootstrap5/js/search.js
  themes/bootstrap5/templates/combined/results-list.phtml
  themes/bootstrap5/theme.config.php
Labels: architecture

#4168 Eliminate references to deprecated TranslatorInterface.
  composer.json
  composer.lock
  module/VuFind/config/module.config.php
  module/VuFind/src/VuFind/I18n/Translator/LanguageInitializerTrait.php
  module/VuFind/src/VuFind/I18n/Translator/TranslatorAwareInterface.php
  module/VuFind/src/VuFind/I18n/Translator/TranslatorAwareTrait.php
  module/VuFind/src/VuFind/I18n/Translator/TranslatorFactory.php
  module/VuFind/src/VuFind/ILS/Driver/Aleph.php
  module/VuFind/src/VuFind/Recommend/AuthorInfo.php
  module/VuFind/src/VuFind/View/Helper/Root/DisplayLanguageOption.php
  module/VuFind/src/VuFindTest/Feature/TranslatorTrait.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/EmailAuthenticatorTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/TranslateTest.php
Labels: architecture

#4166 Fix more button and truncation of top facets in Bootstrap 5 themes.
  themes/bootstrap3/templates/Recommend/TopFacets.phtml
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/scss/bs3-compat.scss
  themes/bootstrap5/templates/Recommend/TopFacets.phtml
  themes/local_theme_example/css/compiled.css
  themes/sandal5/css/compiled.css
Labels: bugfix

#4088 Add detailed status information to the badge for screen readers.
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/js/account_ajax.js
  themes/bootstrap3/less/bootstrap.less
  themes/bootstrap3/scss/bootstrap.scss
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/js/account_ajax.js
  themes/bootstrap5/scss/bootstrap.scss
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal5/css/compiled.css
Labels: accessibility

#4169 Fix bug with lightbox modal failing to close on bootstrap3-based themes.
  themes/bootstrap3/templates/search/facet-list.phtml
Labels: bugfix

#4160 Split OAI server attachNonDeleted function
  module/VuFind/src/VuFind/OAI/Server.php
Labels: architecture

#4173 Fix bug: incorrect theme assignment in console mode.
  module/VuFindTheme/src/VuFindTheme/Initializer.php
Labels: bugfix
