Repository vufind-org/vufind, pull requests merged in 2024-10, with the labels that each got.

#3973 Fix some typos
  module/VuFind/src/VuFind/Cookie/CookieManager.php
  module/VuFind/src/VuFind/DigitalContent/FakeOverdriveConnector.php
  module/VuFind/src/VuFind/DigitalContent/OverdriveConnector.php
  module/VuFind/src/VuFind/ILS/Driver/Aleph.php
  module/VuFind/src/VuFind/ILS/Driver/Alma.php
  module/VuFind/src/VuFind/ILS/Driver/Demo.php
  module/VuFind/src/VuFind/ILS/Driver/Folio.php
  module/VuFind/src/VuFind/ILS/Driver/HorizonXMLAPI.php
  module/VuFind/src/VuFind/ILS/Driver/KohaILSDI.php
  module/VuFind/src/VuFind/ILS/Driver/KohaRest.php
  module/VuFind/src/VuFind/ILS/Driver/PAIA.php
  module/VuFind/src/VuFind/ILS/Driver/Polaris.php
  module/VuFind/src/VuFind/ILS/Driver/SierraRest.php
  module/VuFind/src/VuFind/ILS/Driver/Unicorn.php
  module/VuFind/src/VuFind/ILS/Driver/Virtua.php
  module/VuFind/src/VuFind/ILS/Driver/VoyagerRestful.php
  module/VuFind/src/VuFind/Record/Cache.php
  module/VuFind/src/VuFind/Record/Loader.php
  module/VuFind/src/VuFind/View/Helper/Root/Metadata.php
  module/VuFind/src/VuFind/XSLT/Import/VuFindGeo.php
  module/VuFind/src/VuFindTest/Integration/Session.php
  module/VuFind/tests/fixtures/configs/contentsecuritypolicy/contentsecuritypolicy.ini
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/CartTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchFacetsTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/ILS/Driver/FolioTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordDriver/DefaultRecordTest.php
  module/VuFindSearch/src/VuFindSearch/Backend/EDS/Backend.php
  module/VuFindSearch/src/VuFindSearch/Backend/EDS/Base.php
  module/VuFindSearch/src/VuFindSearch/Backend/Pazpar2/Connector.php
  module/VuFindSearch/src/VuFindSearch/Backend/Primo/Connector.php
  module/VuFindSearch/src/VuFindSearch/Backend/Solr/Response/Json/Spellcheck.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/Solr/QueryBuilderTest.php
  module/VuFindTheme/src/VuFindTheme/View/Helper/ConcatTrait.php
Labels: bugfix, documentation

#3976 Enable Whoops for most integration tests
  config/application.config.php
  module/VuFind/src/VuFindTest/Integration/Session.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/BlendedSearchTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/OAuth2Test.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SavedSearchesTest.php
  themes/bootstrap3/templates/ajax/status-full.phtml
  themes/bootstrap5/templates/ajax/status-full.phtml
Labels: tests

#3557 Fix bug: incorrect author link hidden filter in combined search
  module/VuFind/src/VuFind/Search/Base/Results.php
  module/VuFind/src/VuFind/Search/Memory.php
  module/VuFind/src/VuFind/View/Helper/Root/Record.php
  module/VuFind/src/VuFind/View/Helper/Root/RecordFactory.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/CombinedSearchTest.php
Labels: bugfix

#3980 OIDC: Add option to limit scopes per client
  config/vufind/OAuth2Server.yaml
  module/VuFind/src/VuFind/Controller/OAuth2Controller.php
  module/VuFind/src/VuFind/OAuth2/Repository/ScopeRepository.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/OAuth2Test.php
Labels: improvement

#3975 [dev-11.0] Replace Laminas Mail with Symfony Mailer.
  composer.json
  composer.lock
  config/vufind/config.ini
  module/VuFind/src/VuFind/Form/Handler/Email.php
  module/VuFind/src/VuFind/Log/LoggerFactory.php
  module/VuFind/src/VuFind/Log/Writer/Mail.php
  module/VuFind/src/VuFind/Mailer/Bcc.php
  module/VuFind/src/VuFind/Mailer/Cc.php
  module/VuFind/src/VuFind/Mailer/Factory.php
  module/VuFind/src/VuFind/Mailer/From.php
  module/VuFind/src/VuFind/Mailer/GetFieldValueFixTrait.php
  module/VuFind/src/VuFind/Mailer/Mailer.php
  module/VuFind/src/VuFind/Mailer/Message.php
  module/VuFind/src/VuFind/Mailer/ReplyTo.php
  module/VuFind/src/VuFind/Mailer/To.php
  module/VuFind/src/VuFindTest/Feature/EmailTrait.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AccountActionsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/ChoiceAuthTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/EmailVerificationTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/UrlShortenerTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Mailer/MailerTest.php
Labels: dependencies, architecture

#3984 Use a class for styling fines total balance.
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/bootstrap.less
  themes/bootstrap3/scss/bootstrap.scss
  themes/bootstrap3/templates/myresearch/fines.phtml
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/scss/bootstrap.scss
  themes/bootstrap5/templates/myresearch/fines.phtml
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal5/css/compiled.css
Labels: improvement

#3986 Fix invalid non-breaking space in less and scss files.
  themes/bootstrap3/less/components/record.less
  themes/bootstrap3/scss/components/record.scss
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/scss/components/record.scss
  themes/sandal5/css/compiled.css
Labels: bugfix

#3988 Update translations for 10.1 release - Croatian
  languages/HoldingStatus/hr.ini
  languages/ILSMessages/hr.ini
  languages/ISO639-3/hr.ini
  languages/WorldCatFormats/hr.ini
  languages/hr.ini
Labels: i18n

#3989 Updated translations for 10.1 release - Ukrainian
  languages/ISO639-3/uk.ini
  languages/WorldCatFormats/uk.ini
  languages/uk.ini
Labels: i18n

#3993 Phing: Add parameters for more generic BS5 conversion.
  build.xml
Labels: tooling

#3992 Handle empty cat_password columns in user row
  module/VuFind/src/VuFind/Db/Row/User.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SsoTest.php
Labels: bugfix

#3974 Check for null href in Headlink::itemToString function
  module/VuFindTheme/src/VuFindTheme/View/Helper/HeadLink.php
Labels: bugfix

#3994 Update translations for 10.1 release - German
  languages/HoldingStatus/de.ini
  languages/ILSMessages/de.ini
  languages/WorldCatFormats/de.ini
  languages/de.ini
Labels: i18n

#3941 Moving JS cookie logic into cookie.js and applying it to the keyboard cookie
  module/VuFind/src/VuFind/Cart.php
  module/VuFind/src/VuFind/View/Helper/Root/CookieManager.php
  module/VuFind/src/VuFind/View/Helper/Root/CookieManagerFactory.php
  module/VuFind/tests/unit-tests/src/VuFindTest/CartTest.php
  themes/bootstrap3/js/cart.js
  themes/bootstrap3/js/cookie.js
  themes/bootstrap3/js/searchbox_controls.js
  themes/bootstrap3/templates/Helpers/cookie-consent.phtml
  themes/bootstrap3/templates/layout/layout.phtml
  themes/bootstrap3/theme.config.php
  themes/bootstrap5/js/cart.js
  themes/bootstrap5/js/cookie.js
  themes/bootstrap5/js/searchbox_controls.js
  themes/bootstrap5/templates/Helpers/cookie-consent.phtml
  themes/bootstrap5/templates/layout/layout.phtml
  themes/bootstrap5/theme.config.php
  themes/root/theme.config.php
Labels: bugfix, architecture

#3995 [VUFIND-1702] Switch default theme to sandal5.
  build.xml
  config/vufind/config.ini
Labels: improvement

#3954 Improved RIS export
  module/VuFind/src/VuFind/RecordDriver/DefaultRecord.php
  module/VuFind/src/VuFind/RecordDriver/EDS.php
  module/VuFind/src/VuFind/RecordDriver/Feature/MarcAdvancedTrait.php
  module/VuFind/tests/fixtures/marc/marctraits.xml
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordDriver/EDSTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordDriver/Feature/MarcAdvancedTraitTest.php
  themes/root/templates/RecordDriver/AbstractBase/export-ris.phtml
Labels: improvement

#4000 Add abstract field to record page display
  module/VuFind/src/VuFind/View/Helper/Root/RecordDataFormatterFactory.php
Labels: improvement

#4002 Add additional 520 fields to record description tab
  languages/en.ini
  languages/fr.ini
  module/VuFind/src/VuFind/RecordDriver/Feature/MarcAdvancedTrait.php
  module/VuFind/src/VuFind/View/Helper/Root/RecordDataFormatterFactory.php
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordDriver/Feature/MarcAdvancedTraitTest.php
Labels: improvement, new language strings

#4005 Update Northern Sami translations.
  languages/KeyboardLayout/se.ini
  languages/se.ini
Labels: i18n

#3546 Improve accessibility of cover images
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/cover.phtml
  themes/bootstrap3/templates/RecordDriver/EDS/cover.phtml
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/cover.phtml
  themes/bootstrap5/templates/RecordDriver/EDS/cover.phtml
Labels: accessibility

#4001 Add option to set alignment in confirm-button component
  themes/bootstrap3/templates/_ui/components/confirm-button.phtml
  themes/bootstrap5/templates/_ui/components/confirm-button.phtml
Labels: improvement

#4007 Language dev tool: ignore aliases.ini.
  module/VuFindDevTools/src/VuFindDevTools/LanguageHelper.php
  module/VuFindDevTools/tests/unit-tests/src/VuFindTest/Controller/DevtoolsControllerTest.php
Labels: bugfix, tooling

#3922 Using dir locations stack for language inheritance
  build.xml
  module/VuFind/src/VuFind/Config/PathResolver.php
  module/VuFind/src/VuFind/Config/PathResolverFactory.php
  module/VuFind/src/VuFind/I18n/Translator/LanguageInitializerTrait.php
  module/VuFind/src/VuFind/I18n/Translator/Loader/ExtendedIniFactory.php
  module/VuFind/src/VuFind/I18n/Translator/TranslatorFactory.php
  module/VuFind/src/VuFindTest/Integration/MinkTestCase.php
  module/VuFind/tests/fixtures/dirlocations/DirLocations.ini
  module/VuFind/tests/fixtures/dirlocations/cache/.gitignore
  module/VuFind/tests/fixtures/dirlocations/languages/ParentDomain/en.ini
  module/VuFind/tests/fixtures/dirlocations/languages/en.ini
  module/VuFind/tests/fixtures/dirlocations/test_subdir/AccountMenu.yaml
  module/VuFind/tests/fixtures/dirlocations/test_subdir/searches.ini
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/DirLocationsTest.php
  module/VuFindConsole/src/VuFindConsole/Command/ScheduledSearch/NotifyCommandFactory.php
  module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/ScheduledSearch/NotifyCommandTest.php
Labels: improvement

#4010 Force page refresh with GET request after modifying holds
  module/VuFind/src/VuFind/Controller/AbstractBase.php
  module/VuFind/src/VuFind/Controller/HoldsController.php
  themes/bootstrap3/js/common.js
  themes/bootstrap3/js/lightbox.js
  themes/bootstrap5/js/common.js
  themes/bootstrap5/js/lightbox.js
Labels: bugfix

#3979 [dev-11.0] Make it possible to hide site email address
  config/vufind/config.ini
  languages/en.ini
  languages/fi.ini
  languages/sv.ini
  module/VuFind/src/VuFind/Auth/EmailAuthenticator.php
  module/VuFind/src/VuFind/Auth/LoginTokenManager.php
  module/VuFind/src/VuFind/Config/Feature/EmailSettingsTrait.php
  module/VuFind/src/VuFind/Controller/AbstractBase.php
  module/VuFind/src/VuFind/Controller/AlmaController.php
  module/VuFind/src/VuFind/Controller/MyResearchController.php
  module/VuFind/src/VuFind/Log/LoggerFactory.php
  module/VuFind/src/VuFind/View/Helper/Root/SystemEmailFactory.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/EmailAuthenticationTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/ErrorHandlingTest.php
  module/VuFindConsole/src/VuFindConsole/Command/ScheduledSearch/NotifyCommand.php
  themes/bootstrap3/templates/Helpers/ils-offline.phtml
  themes/bootstrap3/templates/error/contact.phtml
  themes/bootstrap3/templates/error/index.phtml
  themes/bootstrap3/templates/error/permissiondenied.phtml
  themes/bootstrap3/templates/error/unavailable.phtml
  themes/bootstrap5/templates/Helpers/ils-offline.phtml
  themes/bootstrap5/templates/error/contact.phtml
  themes/bootstrap5/templates/error/index.phtml
  themes/bootstrap5/templates/error/permissiondenied.phtml
  themes/bootstrap5/templates/error/unavailable.phtml
  themes/root/templates/Email/notify-email-change.phtml
Labels: improvement, new language strings

#4016 Update translations for 10.1 release - Italian
  languages/HoldingStatus/it.ini
  languages/ILSMessages/it.ini
  languages/ISO639-3/it.ini
  languages/WorldCatFormats/it.ini
  languages/it.ini
Labels: i18n

#3960 Fix bulk favorites save from search results
  module/VuFind/src/VuFind/Controller/AbstractRecord.php
  module/VuFind/src/VuFind/Controller/CartController.php
  module/VuFind/src/VuFind/Controller/MyResearchController.php
  themes/bootstrap3/templates/cart/form-record-hidden-inputs.phtml
  themes/bootstrap3/templates/cart/save.phtml
  themes/bootstrap3/templates/myresearch/editlist.phtml
  themes/bootstrap3/templates/record/save.phtml
  themes/bootstrap5/templates/cart/form-record-hidden-inputs.phtml
  themes/bootstrap5/templates/cart/save.phtml
  themes/bootstrap5/templates/myresearch/editlist.phtml
  themes/bootstrap5/templates/record/save.phtml
Labels: bugfix, small

#3877 Minor OverDrive bug fixes.
  module/VuFind/src/VuFind/DigitalContent/OverdriveConnector.php
  module/VuFind/src/VuFind/RecordDriver/SolrOverdrive.php
  themes/bootstrap3/js/check_item_statuses.js
  themes/bootstrap3/templates/RecordDriver/SolrOverdrive/previewlink.phtml
  themes/bootstrap3/templates/RecordDriver/SolrOverdrive/status-full.phtml
  themes/bootstrap3/templates/RecordTab/overdriveholdings.phtml
  themes/bootstrap5/js/check_item_statuses.js
  themes/bootstrap5/templates/RecordDriver/SolrOverdrive/previewlink.phtml
  themes/bootstrap5/templates/RecordDriver/SolrOverdrive/status-full.phtml
  themes/bootstrap5/templates/RecordTab/overdriveholdings.phtml
Labels: bugfix

#4017 Update translations for 10.1 release - Ukrainian - second PR
  languages/HoldingStatus/uk.ini
  languages/ILSMessages/uk.ini
  languages/ISO639-3/uk.ini
  languages/WorldCatFormats/uk.ini
Labels: i18n

#4012 Create element id which also works as a jQuery selector
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/list-entry.phtml
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/list-entry.phtml
Labels: bugfix

#3930 FOLIO: Support delivery fulfillment preference for requests
  config/vufind/Folio.ini
  module/VuFind/src/VuFind/ILS/Driver/Folio.php
  module/VuFind/tests/fixtures/folio/responses/successful-patron-login-with-okapi-legacy.json
  module/VuFind/tests/fixtures/folio/responses/successful-patron-login-with-okapi.json
  module/VuFind/tests/unit-tests/src/VuFindTest/ILS/Driver/FolioTest.php
  themes/bootstrap3/js/hold.js
  themes/bootstrap3/templates/record/hold.phtml
  themes/bootstrap5/js/hold.js
  themes/bootstrap5/templates/record/hold.phtml
Labels: new feature

#4018 Fix resending of email change confirmation request.
  module/VuFind/src/VuFind/Controller/MyResearchController.php
Labels: bugfix

#4019 Dev tools dependency updates 20241018
  composer.json
  composer.lock
Labels: dependencies

#4020 Support for LaserDisc in MARC import
  import/index_java/src/org/vufind/index/FormatCalculator.java
  import/translation_maps/format_map.properties
  languages/en.ini
Labels: improvement

#4022 Center virtual keyboard on screen
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/components/keyboard.less
  themes/bootstrap3/scss/components/keyboard.scss
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/scss/components/keyboard.scss
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal5/css/compiled.css
Labels: improvement

#4011 VUFIND-1710 Add configurable separators for topics in alphabrowse
  config/vufind/config.ini
  import/browse-indexing.jar
  import/index_java/src/org/vufind/index/FieldSpecTools.java
  import/marc.properties
  index-alphabetic-browse.bat
  index-alphabetic-browse.sh
  module/VuFind/src/VuFind/Controller/AlphabrowseController.php
  module/VuFind/src/VuFind/View/Helper/Root/AlphaBrowse.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/AlphaBrowseTest.php
  solr/vufind/biblio/conf/schema.xml
  solr/vufind/jars/browse-handler.jar
Labels: improvement

#4025 Use ramsey/uuid for UUID generation.
  composer.json
  composer.lock
  module/VuFindSearch/src/VuFindSearch/Backend/AbstractBackend.php
Labels: improvement

#4028 Add key files to .gitignore
  .gitignore
Labels: tooling

#3996 FOLIO: Extract delivery fulfillment config and translations from #3930
  config/vufind/Folio.ini
  languages/en.ini
Labels: new language strings

#4003 [VUFIND-1698] FOLIO: use allowed-service-points API.
  config/vufind/Folio.ini
  module/VuFind/src/VuFind/ILS/Driver/Folio.php
  module/VuFind/tests/fixtures/folio/responses/request-type-fallback.json
  module/VuFind/tests/fixtures/folio/responses/successful-place-hold-legacy.json
  module/VuFind/tests/fixtures/folio/responses/successful-place-hold-no-expiration-date.json
  module/VuFind/tests/fixtures/folio/responses/successful-place-hold.json
  module/VuFind/tests/fixtures/folio/responses/unsuccessful-place-hold.json
  module/VuFind/tests/unit-tests/src/VuFindTest/ILS/Driver/FolioTest.php
Labels: improvement

#4030 Updated translations for 10.1 release - Hindi
  languages/HoldingStatus/hi.ini
  languages/ILSMessages/hi.ini
  languages/WorldCatFormats/hi.ini
  languages/hi.ini
Labels: i18n

#4035 Updated translations for 10.1 release - Catalan
  languages/HoldingStatus/ca.ini
  languages/ILSMessages/ca.ini
  languages/ISO639-3/ca.ini
  languages/WorldCatFormats/ca.ini
  languages/ca.ini
Labels: i18n

#4008 [VUFIND-1660] FOLIO: add pagination/sorting support to getMyTransactions
  config/vufind/Folio.ini
  module/VuFind/src/VuFind/ILS/Driver/Folio.php
Labels: improvement

#4029 Remove obsolete patching logic from build.xml.
  build.xml
  composer.json
Labels: tooling

#4036 Update translations for 10.1 release - Greek
  languages/HoldingStatus/el.ini
  languages/ILSMessages/el.ini
  languages/ServiceType/el.ini
  languages/WorldCatFormats/el.ini
  languages/el.ini
Labels: i18n

#4033 fix: search controls no longer wrap for an improved mobile experience.
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/components/search.less
  themes/bootstrap3/scss/components/search.scss
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/scss/components/search.scss
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal5/css/compiled.css
Labels: improvement

#3761 Facets allow for multiple selections to be made before reloading page
  config/vufind/Blender.ini
  config/vufind/Collection.ini
  config/vufind/EDS.ini
  config/vufind/EPF.ini
  config/vufind/Primo.ini
  config/vufind/Search2.ini
  config/vufind/Summon.ini
  config/vufind/facets.ini
  config/vufind/website.ini
  module/VuFind/src/VuFind/Controller/AbstractSearch.php
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/js/facets.js
  themes/bootstrap3/less/components/sidebar.less
  themes/bootstrap3/scss/components/sidebar.scss
  themes/bootstrap3/templates/Recommend/SideFacets.phtml
  themes/bootstrap3/templates/Recommend/SideFacets/checkbox-filters.phtml
  themes/bootstrap3/templates/Recommend/SideFacets/multiFacetsSelection.phtml
  themes/bootstrap3/templates/Recommend/SideFacets/single-facet.phtml
  themes/bootstrap3/templates/Recommend/SideFacetsDeferred.phtml
  themes/bootstrap3/templates/search/results.phtml
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/js/facets.js
  themes/bootstrap5/scss/components/sidebar.scss
  themes/bootstrap5/templates/Recommend/SideFacets.phtml
  themes/bootstrap5/templates/Recommend/SideFacets/checkbox-filters.phtml
  themes/bootstrap5/templates/Recommend/SideFacets/multiFacetsSelection.phtml
  themes/bootstrap5/templates/Recommend/SideFacets/single-facet.phtml
  themes/bootstrap5/templates/Recommend/SideFacetsDeferred.phtml
  themes/bootstrap5/templates/search/results.phtml
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal5/css/compiled.css
Labels: new feature, new language strings

#3990 Modify Solr suggestions search to handle wonky case with stemming and wildcards
  module/VuFind/src/VuFind/Autocomplete/Solr.php
  module/VuFind/src/VuFind/Autocomplete/SolrCN.php
Labels: improvement

#3937 Add jsdoc-eslint plugin
  .eslintrc.jsdoc.js
  build.xml
  package.json
  themes/bootstrap3/js/observer_manager.js
  themes/bootstrap5/js/observer_manager.js
Labels: tooling, documentation

#4043 Fix: Record print button prints open tab
  themes/bootstrap3/js/record.js
  themes/bootstrap5/js/record.js
Labels: bugfix

#4041 fix: use flex to make the search tool selects line up.
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/components/search.less
  themes/bootstrap3/scss/components/search.scss
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/scss/components/search.scss
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal5/css/compiled.css
Labels: improvement

#4039 Modernize some record tests.
  module/VuFind/tests/unit-tests/src/VuFindTest/Record/CacheTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Record/LoaderTest.php
Labels: tests

#4044 Eliminate use of \Laminas\Crypt\Hash.
  module/VuFind/src/VuFind/Controller/ExternalAuthController.php
Labels: dependencies

#4045 Fix prepend in getCurrentHiddenFilterParams.
  module/VuFind/src/VuFind/View/Helper/Root/SearchTabs.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/SearchTabsTest.php
Labels: bugfix

#4047 Include user when fetching saved search for hidden filters.
  module/VuFind/src/VuFind/Search/Memory.php
  module/VuFind/src/VuFind/View/Helper/Root/Record.php
Labels: bugfix

#4048 Fix issue where versions link does not shift focus to the tab.
  themes/bootstrap3/js/record.js
  themes/bootstrap5/js/record.js
Labels: accessibility

#4046 Update Swedish, Finnish and English translations
  languages/en.ini
  languages/fi.ini
  languages/sv.ini
Labels: i18n
