Repository vufind-org/vufind, pull requests merged in 2024-07, with the labels that each got.

#3821 [VUFIND-1582] Add ChannelProvider for Solr-based new items
  config/vufind/channels.ini
  module/VuFind/src/VuFind/ChannelProvider/NewSearchItems.php
  module/VuFind/src/VuFind/ChannelProvider/NewSearchItemsFactory.php
  module/VuFind/src/VuFind/ChannelProvider/PluginManager.php
  module/VuFind/tests/unit-tests/src/VuFindTest/ChannelProvider/NewSearchItemsTest.php
Labels: new feature

#3824 Better integrate RelativePathTrait and ConcatTrait.
  module/VuFindTheme/src/VuFindTheme/View/Helper/HeadLink.php
  module/VuFindTheme/src/VuFindTheme/View/Helper/HeadScript.php
Labels: bugfix

#3825 EPF: Fix electronic ISSNs and ISBNs
  module/VuFind/src/VuFind/RecordDriver/EPF.php
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordDriver/EPFTest.php
Labels: bugfix

#3822 EDS and EPF: Use orFacets setting for API
  config/vufind/EDS.ini
  module/VuFind/src/VuFind/Controller/EdsController.php
  module/VuFind/src/VuFind/Search/EDS/AbstractEDSParams.php
  module/VuFind/src/VuFind/Search/EDS/Params.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/Blender/ParamsTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/EDS/SearchRequestModelTest.php
  module/VuFindSearch/src/VuFindSearch/Backend/EDS/SearchRequestModel.php
  themes/bootstrap3/templates/search/advanced/eds.phtml
  themes/bootstrap5/templates/search/advanced/eds.phtml
Labels: bugfix, improvement

#3831 results-tools.phtml: Add rel="nofollow" to multiple links
  themes/bootstrap3/templates/search/controls/results-tools.phtml
  themes/bootstrap5/templates/search/controls/results-tools.phtml
Labels: improvement

#3830 Update getHighlightedSnippet to return first non-empty snippet
  module/VuFind/src/VuFind/RecordDriver/SolrDefault.php
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordDriver/SolrDefaultTest.php
Labels: improvement, tests

#3837 Adding record-tab-init event
  themes/bootstrap3/js/embedded_record.js
  themes/bootstrap3/js/record.js
  themes/bootstrap5/js/embedded_record.js
  themes/bootstrap5/js/record.js
Labels: improvement

#3845 SearchMemory: refactor to add getLastSearchUrl method
  module/VuFind/src/VuFind/View/Helper/Root/SearchMemory.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/SearchMemoryTest.php
Labels: improvement

#3832 Fix bug: passing isn=0 to cover loader caused error.
  module/VuFind/src/VuFind/Controller/CoverController.php
Labels: bugfix

#3846 [VUFIND-1681] Add visible heading on cart confirmation menus.
  languages/ar.ini
  languages/bn.ini
  languages/ca.ini
  languages/cs.ini
  languages/cy.ini
  languages/da.ini
  languages/de.ini
  languages/el.ini
  languages/en.ini
  languages/es.ini
  languages/eu.ini
  languages/fi.ini
  languages/fr.ini
  languages/ga.ini
  languages/gl.ini
  languages/he.ini
  languages/hi.ini
  languages/hr.ini
  languages/hy.ini
  languages/it.ini
  languages/ja.ini
  languages/mi.ini
  languages/mn.ini
  languages/nl.ini
  languages/pl.ini
  languages/pt-br.ini
  languages/pt.ini
  languages/ru.ini
  languages/se.ini
  languages/sl.ini
  languages/sv.ini
  languages/tr.ini
  languages/uk.ini
  languages/vi.ini
  languages/zh-cn.ini
  languages/zh.ini
  themes/bootstrap3/templates/cart/cart.phtml
  themes/bootstrap3/templates/layout/js-translations.phtml
  themes/bootstrap5/templates/cart/cart.phtml
  themes/bootstrap5/templates/layout/js-translations.phtml
Labels: improvement
