Repository vufind-org/vufind, pull requests merged in 2024-05, with the labels that each got.

#3025 Add new Overdrive features
  config/vufind/Overdrive.ini
  config/vufind/RecordTabs.ini
  languages/ar.ini
  languages/ca.ini
  languages/cs.ini
  languages/cy.ini
  languages/de.ini
  languages/el.ini
  languages/en.ini
  languages/es.ini
  languages/fi.ini
  languages/fr.ini
  languages/ga.ini
  languages/hr.ini
  languages/hy.ini
  languages/it.ini
  languages/ja.ini
  languages/mn.ini
  languages/nl.ini
  languages/pl.ini
  languages/pt-br.ini
  languages/ru.ini
  languages/se.ini
  languages/sv.ini
  languages/tr.ini
  languages/uk.ini
  languages/vi.ini
  module/VuFind/src/VuFind/Controller/OverdriveController.php
  module/VuFind/src/VuFind/DigitalContent/FakeOverdriveConnector.php
  module/VuFind/src/VuFind/DigitalContent/OverdriveConnector.php
  module/VuFind/src/VuFind/RecordDriver/SolrOverdrive.php
  module/VuFind/src/VuFind/RecordTab/OverdriveHoldings.php
  module/VuFind/src/VuFind/RecordTab/PluginManager.php
  module/VuFind/src/VuFind/View/Helper/Root/Overdrive.php
  themes/bootstrap3/less/bootstrap.less
  themes/bootstrap3/scss/bootstrap.scss
  themes/bootstrap3/templates/RecordDriver/SolrOverdrive/core.phtml
  themes/bootstrap3/templates/RecordDriver/SolrOverdrive/hold.phtml
  themes/bootstrap3/templates/RecordDriver/SolrOverdrive/previewlink.phtml
  themes/bootstrap3/templates/RecordDriver/SolrOverdrive/result-list.phtml
  themes/bootstrap3/templates/RecordDriver/SolrOverdrive/status-full.phtml
  themes/bootstrap3/templates/RecordTab/overdriveholdings.phtml
  themes/bootstrap3/templates/admin/menu.phtml
  themes/bootstrap3/templates/admin/overdrive/home.phtml
  themes/bootstrap3/templates/myresearch/odmycontent.phtml
  themes/bootstrap3/theme.config.php
  themes/root/images/OverDrive_Logo_28x28_rgb.jpg
Labels: new feature

#3631 Use UserEntityInterface/UserService in LoginTokenManager.
  module/VuFind/src/VuFind/Auth/LoginTokenManager.php
  module/VuFind/src/VuFind/Auth/LoginTokenManagerFactory.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/LoginTokenManagerTest.php
Labels: architecture

#3632 Use DbTableAwareTrait in UserService.
  module/VuFind/src/VuFind/Db/Service/PluginManager.php
  module/VuFind/src/VuFind/Db/Service/UserService.php
  module/VuFind/src/VuFind/Db/Service/UserServiceFactory.php
Labels: architecture

#3633 Fix bug: tag links not displaying in favorites.
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/FavoritesTest.php
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/list-entry.phtml
Labels: bugfix

#3584 Add result-scripts event to apply Javascript to search results
  themes/bootstrap3/js/cart.js
  themes/bootstrap3/js/check_item_statuses.js
  themes/bootstrap3/js/check_save_statuses.js
  themes/bootstrap3/js/common.js
  themes/bootstrap3/js/doi.js
  themes/bootstrap3/js/embedded_record.js
  themes/bootstrap3/js/explain.js
  themes/bootstrap3/js/lightbox.js
  themes/bootstrap3/js/openurl.js
  themes/bootstrap3/js/record_versions.js
Labels: architecture

#3640 Accessibility: use heading on query and spelling suggestions.
  module/VuFind/src/VuFind/View/Helper/AbstractSearch.php
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/components/search.less
  themes/bootstrap3/scss/components/search.scss
  themes/bootstrap3/templates/Recommend/SwitchQuery.phtml
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
Labels: accessibility

#3627 Remove mobile top margin from media-body
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/components/record.less
  themes/bootstrap3/scss/components/record.scss
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
Labels: bugfix

#3643 EPF: Add embargo description to record page
  themes/bootstrap3/templates/RecordDriver/EPF/core.phtml
Labels: improvement

#3645 Use list items for spelling suggestions
  module/VuFind/src/VuFind/View/Helper/AbstractSearch.php
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/components/search.less
  themes/bootstrap3/scss/components/search.scss
  themes/bootstrap3/templates/Recommend/SwitchQuery.phtml
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
Labels: improvement

#3494 Remove redundant language codes; use aliases.
  languages/ISO639-3/aliases.ini
  languages/ISO639-3/de.ini
  languages/ISO639-3/en.ini
  languages/ISO639-3/es.ini
  languages/ISO639-3/fi.ini
  languages/ISO639-3/fr.ini
  languages/ISO639-3/gl.ini
  languages/ISO639-3/pt.ini
  languages/ISO639-3/ru.ini
  languages/ISO639-3/se.ini
  languages/ISO639-3/sv.ini
Labels: bugfix

#3576 Aleph driver: improve ID and date processing.
  module/VuFind/src/VuFind/ILS/Driver/Aleph.php
Labels: bugfix

#3648 Make tag display test more flexible.
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/FavoritesTest.php
Labels: bugfix, tests

#3649 Fix bug: popover broke when clicking same record in different channels.
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/ChannelsTest.php
  themes/bootstrap3/js/channels.js
  themes/bootstrap3/templates/channels/channelList.phtml
Labels: bugfix

#3654 [VUFIND-1688] Fix sandal .btn-info colors.
  themes/sandal/css/compiled.css
  themes/sandal/less/common.less
  themes/sandal/scss/common.scss
Labels: bugfix

#3639 Modernize database access in Bootstrapper::initUserLanguage()
  module/VuFind/src/VuFind/Bootstrapper.php
  module/VuFind/src/VuFind/Db/Entity/UserEntityInterface.php
  module/VuFind/src/VuFind/Db/Row/User.php
Labels: architecture

#3657 Default required-string User getters to blank strings if unset.
  module/VuFind/src/VuFind/Db/Row/User.php
Labels: bugfix

#3659 Fix missing alt attributes
  themes/bootstrap3/templates/Recommend/EuropeanaResults.phtml
  themes/bootstrap3/templates/RecordDriver/EDS/core.phtml
  themes/bootstrap3/templates/RecordDriver/EDS/result-list.phtml
  themes/bootstrap3/templates/RecordDriver/SolrOverdrive/hold.phtml
  themes/bootstrap3/templates/RecordTab/overdriveholdings.phtml
  themes/bootstrap3/templates/myresearch/odmycontent.phtml
Labels: accessibility

#3571 Updated bulkFormHandler from jQuery to vanilla Javascript
  themes/bootstrap3/js/common.js
Labels: architecture

#3598 Add JsConfigs view helper for sharing configs with Javascript code
  module/VuFind/src/VuFind/View/Helper/Root/JsConfigs.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/JsTranslationsTest.php
  themes/bootstrap3/js/config.js
  themes/bootstrap3/templates/layout/js-configs.phtml
  themes/bootstrap3/templates/layout/layout.phtml
  themes/bootstrap3/theme.config.php
  themes/root/theme.config.php
Labels: new feature

#3662 [release-9.1] Fix and improve popovers in channels.
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/ChannelsTest.php
  themes/bootstrap3/js/channels.js
Labels: bugfix

#3617 VuFindTheme: Do not search for URLs/absolute paths inside themes.
  module/VuFindTheme/src/VuFindTheme/View/Helper/HeadLink.php
  module/VuFindTheme/src/VuFindTheme/View/Helper/HeadScript.php
  module/VuFindTheme/src/VuFindTheme/View/Helper/ImageLink.php
  module/VuFindTheme/src/VuFindTheme/View/Helper/RelativePathTrait.php
Labels: improvement

#3624 Establish UserResourceService; modernize SocialstatsController.
  module/VuFind/src/VuFind/Db/Service/PluginManager.php
  module/VuFind/src/VuFind/Db/Service/UserResourceService.php
  module/VuFind/src/VuFind/Db/Service/UserResourceServiceInterface.php
  module/VuFindAdmin/src/VuFindAdmin/Controller/SocialstatsController.php
  module/VuFindAdmin/tests/unit-tests/src/VuFindTest/Controller/SocialstatsControllerTest.php
Labels: architecture

#3638 Expand use of UserEntityInterface in console commands
  module/VuFind/src/VuFind/Db/Entity/UserEntityInterface.php
  module/VuFind/src/VuFind/Db/Row/Search.php
  module/VuFind/src/VuFind/Db/Row/User.php
  module/VuFindConsole/src/VuFindConsole/Command/ScheduledSearch/NotifyCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/SwitchDbHashCommand.php
  module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/ScheduledSearch/NotifyCommandTest.php
  module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Util/SwitchDbHashCommandTest.php
Labels: architecture

#3663 updated setupOffcanvas from jQuery to vanilla javascript
  themes/bootstrap3/js/common.js
Labels: improvement

#3637 Add support for rate limiting.
  composer.json
  composer.lock
  config/vufind/RateLimiter.yaml
  languages/en.ini
  languages/fi.ini
  languages/sv.ini
  module/VuFind/config/module.config.php
  module/VuFind/src/VuFind/Bootstrapper.php
  module/VuFind/src/VuFind/RateLimiter/RateLimiterManager.php
  module/VuFind/src/VuFind/RateLimiter/RateLimiterManagerFactory.php
  module/VuFind/src/VuFind/RateLimiter/Storage/CredisStorage.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/RateLimiterTest.php
  themes/bootstrap3/js/search.js
Labels: new feature, new language strings

#3641 Add Change Tracker information to Sitemap
  config/vufind/sitemap.ini
  module/VuFind/src/VuFind/Sitemap/Plugin/Index.php
  module/VuFind/src/VuFind/Sitemap/Plugin/Index/CursorMarkIdFetcher.php
  module/VuFind/src/VuFind/Sitemap/Sitemap.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Sitemap/Plugin/Index/CursorMarkIdFetcherTest.php
  module/VuFindSearch/src/VuFindSearch/Backend/Solr/Backend.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/Solr/BackendTest.php
Labels: improvement

#3668 Login Tokens: removed unused user ID parameter from deleteToken methods.
  module/VuFind/src/VuFind/Auth/LoginTokenManager.php
  module/VuFind/src/VuFind/Auth/Manager.php
  module/VuFind/src/VuFind/Controller/MyResearchController.php
Labels: improvement

#3670 fix: toolbar btns out of alignment.
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/components/search.less
  themes/bootstrap3/scss/components/search.scss
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
Labels: bugfix

#3650 Expand Feedback entity interface; add Feedback service
  module/VuFind/src/VuFind/Db/Entity/FeedbackEntityInterface.php
  module/VuFind/src/VuFind/Db/Row/Feedback.php
  module/VuFind/src/VuFind/Db/Service/FeedbackService.php
  module/VuFind/src/VuFind/Db/Service/FeedbackServiceInterface.php
  module/VuFind/src/VuFind/Db/Service/PluginManager.php
  module/VuFind/src/VuFind/Db/Table/PluginManager.php
  module/VuFind/src/VuFind/Form/Handler/Database.php
  module/VuFind/src/VuFind/Form/Handler/DatabaseFactory.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Form/Handler/DatabaseTest.php
Labels: architecture

#3653 Expand use/scope of SessionService
  module/VuFind/src/VuFind/Db/Service/PluginManager.php
  module/VuFind/src/VuFind/Db/Service/SessionService.php
  module/VuFind/src/VuFind/Db/Service/SessionServiceFactory.php
  module/VuFind/src/VuFind/Db/Service/SessionServiceInterface.php
  module/VuFind/src/VuFind/Session/AbstractBase.php
  module/VuFind/src/VuFind/Session/AbstractBaseFactory.php
  module/VuFind/src/VuFind/Session/Database.php
  module/VuFind/src/VuFindTest/Container/MockDbServicePluginManager.php
  module/VuFind/src/VuFindTest/Unit/SessionHandlerTestCase.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Session/DatabaseTest.php
Labels: architecture

#3629 Refactor libraryCardsEnabled method to AccountCapabilities class.
  module/VuFind/src/VuFind/Config/AccountCapabilities.php
  module/VuFind/src/VuFind/Config/AccountCapabilitiesFactory.php
  module/VuFind/src/VuFind/Db/Row/PrivateUser.php
  module/VuFind/src/VuFind/Db/Row/User.php
  module/VuFind/src/VuFind/Db/Row/UserFactory.php
  module/VuFind/src/VuFind/View/Helper/Root/AccountMenu.php
  module/VuFind/tests/unit-tests/src/VuFindTest/AjaxHandler/CommentRecordTest.php
Labels: architecture

#3666 Add/implement CommentsServiceInterface::createEntity()
  module/VuFind/src/VuFind/Db/Service/CommentsService.php
  module/VuFind/src/VuFind/Db/Service/CommentsServiceInterface.php
Labels: architecture

#3672 Remove undefined variable reference caused by merge error.
  themes/bootstrap3/templates/RecordTab/holdingsils/standard.phtml
Labels: bugfix

#3667 Establish entity interface and database service for login tokens.
  module/VuFind/src/VuFind/Auth/LoginTokenManager.php
  module/VuFind/src/VuFind/Auth/LoginTokenManagerFactory.php
  module/VuFind/src/VuFind/Db/Entity/LoginTokenEntityInterface.php
  module/VuFind/src/VuFind/Db/Row/LoginToken.php
  module/VuFind/src/VuFind/Db/Service/LoginTokenService.php
  module/VuFind/src/VuFind/Db/Service/LoginTokenServiceInterface.php
  module/VuFind/src/VuFind/Db/Service/PluginManager.php
  module/VuFind/src/VuFind/Db/Table/LoginToken.php
  module/VuFind/src/VuFind/View/Helper/Root/Auth.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/LoginTokenManagerTest.php
  themes/bootstrap3/templates/myresearch/profile.phtml
Labels: architecture

#3677 Fix .gitignore for TAGS files.
  .gitignore
Labels: tooling

#3646 Expand ChangeTracker entity interface; add ChangeTracker service
  module/VuFind/src/VuFind/Db/Entity/ChangeTrackerEntityInterface.php
  module/VuFind/src/VuFind/Db/Row/ChangeTracker.php
  module/VuFind/src/VuFind/Db/Service/ChangeTrackerService.php
  module/VuFind/src/VuFind/Db/Service/ChangeTrackerServiceInterface.php
  module/VuFind/src/VuFind/Db/Service/PluginManager.php
  module/VuFind/src/VuFind/XSLT/Import/VuFind.php
  module/VuFind/tests/unit-tests/src/VuFindTest/XSLT/Import/VuFindTest.php
Labels: architecture

#3673 Add sort option to AbstractSearchObject recommendations.
  config/vufind/searches.ini
  module/VuFind/src/VuFind/Recommend/AbstractSearchObject.php
Labels: improvement

#3642 VUFIND-1667: Fix tabbing within a modal dialog
  themes/bootstrap3/js/lightbox.js
Labels: bugfix

#3680 Add TOC from Obalkyknih.cz
  config/vufind/config.ini
  module/VuFind/src/VuFind/Content/AbstractBase.php
  module/VuFind/src/VuFind/Content/ObalkyKnihContentFactory.php
  module/VuFind/src/VuFind/Content/ObalkyKnihService.php
  module/VuFind/src/VuFind/Content/TOC/ObalkyKnih.php
  module/VuFind/src/VuFind/Content/TOC/PluginManager.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Content/TOC/ObalkyKnihTest.php
Labels: new feature

#3679 Introduce UserCardService.
  module/VuFind/src/VuFind/Auth/AbstractBase.php
  module/VuFind/src/VuFind/Auth/Shibboleth.php
  module/VuFind/src/VuFind/Controller/Feature/SecureDatabaseTrait.php
  module/VuFind/src/VuFind/Controller/InstallController.php
  module/VuFind/src/VuFind/Controller/LibraryCardsController.php
  module/VuFind/src/VuFind/Db/Row/User.php
  module/VuFind/src/VuFind/Db/Service/PluginManager.php
  module/VuFind/src/VuFind/Db/Service/UserCardService.php
  module/VuFind/src/VuFind/Db/Service/UserCardServiceFactory.php
  module/VuFind/src/VuFind/Db/Service/UserCardServiceInterface.php
  module/VuFind/src/VuFind/View/Helper/Root/LibraryCards.php
  module/VuFind/src/VuFind/View/Helper/Root/LibraryCardsFactory.php
  themes/bootstrap3/templates/librarycards/selectcard.phtml
  themes/bootstrap3/templates/oauth2/authorize.phtml
  themes/bootstrap5/templates/librarycards/selectcard.phtml
  themes/bootstrap5/templates/oauth2/authorize.phtml
  themes/root/theme.config.php
Labels: architecture

#3689 Add phpunitfast-with-shutdown-on-fail Phing task.
  build.xml
Labels: tooling

#3621 Add optional formatString argument to SortFacetList helper.
  module/VuFind/src/VuFind/View/Helper/Root/SortFacetList.php
  themes/bootstrap3/templates/ContentBlock/FacetList.phtml
  themes/bootstrap5/templates/ContentBlock/FacetList.phtml
Labels: new feature

#3696 Fix phing build issues.
  build.xml
Labels: bugfix, tooling

#3694 Minor fixes/improvements to user list-related templates.
  themes/bootstrap3/templates/myresearch/editlist.phtml
  themes/bootstrap3/templates/myresearch/menu.phtml
  themes/bootstrap3/templates/myresearch/mylist.phtml
  themes/bootstrap5/templates/myresearch/editlist.phtml
  themes/bootstrap5/templates/myresearch/menu.phtml
  themes/bootstrap5/templates/myresearch/mylist.phtml
Labels: bugfix

#3568 KohaRest driver: Enable the use of custom renewal block messages in .ini
  config/vufind/KohaRest.ini
  module/VuFind/src/VuFind/ILS/Driver/KohaRest.php
Labels: improvement

#3695 Implement and use UserCardServiceInterface::getAllRowsWithUsernames().
  module/VuFind/src/VuFind/Db/Service/UserCardService.php
  module/VuFind/src/VuFind/Db/Service/UserCardServiceInterface.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/SwitchDbHashCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/SwitchDbHashCommandFactory.php
  module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Util/SwitchDbHashCommandTest.php
Labels: architecture

#3697 Fix results scripts init on record versions tab.
  themes/bootstrap3/templates/RecordTab/versions.phtml
  themes/bootstrap5/templates/RecordTab/versions.phtml
Labels: bugfix

#3699 Corrects German translation file
  languages/de.ini
Labels: improvement

#3713 FOLIO: Detect inactive location
  module/VuFind/src/VuFind/ILS/Driver/Folio.php
  module/VuFind/tests/unit-tests/src/VuFindTest/ILS/Driver/FolioTest.php
Labels: improvement

#3685 Fix facets JS issues.
  build.xml
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchFacetsTest.php
  themes/bootstrap3/js/common.js
  themes/bootstrap3/js/facets.js
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/js/bs3-compat.js
  themes/bootstrap5/js/common.js
  themes/bootstrap5/js/facets.js
  themes/bootstrap5/js/lightbox.js
  themes/bootstrap5/scss/bootstrap-variable-overrides.scss
  themes/sandal5/css/compiled.css
Labels: bugfix

#3702 Increase use of UserEntityInterface in MyResearchController.
  module/VuFind/src/VuFind/Controller/MyResearchController.php
Labels: architecture

#3704 Increase use of entity interfaces in unit tests.
  module/VuFind/src/VuFindTest/Unit/AjaxHandlerTestCase.php
  module/VuFind/tests/unit-tests/src/VuFindTest/AjaxHandler/CheckRequestIsValidTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/ChoiceAuthTest.php
Labels: tests

#3705 Remove unnecessary timezone from Comments class.
  module/VuFind/src/VuFind/Db/Row/Comments.php
Labels: architecture

#3709 Refactor admin FeedbackController to use FeedbackService.
  module/VuFind/src/VuFind/Db/Service/FeedbackService.php
  module/VuFind/src/VuFind/Db/Service/FeedbackServiceInterface.php
  module/VuFindAdmin/src/VuFindAdmin/Controller/FeedbackController.php
Labels: architecture

#3701 Introduce UserList service
  module/VuFind/src/VuFind/ChannelProvider/ListItems.php
  module/VuFind/src/VuFind/ChannelProvider/ListItemsFactory.php
  module/VuFind/src/VuFind/Controller/MyResearchController.php
  module/VuFind/src/VuFind/Controller/Plugin/Favorites.php
  module/VuFind/src/VuFind/Db/Row/User.php
  module/VuFind/src/VuFind/Db/Service/PluginManager.php
  module/VuFind/src/VuFind/Db/Service/UserListService.php
  module/VuFind/src/VuFind/Db/Service/UserListServiceInterface.php
  module/VuFind/src/VuFind/Db/Table/UserList.php
  module/VuFind/src/VuFind/Favorites/FavoritesService.php
  module/VuFind/src/VuFind/Favorites/FavoritesServiceFactory.php
  module/VuFind/src/VuFind/Search/Favorites/Results.php
  module/VuFind/src/VuFind/Search/Favorites/ResultsFactory.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Db/Table/UserListTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Favorites/FavoritesServiceTest.php
Labels: architecture

#3720 Add integration test coverage for ListItems channel provider.
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/FavoritesTest.php
Labels: tests

#3706 Use ChangeTrackerService in OAI server.
  module/VuFind/src/VuFind/Db/Service/ChangeTrackerService.php
  module/VuFind/src/VuFind/Db/Service/ChangeTrackerServiceInterface.php
  module/VuFind/src/VuFind/OAI/Server.php
  module/VuFind/src/VuFind/OAI/Server/Auth.php
  module/VuFind/src/VuFind/OAI/ServerFactory.php
  module/VuFind/tests/unit-tests/src/VuFindTest/OAI/Server/AuthTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/OAI/ServerTest.php
Labels: architecture

#3708 Migrate more methods to ResourceService.
  module/VuFind/src/VuFind/Controller/UpgradeController.php
  module/VuFind/src/VuFind/Db/Row/User.php
  module/VuFind/src/VuFind/Db/Row/UserList.php
  module/VuFind/src/VuFind/Db/Service/ResourceService.php
  module/VuFind/src/VuFind/Db/Service/ResourceServiceInterface.php
  module/VuFind/src/VuFind/Db/Table/Resource.php
Labels: architecture

#3722 Move bootstrapper activities to event handlers
  module/VuFind/src/VuFind/Bootstrapper.php
Labels: improvement

#3687 Fix order of parameters in assertEquals.
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/CollectionsTest.php
Labels: bugfix, tests

#3681 Update setupJumpMenus from jQuery to Javascript
  themes/bootstrap3/js/common.js
  themes/bootstrap5/js/common.js
Labels: improvement

#3726 Fix invalid argument in Record Driver test harness.
  module/VuFind/src/VuFindTest/RecordDriver/TestHarness.php
Labels: bugfix, tests

#3723 Refactor User::updateEmail to UserServiceInterface::updateUserEmail
  module/VuFind/src/VuFind/Auth/AbstractBase.php
  module/VuFind/src/VuFind/Auth/CAS.php
  module/VuFind/src/VuFind/Auth/Database.php
  module/VuFind/src/VuFind/Auth/Facebook.php
  module/VuFind/src/VuFind/Auth/ILS.php
  module/VuFind/src/VuFind/Auth/Manager.php
  module/VuFind/src/VuFind/Auth/Shibboleth.php
  module/VuFind/src/VuFind/Auth/SimulatedSSO.php
  module/VuFind/src/VuFind/Controller/AlmaController.php
  module/VuFind/src/VuFind/Controller/MyResearchController.php
  module/VuFind/src/VuFind/Db/Row/User.php
  module/VuFind/src/VuFind/Db/Service/UserService.php
  module/VuFind/src/VuFind/Db/Service/UserServiceInterface.php
  module/VuFind/src/VuFindTest/Feature/LiveDatabaseTrait.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Auth/DatabaseTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Auth/ILSTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Auth/ShibbolethTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/DatabaseUnitTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/MultiILSTest.php
Labels: architecture
