Repository vufind-org/vufind, pull requests merged in 2024-08, with the labels that each got.

#3312 KohaRest: Display the date and destination of transitting items
  module/VuFind/src/VuFind/ILS/Driver/KohaRest.php
Labels: new language strings

#3840 Add mechanism to display textual holdings (866 MARC field)
  config/vufind/RecordDataFormatter.ini
  module/VuFind/src/VuFind/RecordDriver/Feature/MarcAdvancedTrait.php
Labels: improvement

#3847 [VUFIND-1682] Improve confirmation banners for account functionality
  languages/en.ini
  module/VuFind/src/VuFind/Controller/Plugin/Holds.php
  module/VuFind/src/VuFind/Controller/Plugin/ILLRequests.php
  module/VuFind/src/VuFind/Controller/Plugin/Renewals.php
  module/VuFind/src/VuFind/Controller/Plugin/StorageRetrievalRequests.php
  module/VuFind/src/VuFind/View/Helper/Root/Flashmessages.php
Labels: improvement

#3848 [VUFIND-1683] Label drop-downs for deleting lists/library cards
  themes/bootstrap3/templates/librarycards/home.phtml
  themes/bootstrap3/templates/myresearch/mylist.phtml
  themes/bootstrap5/templates/librarycards/home.phtml
  themes/bootstrap5/templates/myresearch/mylist.phtml
Labels: improvement

#3820 [VUFIND-1697] NPM build:css task should auto-install dependencies
  package.json
  themes/bootstrap5/package.json
Labels: tooling

#3851 SierraRest: improve extractVolume compatibility
  module/VuFind/src/VuFind/ILS/Driver/SierraRest.php
Labels: bugfix

#3850 Add SpecBuilder->removeLine() method
  module/VuFind/src/VuFind/View/Helper/Root/RecordDataFormatter/SpecBuilder.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/RecordDataFormatter/SpecBuilderTest.php
Labels: improvement

#3849 schema.org: Remove default type "Product"
  module/VuFind/src/VuFind/RecordDriver/DefaultRecord.php
  module/VuFind/src/VuFind/View/Helper/Root/SchemaOrg.php
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordDriver/DefaultRecordTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordDriver/SolrMarcTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/SchemaOrgTest.php
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/core.phtml
  themes/bootstrap3/templates/RecordDriver/EDS/core.phtml
  themes/bootstrap3/templates/RecordDriver/EPF/core.phtml
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/core.phtml
  themes/bootstrap5/templates/RecordDriver/EDS/core.phtml
  themes/bootstrap5/templates/RecordDriver/EPF/core.phtml
Labels: improvement

#2850 Improve routing configuration to simplify URLs for help pages
  module/VuFind/config/module.config.php
  module/VuFind/src/VuFind/Controller/HelpController.php
  themes/bootstrap3/templates/Recommend/MapSelection.phtml
  themes/bootstrap3/templates/devtools/language.phtml
  themes/bootstrap3/templates/footer.phtml
  themes/bootstrap3/templates/search/advanced/layout.phtml
  themes/bootstrap3/templates/search/list-visual.phtml
  themes/bootstrap5/templates/Recommend/MapSelection.phtml
  themes/bootstrap5/templates/devtools/language.phtml
  themes/bootstrap5/templates/footer.phtml
  themes/bootstrap5/templates/search/advanced/layout.phtml
  themes/bootstrap5/templates/search/list-visual.phtml
  themes/root/templates/HelpTranslations/ar/advsearch.phtml
  themes/root/templates/HelpTranslations/ar/blender_advsearch.phtml
  themes/root/templates/HelpTranslations/cs/advsearch.phtml
  themes/root/templates/HelpTranslations/de/advsearch.phtml
  themes/root/templates/HelpTranslations/de/blender_advsearch.phtml
  themes/root/templates/HelpTranslations/el/advsearch.phtml
  themes/root/templates/HelpTranslations/en/advsearch.phtml
  themes/root/templates/HelpTranslations/en/blender_advsearch.phtml
  themes/root/templates/HelpTranslations/es/advsearch.phtml
  themes/root/templates/HelpTranslations/eu/advsearch.phtml
  themes/root/templates/HelpTranslations/fr/advsearch.phtml
  themes/root/templates/HelpTranslations/ga/advsearch.phtml
  themes/root/templates/HelpTranslations/hy/advsearch.phtml
  themes/root/templates/HelpTranslations/hy/blender_advsearch.phtml
  themes/root/templates/HelpTranslations/it/advsearch.phtml
  themes/root/templates/HelpTranslations/ja/advsearch.phtml
  themes/root/templates/HelpTranslations/pl/advsearch.phtml
  themes/root/templates/HelpTranslations/pt-br/advsearch.phtml
  themes/root/templates/HelpTranslations/pt-br/blender_advsearch.phtml
  themes/root/templates/HelpTranslations/tr/advsearch.phtml
  themes/root/templates/HelpTranslations/uk/advsearch.phtml
Labels: improvement

#3852 export-menu.phtml: Add rel="nofollow" to generated links
  themes/bootstrap3/templates/record/export-menu.phtml
  themes/bootstrap5/templates/record/export-menu.phtml
Labels: improvement

#3855 Fix a couple of Finnish translations.
  languages/fi.ini
Labels: bugfix

#3854 [10.0] Fix deferred facets.
  module/VuFind/src/VuFind/AjaxHandler/GetSideFacets.php
  module/VuFind/src/VuFindTest/Feature/SearchLimitTrait.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchFacetsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchLimitTest.php
  themes/bootstrap3/js/facets.js
  themes/bootstrap5/js/facets.js
Labels: bugfix

#3857 Phing: add properties to override MARC test data locations.
  build.xml
Labels: tooling

#3856 KohaRest: Add option to include suspended holds in hold queue length calculation.
  config/vufind/KohaRest.ini
  module/VuFind/src/VuFind/ILS/Driver/KohaRest.php
Labels: improvement

#3859 FOLIO: Add settings to ignore expired courses in course reserves
  config/vufind/Folio.ini
  module/VuFind/src/VuFind/ILS/Driver/Folio.php
Labels: improvement

#3858 FOLIO: automatically renew expired token as needed.
  module/VuFind/src/VuFind/ILS/Driver/AbstractAPI.php
  module/VuFind/src/VuFind/ILS/Driver/Folio.php
Labels: improvement

#3844 [VUFIND-1678] Add setting to include extra URLs in sitemap index
  config/vufind/sitemap.ini
  module/VuFind/src/VuFind/Sitemap/Generator.php
  module/VuFind/tests/fixtures/sitemap/staticIndex.xml
  module/VuFind/tests/unit-tests/src/VuFindTest/Sitemap/GeneratorTest.php
Labels: improvement

#3867 KohaRest: Fix sorting of loans by title.
  module/VuFind/src/VuFind/ILS/Driver/KohaRest.php
Labels: bugfix

#3866 Allow 404 response from Solr to be retried.
  module/VuFindSearch/src/VuFindSearch/Backend/Solr/Connector.php
Labels: improvement

#3863 Fix KeepAlive error in trigger-print.js
  themes/bootstrap3/js/check_save_statuses.js
  themes/bootstrap3/js/common.js
  themes/bootstrap3/js/trigger_print.js
  themes/bootstrap5/js/check_save_statuses.js
  themes/bootstrap5/js/common.js
  themes/bootstrap5/js/trigger_print.js
Labels: bugfix

#3870 Showing FunctionQuery in explain
  languages/de.ini
  languages/en.ini
  module/VuFind/src/VuFind/Search/Solr/Explanation.php
  module/VuFind/src/VuFind/View/Helper/Root/ExplainElement.php
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/explain-line.phtml
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/explain-line.phtml
Labels: improvement

#3873 Fixed color of focused btn-default in sandal themes
  themes/sandal/css/compiled.css
  themes/sandal/less/common.less
  themes/sandal/scss/common.scss
  themes/sandal5/css/compiled.css
  themes/sandal5/scss/common.scss
Labels: bugfix

#3862 Fix bug: allow display of facet value of 0.
  themes/bootstrap3/templates/Recommend/SideFacets/single-facet.phtml
  themes/bootstrap5/templates/Recommend/SideFacets/single-facet.phtml
Labels: bugfix

#3865 Adding margin to searchform
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/components/search.less
  themes/bootstrap3/scss/components/search.scss
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/scss/components/search.scss
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal5/css/compiled.css
Labels: improvement

#3879 Eliminate double-escaping from searchTabs.phtml
  themes/bootstrap3/templates/search/searchTabs.phtml
  themes/bootstrap5/templates/search/searchTabs.phtml
Labels: bugfix

#3883 Fix some deprecation comments.
  module/VuFind/src/VuFind/Db/Row/UserList.php
  module/VuFind/src/VuFind/Db/Table/Resource.php
  module/VuFind/src/VuFind/Db/Table/Search.php
Labels: bugfix

#3887 Fix bug: Phing 3 broke PostgreSQL setup.
  build.xml
Labels: bugfix

#3889 Fix missing UserEntityInterface references in InstallController
  module/VuFind/src/VuFind/Controller/InstallController.php
Labels: bugfix

#3890 KohaRest: Fix holdings with older Koha DI plugin versions.
  module/VuFind/src/VuFind/ILS/Driver/KohaRest.php
Labels: bugfix

#3886 HoldingsILS tab: use UserEntityInterface appropriately.
  themes/bootstrap3/templates/RecordTab/holdingsils.phtml
  themes/bootstrap5/templates/RecordTab/holdingsils.phtml
Labels: bugfix

#3878 Fix BrowZine grid template images for consistency.
  themes/bootstrap3/templates/RecordDriver/BrowZine/result-grid.phtml
  themes/bootstrap5/templates/RecordDriver/BrowZine/result-grid.phtml
Labels: bugfix

#3884 Sort favorites by save date
  languages/de.ini
  languages/en.ini
  module/VuFind/src/VuFind/Db/Table/Resource.php
  module/VuFind/src/VuFind/Search/Favorites/Options.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/FavoritesTest.php
Labels: improvement

#3893 Fix PHP 8.2 deprecations
  module/VuFind/src/VuFind/ILS/Driver/Unicorn.php
  module/VuFind/src/VuFind/ILS/Driver/Voyager.php
  module/VuFind/src/VuFind/ILS/Driver/VoyagerRestful.php
  module/VuFind/tests/unit-tests/src/VuFindTest/ILS/Driver/VoyagerRestfulTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/ILS/Driver/VoyagerTest.php
  themes/bootstrap3/templates/Helpers/copy-to-clipboard-button.phtml
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/list-entry.phtml
  themes/bootstrap3/templates/upgrade/fixanonymoustags.phtml
  themes/bootstrap3/templates/upgrade/fixduplicatetags.phtml
  themes/bootstrap3/templates/upgrade/fixmetadata.phtml
  themes/bootstrap5/templates/Helpers/copy-to-clipboard-button.phtml
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/list-entry.phtml
  themes/bootstrap5/templates/upgrade/fixanonymoustags.phtml
  themes/bootstrap5/templates/upgrade/fixduplicatetags.phtml
  themes/bootstrap5/templates/upgrade/fixmetadata.phtml
Labels: architecture

#3875 ExternalVuFind: Cache results
  config/vufind/ExternalVuFind.ini
  config/vufind/searches.ini
  module/VuFind/config/module.config.php
  module/VuFind/src/VuFind/Connection/ExternalVuFind.php
  module/VuFind/src/VuFind/Connection/ExternalVuFindFactory.php
  module/VuFind/src/VuFind/Http/CachingDownloader.php
  module/VuFind/src/VuFind/Http/CachingDownloaderAwareTrait.php
Labels: improvement

#3896 Fix Db service factories to use Psr\Container.
  module/VuFind/src/VuFind/Db/Service/AbstractDbServiceFactory.php
  module/VuFind/src/VuFind/Db/Service/AccessTokenServiceFactory.php
  module/VuFind/src/VuFind/Db/Service/ResourceServiceFactory.php
  module/VuFind/src/VuFind/Db/Service/UserCardServiceFactory.php
  module/VuFind/src/VuFind/Db/Service/UserServiceFactory.php
Labels: bugfix

#3868 Add permalink to search results in embedded mode; adjust thumbnail links
  languages/en.ini
  module/VuFind/src/VuFind/View/Helper/Root/Record.php
  themes/bootstrap3/js/embedded_record.js
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/core.phtml
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/cover.phtml
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/result-list.phtml
  themes/bootstrap3/templates/RecordDriver/EDS/result-list.phtml
  themes/bootstrap3/templates/RecordDriver/Pazpar2/result-list.phtml
  themes/bootstrap3/templates/RecordDriver/SolrAuthDefault/result-list.phtml
  themes/bootstrap3/templates/RecordDriver/SolrOverdrive/result-list.phtml
  themes/bootstrap5/js/embedded_record.js
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/core.phtml
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/cover.phtml
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/result-list.phtml
  themes/bootstrap5/templates/RecordDriver/EDS/result-list.phtml
  themes/bootstrap5/templates/RecordDriver/Pazpar2/result-list.phtml
  themes/bootstrap5/templates/RecordDriver/SolrAuthDefault/result-list.phtml
  themes/bootstrap5/templates/RecordDriver/SolrOverdrive/result-list.phtml
Labels: accessibility

#3894 Smarter/more configurable disabling of email functionality
  config/vufind/config.ini
  module/VuFind/src/VuFind/Config/AccountCapabilities.php
  module/VuFind/src/VuFind/Config/Upgrade.php
  module/VuFind/src/VuFind/Controller/AbstractRecord.php
  module/VuFind/src/VuFind/Controller/CartController.php
  module/VuFind/src/VuFind/Controller/SearchController.php
  module/VuFind/tests/fixtures/configs/email-require-login-false/config.ini
  module/VuFind/tests/fixtures/configs/email-require-login-true/config.ini
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/UrlShortenerTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Config/AccountCapabilitiesTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Config/UpgradeTest.php
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/toolbar.phtml
  themes/bootstrap3/templates/cart/cart.phtml
  themes/bootstrap3/templates/myresearch/bulk-action-buttons.phtml
  themes/bootstrap3/templates/search/bulk-action-buttons.phtml
  themes/bootstrap3/templates/search/controls/results-tools.phtml
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/toolbar.phtml
  themes/bootstrap5/templates/cart/cart.phtml
  themes/bootstrap5/templates/myresearch/bulk-action-buttons.phtml
  themes/bootstrap5/templates/search/bulk-action-buttons.phtml
  themes/bootstrap5/templates/search/controls/results-tools.phtml
Labels: improvement
