Repository vufind-org/vufind, pull requests merged in 2024-06, with the labels that each got.

#3691 OverDrive: Load availability via overdrive ID
  themes/bootstrap3/templates/RecordDriver/SolrOverdrive/result-list.phtml
  themes/bootstrap5/templates/RecordDriver/SolrOverdrive/result-list.phtml
Labels: bugfix

#3690 OverDrive: Update content security policy for images
  config/vufind/contentsecuritypolicy.ini
Labels: improvement

#3739 Expand Ratings Entity Interface
  module/VuFind/src/VuFind/Db/Entity/RatingsEntityInterface.php
  module/VuFind/src/VuFind/Db/Row/Ratings.php
Labels: architecture

#3707 Use different debug formatting string on console vs. web.
  module/VuFind/src/VuFind/Log/LoggerFactory.php
Labels: tooling

#3717 PHPUnit: turn on displayDetailsOnTestsThatTriggerDeprecations.
  module/VuFind/tests/phpunit.xml
Labels: tooling

#3693 OverDrive: Support disabled patron API
  config/vufind/Overdrive.ini
  module/VuFind/src/VuFind/DigitalContent/OverdriveConnector.php
  module/VuFind/src/VuFind/RecordDriver/SolrOverdrive.php
  themes/bootstrap3/templates/RecordTab/overdriveholdings.phtml
  themes/bootstrap5/templates/RecordTab/overdriveholdings.phtml
Labels: improvement

#3742 Simplify <br> tags in Javascript code.
  themes/bootstrap3/js/check_item_statuses.js
  themes/bootstrap3/js/lightbox.js
  themes/bootstrap5/js/check_item_statuses.js
  themes/bootstrap5/js/lightbox.js
Labels: improvement

#3719 Feedback: expand test; improve error handling.
  module/VuFind/src/VuFind/Form/Handler/Email.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/FeedbackTest.php
Labels: improvement, tests

#3721 Add testing of deleted records to OaiTest.
  build.xml
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/OaiTest.php
  tests/data/fake-deleted-ids.txt
Labels: tests

#3733 Fix outdated comments to use UserEntityInterface.
  module/VuFind/src/VuFind/Auth/Manager.php
  module/VuFind/src/VuFind/Controller/LibraryCardsController.php
Labels: bugfix, small, documentation

#3750 Allow the order of author groups to be configurable
  module/VuFind/src/VuFind/View/Helper/Root/RecordDataFormatterFactory.php
Labels: improvement

#3728 Deprecate several obsolete User row methods
  module/VuFind/src/VuFind/Auth/Database.php
  module/VuFind/src/VuFind/Auth/Email.php
  module/VuFind/src/VuFind/Auth/ILS.php
  module/VuFind/src/VuFind/Auth/ILSAuthenticator.php
  module/VuFind/src/VuFind/Auth/Manager.php
  module/VuFind/src/VuFind/Controller/AlmaController.php
  module/VuFind/src/VuFind/Controller/MyResearchController.php
  module/VuFind/src/VuFind/Db/Entity/UserEntityInterface.php
  module/VuFind/src/VuFind/Db/Row/User.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/ILSAuthenticatorTest.php
Labels: architecture

#3730 Deprecate record driver getContainingLists() method.
  module/VuFind/src/VuFind/Db/Service/UserListService.php
  module/VuFind/src/VuFind/Db/Service/UserListServiceInterface.php
  module/VuFind/src/VuFind/RecordDriver/AbstractBase.php
  module/VuFind/src/VuFind/View/Helper/Root/Record.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/RecordTest.php
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/list-entry.phtml
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/list-entry.phtml
Labels: architecture

#3734 Use UserEntityInterface in email-related MyResearchController methods.
  module/VuFind/src/VuFind/Controller/MyResearchController.php
Labels: architecture

#3736 Add stubs for remaining database services.
  module/VuFind/src/VuFind/Db/Service/PluginManager.php
  module/VuFind/src/VuFind/Db/Service/ResourceTagsService.php
  module/VuFind/src/VuFind/Db/Service/ResourceTagsServiceInterface.php
  module/VuFind/src/VuFind/Db/Service/SearchService.php
  module/VuFind/src/VuFind/Db/Service/SearchServiceInterface.php
Labels: architecture

#3747 Expand Search entity interface
  module/VuFind/src/VuFind/Db/Entity/SearchEntityInterface.php
  module/VuFind/src/VuFind/Db/Row/Search.php
Labels: architecture

#3756 Fix UserResource getters
  module/VuFind/src/VuFind/Db/Row/UserResource.php
Labels: bugfix

#3753 Fix incorrect capitalization of DateTime in comments.
  module/VuFind/src/VuFind/Db/Entity/UserEntityInterface.php
Labels: bugfix

#3703 Refactor tag administration to use database services
  module/VuFind/src/VuFind/Db/Service/ResourceTagsService.php
  module/VuFind/src/VuFind/Db/Service/ResourceTagsServiceInterface.php
  module/VuFind/src/VuFind/Db/Service/TagService.php
  module/VuFind/src/VuFind/Db/Service/TagServiceInterface.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/RecordActionsTest.php
  module/VuFindAdmin/src/VuFindAdmin/Controller/TagsController.php
  themes/bootstrap3/templates/admin/tags/list.phtml
  themes/bootstrap5/templates/admin/tags/list.phtml
Labels: architecture

#3759 Added missing parameters college and major in user entity interface
  module/VuFind/src/VuFind/Db/Entity/UserEntityInterface.php
  module/VuFind/src/VuFind/Db/Row/User.php
Labels: architecture

#3757 Fix issues with search database table and entity interface
  module/VuFind/sql/migrations/pgsql/10.0/002-modify-search-user-column.sql
  module/VuFind/sql/mysql.sql
  module/VuFind/sql/pgsql.sql
  module/VuFind/src/VuFind/Controller/AbstractSearch.php
  module/VuFind/src/VuFind/Controller/MyResearchController.php
  module/VuFind/src/VuFind/Controller/Plugin/ResultScroller.php
  module/VuFind/src/VuFind/Controller/UpgradeController.php
  module/VuFind/src/VuFind/Db/Entity/SearchEntityInterface.php
  module/VuFind/src/VuFind/Db/Row/Search.php
  module/VuFind/src/VuFind/Db/Service/SearchService.php
  module/VuFind/src/VuFind/Db/Service/SearchServiceInterface.php
  module/VuFind/src/VuFind/Db/Table/Search.php
  module/VuFind/src/VuFind/Search/History.php
  module/VuFind/src/VuFind/Search/Memory.php
  module/VuFindConsole/src/VuFindConsole/Command/ScheduledSearch/NotifyCommand.php
Labels: bugfix

#3745 VUFIND-1675: Fix mobile top menu colors on sandal
  themes/sandal/css/compiled.css
  themes/sandal/less/sandal.less
  themes/sandal/scss/sandal.scss
Labels: bugfix

#3764 Minor improvements to MockContainerTrait.
  module/VuFind/src/VuFindTest/Container/MockContainerTrait.php
Labels: tests

#3763 Refactor and replace User row's getLists() method.
  module/VuFind/src/VuFind/Controller/AbstractRecord.php
  module/VuFind/src/VuFind/Controller/CartController.php
  module/VuFind/src/VuFind/Controller/MyResearchController.php
  module/VuFind/src/VuFind/Db/Row/User.php
  module/VuFind/src/VuFind/Db/Service/UserListService.php
  module/VuFind/src/VuFind/Db/Service/UserListServiceInterface.php
  module/VuFind/src/VuFind/View/Helper/Root/UserList.php
  module/VuFind/src/VuFind/View/Helper/Root/UserListFactory.php
  themes/bootstrap3/templates/myresearch/menu.phtml
  themes/bootstrap5/templates/myresearch/menu.phtml
Labels: architecture

#3765 Refactor ResourceTags createLink method to database service.
  module/VuFind/src/VuFind/Db/Row/Resource.php
  module/VuFind/src/VuFind/Db/Row/UserList.php
  module/VuFind/src/VuFind/Db/Service/ResourceTagsService.php
  module/VuFind/src/VuFind/Db/Service/ResourceTagsServiceInterface.php
  module/VuFind/src/VuFind/Db/Table/ResourceTags.php
  module/VuFind/src/VuFind/Db/Table/Tags.php
Labels: architecture

#3767 Add missing dependency annotation to BulkTest.
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/BulkTest.php
Labels: tests

#3766 DB services: Fix argument names for consistency.
  module/VuFind/src/VuFind/Db/Service/CommentsService.php
  module/VuFind/src/VuFind/Db/Service/CommentsServiceInterface.php
  module/VuFind/src/VuFind/Db/Service/LoginTokenService.php
  module/VuFind/src/VuFind/Db/Service/LoginTokenServiceInterface.php
  module/VuFind/src/VuFind/Db/Service/RatingsService.php
  module/VuFind/src/VuFind/Db/Service/RatingsServiceInterface.php
  module/VuFind/src/VuFind/Db/Service/UserCardService.php
  module/VuFind/src/VuFind/Db/Service/UserCardServiceInterface.php
  module/VuFind/src/VuFind/Db/Service/UserResourceService.php
  module/VuFind/src/VuFind/Db/Service/UserResourceServiceInterface.php
  module/VuFind/src/VuFind/Db/Service/UserService.php
  module/VuFind/src/VuFind/Db/Service/UserServiceInterface.php
Labels: bugfix, architecture

#3729 Add support for logging emails to a file.
  config/vufind/config.ini
  module/VuFind/src/VuFind/Mailer/Factory.php
  module/VuFind/src/VuFind/Mailer/Mailer.php
Labels: tooling, tests

#3731 Update feedback admin template to use FeedbackEntityInterface.
  module/VuFind/src/VuFind/Db/Service/FeedbackService.php
  themes/bootstrap3/templates/admin/feedback/home.phtml
  themes/bootstrap5/templates/admin/feedback/home.phtml
Labels: architecture

#3769 Refactor more favorites and list logic into FavoritesService
  module/VuFind/src/VuFind/Controller/AbstractBase.php
  module/VuFind/src/VuFind/Controller/AbstractRecord.php
  module/VuFind/src/VuFind/Controller/CartController.php
  module/VuFind/src/VuFind/Controller/MyResearchController.php
  module/VuFind/src/VuFind/Controller/Plugin/Favorites.php
  module/VuFind/src/VuFind/Controller/Plugin/FavoritesFactory.php
  module/VuFind/src/VuFind/Db/Row/User.php
  module/VuFind/src/VuFind/Db/Row/UserFactory.php
  module/VuFind/src/VuFind/Db/Row/UserList.php
  module/VuFind/src/VuFind/Db/Service/UserListService.php
  module/VuFind/src/VuFind/Db/Service/UserListServiceInterface.php
  module/VuFind/src/VuFind/Db/Table/UserListFactory.php
  module/VuFind/src/VuFind/Favorites/FavoritesService.php
  module/VuFind/src/VuFind/Favorites/FavoritesServiceFactory.php
  module/VuFind/src/VuFind/View/Helper/Root/UserList.php
  module/VuFind/src/VuFind/View/Helper/Root/UserListFactory.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Favorites/FavoritesServiceTest.php
  themes/bootstrap3/templates/myresearch/bulk-action-buttons.phtml
  themes/bootstrap3/templates/myresearch/mylist.phtml
  themes/bootstrap5/templates/myresearch/bulk-action-buttons.phtml
  themes/bootstrap5/templates/myresearch/mylist.phtml
Labels: architecture

#3773 Deprecate a few more User row methods.
  module/VuFind/src/VuFind/Auth/ILSAuthenticator.php
  module/VuFind/src/VuFind/Controller/MyResearchController.php
  module/VuFind/src/VuFind/Db/Row/User.php
  module/VuFind/src/VuFind/Db/Row/UserFactory.php
Labels: architecture

#3772 Refactor User and UserList tag methods to FavoritesService
  module/VuFind/src/VuFind/Controller/MyResearchController.php
  module/VuFind/src/VuFind/Db/Row/User.php
  module/VuFind/src/VuFind/Db/Row/UserList.php
  module/VuFind/src/VuFind/Db/Service/TagService.php
  module/VuFind/src/VuFind/Db/Service/TagServiceInterface.php
  module/VuFind/src/VuFind/Db/Table/Tags.php
  module/VuFind/src/VuFind/Favorites/FavoritesService.php
  module/VuFind/src/VuFind/Favorites/FavoritesServiceFactory.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Favorites/FavoritesServiceTest.php
Labels: architecture

#3777 Deprecate record driver getComments() method.
  module/VuFind/src/VuFind/RecordDriver/AbstractBase.php
  module/VuFind/src/VuFind/View/Helper/Root/Record.php
  themes/bootstrap3/templates/record/comments-list.phtml
  themes/bootstrap5/templates/record/comments-list.phtml
Labels: architecture

#3776 Add markDeleted() to ChangeTrackerService.
  module/VuFind/src/VuFind/Db/Service/ChangeTrackerService.php
  module/VuFind/src/VuFind/Db/Service/ChangeTrackerServiceInterface.php
  module/VuFind/src/VuFind/Solr/Writer.php
  module/VuFind/src/VuFind/Solr/WriterFactory.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Solr/WriterTest.php
Labels: architecture

#3781 Fix: Always retrieve database services by interface.
  module/VuFind/src/VuFind/Bootstrapper.php
  module/VuFind/src/VuFind/Db/Row/PrivateUser.php
  module/VuFind/src/VuFind/Db/Row/UserCard.php
  module/VuFind/src/VuFind/Db/Service/PluginManager.php
Labels: bugfix

#3785 Make unique tag sort unambiguous.
  module/VuFind/src/VuFind/Db/Table/ResourceTags.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/RecordActionsTest.php
Labels: bugfix, tests

#3779 Increase error tolerance: Wikipedia outage shouldn't break author page.
  module/VuFind/src/VuFind/Recommend/AuthorInfo.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AuthorControllerTest.php
Labels: bugfix

#3783 Refactor Favorites search results to use database service
  module/VuFind/src/VuFind/Db/Service/ResourceService.php
  module/VuFind/src/VuFind/Db/Service/ResourceServiceInterface.php
  module/VuFind/src/VuFind/Db/Table/Resource.php
  module/VuFind/src/VuFind/Search/Favorites/Results.php
  module/VuFind/src/VuFind/Search/Favorites/ResultsFactory.php
Labels: architecture

#3784 Refactor createOrUpdateLink() to UserResourceService.
  module/VuFind/src/VuFind/Db/Row/User.php
  module/VuFind/src/VuFind/Db/Service/UserResourceService.php
  module/VuFind/src/VuFind/Db/Service/UserResourceServiceInterface.php
  module/VuFind/src/VuFind/Db/Table/UserResource.php
  module/VuFind/src/VuFind/Favorites/FavoritesService.php
  module/VuFind/src/VuFind/Favorites/FavoritesServiceFactory.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Favorites/FavoritesServiceTest.php
Labels: architecture

#3778 Add integration test for Email authentication.
  build.xml
  module/VuFind/src/VuFind/Auth/Email.php
  module/VuFind/src/VuFindTest/Feature/EmailTrait.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/ChoiceAuthTest.php
Labels: bugfix, tests

#3787 Minor user authentication improvements (follows #3625).
  module/VuFind/src/VuFind/Auth/Email.php
  module/VuFind/src/VuFind/Db/Service/UserService.php
  module/VuFind/src/VuFind/Db/Service/UserServiceInterface.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Auth/DatabaseTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Auth/ILSTest.php
Labels: bugfix

#3774 Refactor user purging to new UserAccountService.
  module/VuFind/config/module.config.php
  module/VuFind/src/VuFind/Account/UserAccountService.php
  module/VuFind/src/VuFind/Account/UserAccountServiceFactory.php
  module/VuFind/src/VuFind/Controller/AlmaController.php
  module/VuFind/src/VuFind/Controller/MyResearchController.php
  module/VuFind/src/VuFind/Db/Row/Resource.php
  module/VuFind/src/VuFind/Db/Row/User.php
  module/VuFind/src/VuFind/Db/Service/ResourceTagsService.php
  module/VuFind/src/VuFind/Db/Service/ResourceTagsServiceInterface.php
  module/VuFind/src/VuFind/Db/Service/UserService.php
  module/VuFind/src/VuFind/Db/Service/UserServiceInterface.php
  module/VuFind/src/VuFind/Db/Table/UserResource.php
  module/VuFind/src/VuFindTest/Feature/LiveDatabaseTrait.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AccountActionsTest.php
Labels: architecture

#3788 Refactor BrowseController tag search to TagService.
  module/VuFind/src/VuFind/Controller/BrowseController.php
  module/VuFind/src/VuFind/Db/Service/TagService.php
  module/VuFind/src/VuFind/Db/Service/TagServiceInterface.php
Labels: architecture

#3789 Eliminate tag table calls from InstallController
  module/VuFind/src/VuFind/Controller/UpgradeController.php
  module/VuFind/src/VuFind/Db/Service/ResourceTagsService.php
  module/VuFind/src/VuFind/Db/Service/ResourceTagsServiceInterface.php
  module/VuFind/src/VuFind/Db/Service/TagService.php
  module/VuFind/src/VuFind/Db/Service/TagServiceInterface.php
  module/VuFind/src/VuFind/Tags.php
Labels: architecture

#3780 Improve method names/terminology -- use record instead of resource.
  module/VuFind/src/VuFind/Db/Service/CommentsService.php
  module/VuFind/src/VuFind/Db/Service/CommentsServiceInterface.php
  module/VuFind/src/VuFind/Db/Service/RatingsService.php
  module/VuFind/src/VuFind/Db/Service/RatingsServiceInterface.php
  module/VuFind/src/VuFind/Ratings/RatingsService.php
  module/VuFind/src/VuFind/RecordDriver/AbstractBase.php
  module/VuFind/src/VuFind/View/Helper/Root/Record.php
Labels: architecture

#3791 Rename \VuFind\Tags to \VuFind\Tags\TagsService.
  module/VuFind/config/module.config.php
  module/VuFind/src/VuFind/AjaxHandler/TagRecord.php
  module/VuFind/src/VuFind/AjaxHandler/TagRecordFactory.php
  module/VuFind/src/VuFind/Controller/AbstractRecord.php
  module/VuFind/src/VuFind/Controller/MyResearchController.php
  module/VuFind/src/VuFind/Controller/UpgradeController.php
  module/VuFind/src/VuFind/Db/Row/UserList.php
  module/VuFind/src/VuFind/Db/Row/UserListFactory.php
  module/VuFind/src/VuFind/Favorites/FavoritesService.php
  module/VuFind/src/VuFind/Favorites/FavoritesServiceFactory.php
  module/VuFind/src/VuFind/RecordDriver/AbstractBase.php
  module/VuFind/src/VuFind/Tags.php
  module/VuFind/src/VuFind/Tags/TagsService.php
  module/VuFind/src/VuFind/Tags/TagsServiceFactory.php
  module/VuFind/src/VuFindTest/Feature/LiveDatabaseTrait.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Favorites/FavoritesServiceTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Tags/TagsServiceTest.php
Labels: architecture

#3714 Add AuthHashService; refactor code to use it.
  module/VuFind/src/VuFind/Auth/EmailAuthenticator.php
  module/VuFind/src/VuFind/Auth/EmailAuthenticatorFactory.php
  module/VuFind/src/VuFind/Db/Service/AuthHashService.php
  module/VuFind/src/VuFind/Db/Service/AuthHashServiceInterface.php
  module/VuFind/src/VuFind/Db/Service/Feature/DeleteExpiredInterface.php
  module/VuFind/src/VuFind/Db/Service/PluginManager.php
  module/VuFind/src/VuFind/Db/Table/PluginManager.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/EmailAuthenticatorTest.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/AbstractExpireCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/ExpireAuthHashesCommandFactory.php
  module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Util/AbstractExpireCommandTest.php
Labels: architecture

#3735 Introduce and use RecordService.
  module/VuFind/src/VuFind/Db/Row/Record.php
  module/VuFind/src/VuFind/Db/Service/PluginManager.php
  module/VuFind/src/VuFind/Db/Service/RecordService.php
  module/VuFind/src/VuFind/Db/Service/RecordServiceInterface.php
  module/VuFind/src/VuFind/Db/Service/ResourceService.php
  module/VuFind/src/VuFind/Db/Service/ResourceServiceInterface.php
  module/VuFind/src/VuFind/Db/Table/Record.php
  module/VuFind/src/VuFind/Record/Cache.php
  module/VuFind/src/VuFind/Record/CacheFactory.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Record/CacheTest.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/CleanUpRecordCacheCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/CleanUpRecordCacheCommandFactory.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/PurgeCachedRecordCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/PurgeCachedRecordCommandFactory.php
  module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Util/CleanUpRecordCacheCommandTest.php
  module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Util/PurgeCachedRecordCommandTest.php
Labels: architecture

#3786 Upgrade PHPUnit to 10.5.20; fix deprecation warnings.
  composer.json
  composer.lock
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordDriver/SolrMarcTest.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/Solr/QueryBuilderTest.php
Labels: tooling

#3795 Improve search table cleanup query.
  module/VuFind/src/VuFind/Db/Service/SearchService.php
Labels: bugfix

#3794 Move source renaming to ResourceService.
  module/VuFind/src/VuFind/Controller/UpgradeController.php
  module/VuFind/src/VuFind/Db/Service/ResourceService.php
  module/VuFind/src/VuFind/Db/Service/ResourceServiceInterface.php
Labels: architecture

#3793 Clarify and refactor tag logic related to linking/unlinking
  module/VuFind/src/VuFind/AjaxHandler/TagRecord.php
  module/VuFind/src/VuFind/Controller/AbstractRecord.php
  module/VuFind/src/VuFind/Db/Row/Resource.php
  module/VuFind/src/VuFind/Db/Row/User.php
  module/VuFind/src/VuFind/Db/Service/ResourceTagsService.php
  module/VuFind/src/VuFind/Db/Service/ResourceTagsServiceInterface.php
  module/VuFind/src/VuFind/Db/Table/UserResource.php
  module/VuFind/src/VuFind/Favorites/FavoritesService.php
  module/VuFind/src/VuFind/RecordDriver/AbstractBase.php
  module/VuFind/src/VuFind/Tags/TagsService.php
Labels: architecture

#3796 Update dev dependencies (php-jwt, phpstan, php_codesniffer)
  composer.json
  composer.lock
Labels: dependencies

#3749 Introduce and use ShortlinksService
  module/VuFind/src/VuFind/Controller/UpgradeController.php
  module/VuFind/src/VuFind/Db/Service/Feature/TransactionInterface.php
  module/VuFind/src/VuFind/Db/Service/PluginManager.php
  module/VuFind/src/VuFind/Db/Service/ShortlinksService.php
  module/VuFind/src/VuFind/Db/Service/ShortlinksServiceInterface.php
  module/VuFind/src/VuFind/UrlShortener/Database.php
  module/VuFind/src/VuFind/UrlShortener/DatabaseFactory.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/UrlShortenerTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/UrlShortener/DatabaseTest.php
Labels: architecture

#3768 Simplify return type of \VuFind\Controller\AbstractBase::getUser()
  module/VuFind/src/VuFind/Controller/AbstractBase.php
  module/VuFind/src/VuFind/Controller/AbstractSearch.php
  module/VuFind/src/VuFind/Controller/FeedbackController.php
  module/VuFind/src/VuFind/Controller/MyResearchController.php
  module/VuFind/src/VuFind/Controller/SearchController.php
Labels: architecture

#3801 Minor improvements to UpgradeController.
  module/VuFind/src/VuFind/Controller/UpgradeController.php
Labels: improvement

#3802 Replace deprecated method calls in Favorites search Results class.
  module/VuFind/src/VuFind/Search/Favorites/Results.php
  module/VuFind/src/VuFind/Search/Favorites/ResultsFactory.php
Labels: architecture

#3790 Fix favorites multi-select-list storage cleanup after deleting items from lists
  themes/bootstrap3/js/list_item_selection.js
  themes/bootstrap5/js/list_item_selection.js
Labels: bugfix

#3805 Clean up outdated row references in VuFind module.
  module/VuFind/src/VuFind/AjaxHandler/GetSaveStatuses.php
  module/VuFind/src/VuFind/Auth/LoginTokenManager.php
  module/VuFind/src/VuFind/Controller/AlmaController.php
  module/VuFind/src/VuFind/Favorites/FavoritesService.php
  module/VuFind/src/VuFind/RecordDriver/AbstractBase.php
  module/VuFind/src/VuFind/View/Helper/Root/AccountMenu.php
  module/VuFind/src/VuFind/View/Helper/Root/Auth.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/DatabaseUnitTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/ILSAuthenticatorTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/LoginTokenManagerTest.php
Labels: architecture

#3806 Finish updating SwitchDbHashCommand to use database services
  module/VuFind/src/VuFind/Db/Service/UserService.php
  module/VuFind/src/VuFind/Db/Service/UserServiceInterface.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/SwitchDbHashCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/SwitchDbHashCommandFactory.php
  module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Util/SwitchDbHashCommandTest.php
Labels: architecture

#3808 Make tag faceting test pass in PostgreSQL as well as MySQL.
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/FavoritesTest.php
Labels: bugfix, tests

#3807 Refactor favorite and user list tag unlinking.
  module/VuFind/src/VuFind/Db/Service/ResourceService.php
  module/VuFind/src/VuFind/Db/Service/ResourceTagsService.php
  module/VuFind/src/VuFind/Db/Service/ResourceTagsServiceInterface.php
  module/VuFind/src/VuFind/Db/Service/ShortlinksService.php
  module/VuFind/src/VuFind/Db/Service/UserResourceService.php
  module/VuFind/src/VuFind/Db/Service/UserResourceServiceInterface.php
  module/VuFind/src/VuFind/Db/Table/Gateway.php
  module/VuFind/src/VuFind/Db/Table/ResourceTags.php
  module/VuFind/src/VuFind/Db/Table/UserResource.php
  module/VuFind/src/VuFind/Favorites/FavoritesService.php
  module/VuFind/src/VuFind/Tags/TagsService.php
  module/VuFind/src/VuFindTest/Feature/LiveDatabaseTrait.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Favorites/FavoritesServiceTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Tags/TagsServiceTest.php
Labels: architecture

#3810 Minor improvements to FavoritesService.
  module/VuFind/src/VuFind/Favorites/FavoritesService.php
Labels: improvement

#3811 Eliminate remaining controller references to getTable().
  module/VuFind/src/VuFind/Controller/AlmaController.php
  module/VuFind/src/VuFind/Controller/Feature/SecureDatabaseTrait.php
  module/VuFind/src/VuFind/Controller/InstallController.php
  module/VuFind/src/VuFind/Controller/MyResearchController.php
  module/VuFind/src/VuFind/Controller/UpgradeController.php
  module/VuFind/src/VuFind/Db/Service/UserService.php
  module/VuFind/src/VuFind/Db/Service/UserServiceInterface.php
Labels: architecture

#3799 OverDrive: Fix incorrect translation string in status-full.phtml.
  themes/bootstrap3/templates/RecordDriver/SolrOverdrive/status-full.phtml
  themes/bootstrap5/templates/RecordDriver/SolrOverdrive/status-full.phtml
Labels: bugfix

#3813 More UserEntityInterface improvements to AlmaController.
  module/VuFind/src/VuFind/Controller/AlmaController.php
Labels: architecture

#3812 Use UserEntityInterface on new password form.
  module/VuFind/src/VuFind/Controller/MyResearchController.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AccountActionsTest.php
  themes/bootstrap3/templates/Auth/AbstractBase/login.phtml
  themes/bootstrap5/templates/Auth/AbstractBase/login.phtml
Labels: bugfix

#3814 Index email and verify_hash fields in user table.
  module/VuFind/sql/migrations/pgsql/10.0/003-add-user-indexes.sql
  module/VuFind/sql/mysql.sql
  module/VuFind/sql/pgsql.sql
Labels: improvement

#3817 Extract Solr directly to the vendor directory.
  build.xml
Labels: tooling

#3816 [VUFIND-1351] Add email verification test.
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/EmailVerificationTest.php
Labels: tests

#3818 Improve translation key escaping to improve Lokalise compatibility.
  languages/ISO639-3/ar.ini
  languages/ISO639-3/de.ini
  languages/ISO639-3/en.ini
  languages/ISO639-3/fi.ini
  languages/ISO639-3/ga.ini
  languages/ISO639-3/hy.ini
  languages/ISO639-3/it.ini
  languages/ISO639-3/mn.ini
  languages/ISO639-3/pt-br.ini
  languages/ISO639-3/se.ini
  languages/ISO639-3/sv.ini
  languages/ISO639-3/tr.ini
  module/VuFind/src/VuFind/I18n/ExtendedIniNormalizer.php
  module/VuFind/src/VuFind/I18n/Translator/TranslatorAwareTrait.php
Labels: bugfix

#3744 Define two example ILL strings in en.ini
  languages/ILSMessages/en.ini
Labels: new language strings

#3422 KohaRest: Show recalled message if a recall is blocking renewal
  languages/ILSMessages/en.ini
  module/VuFind/src/VuFind/ILS/Driver/KohaRest.php
Labels: new language strings

#3740 Support extra status information in availability status handling
  config/vufind/Demo.ini
  languages/HoldingStatus/de.ini
  languages/HoldingStatus/en.ini
  module/VuFind/src/VuFind/ILS/Driver/Demo.php
  module/VuFind/src/VuFind/ILS/Logic/AvailabilityStatus.php
  module/VuFind/src/VuFind/ILS/Logic/AvailabilityStatusInterface.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/HoldingsTest.php
  themes/bootstrap3/templates/RecordTab/holdingsils/electronic.phtml
  themes/bootstrap3/templates/RecordTab/holdingsils/extended.phtml
  themes/bootstrap3/templates/RecordTab/holdingsils/standard.phtml
  themes/bootstrap3/templates/ajax/status-full.phtml
  themes/bootstrap5/templates/RecordTab/holdingsils/electronic.phtml
  themes/bootstrap5/templates/RecordTab/holdingsils/extended.phtml
  themes/bootstrap5/templates/RecordTab/holdingsils/standard.phtml
  themes/bootstrap5/templates/ajax/status-full.phtml
Labels: new language strings

#3819 Fix bug: Explain broke mixed-AJAX combined search.
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/CombinedSearchTest.php
  themes/bootstrap3/js/explain.js
  themes/bootstrap5/js/explain.js
Labels: bugfix
