Repository vufind-org/vufind, pull requests merged in 2024-02, with the labels that each got.

#3375 KohaRest: Add and fix renewal block reason translations.
  languages/ILSMessages/en.ini
  languages/ILSMessages/fi.ini
  languages/ILSMessages/sv.ini
  module/VuFind/src/VuFind/ILS/Driver/KohaRest.php
Labels: bugfix

#3374 Mock LoggerInterface instead of Logger for more stable tests.
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/MultiAuthTest.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/Blender/BackendTest.php
Labels: tests

#3378 Mink tests: remove AutoRetryTrait.
  module/VuFind/src/VuFindTest/Feature/AutoRetryTrait.php
  module/VuFind/src/VuFindTest/Integration/MinkTestCase.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AccountActionsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AccountMenuTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AdvancedSearchTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AlphabrowseTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/ApiTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AuthorControllerTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AuthorSearchTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AutocompleteTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/BasicSearchTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/BasicTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/BlendedSearchTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/BulkTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/CallnumberBrowseTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/CartTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/ChannelsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/ChoiceAuthTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/CollectionsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/CombinedSearchTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/CookieConsentTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/ExplainTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/FavoritesTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/FeedbackTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/HoldingsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/HoldsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/HomePageFacetsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/IlsActionsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/JumpToRecordTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/LibraryCardsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/LinkResolverTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/ListViewsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/MarkdownTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/NextPrevNavTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/OAuth2Test.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/RecordActionsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/RecordTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/RecordVersionsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SavedSearchesTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchFacetsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchLimitTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchSortTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchViewsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/ShibbolethLogoutNotificationTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SsoTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/VisualizationTest.php
Labels: tests

#3379 Only proxy images through cover proxy.
  module/VuFind/src/VuFind/Controller/CoverController.php
Labels: bugfix

#3380 Use PHP8 attribute to toggle HTML validation in tests.
  module/VuFind/src/VuFindTest/Attribute/HtmlValidation.php
  module/VuFind/src/VuFindTest/Integration/MinkTestCase.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/ListViewsTest.php
Labels: tests

#3385 Restrict hostnames for cover proxy.
  config/vufind/config.ini
  module/VuFind/src/VuFind/Controller/CoverController.php
  module/VuFind/src/VuFind/Controller/CoverControllerFactory.php
Labels: improvement

#3314 Upgrade to PHPUnit 10.
  build.xml
  composer.json
  composer.lock
  module/VuFind/src/VuFind/Search/Base/Options.php
  module/VuFind/src/VuFindTest/Feature/LiveDatabaseTrait.php
  module/VuFind/src/VuFindTest/Feature/WithConsecutiveTrait.php
  module/VuFind/src/VuFindTest/Integration/MinkTestCase.php
  module/VuFind/tests/phpunit.xml
Labels: tooling

#3386 Revert bad changes from #3383.
  module/VuFind/src/VuFindTest/Integration/MinkTestCase.php
Labels: tests

#3382 AbstractAPI: use status instead of code to capture HTTP status.
  module/VuFind/src/VuFind/ILS/Driver/AbstractAPI.php
  module/VuFind/tests/fixtures/folio/responses/get-holding-checkedout.json
  module/VuFind/tests/fixtures/folio/responses/get-holding-empty-statements.json
  module/VuFind/tests/fixtures/folio/responses/get-holding-multi-volume.json
  module/VuFind/tests/fixtures/folio/responses/get-holding-sorted.json
  module/VuFind/tests/fixtures/folio/responses/get-holding.json
  module/VuFind/tests/fixtures/folio/responses/successful-place-hold-legacy.json
  module/VuFind/tests/fixtures/folio/responses/successful-place-hold-no-expiration-date.json
  module/VuFind/tests/fixtures/folio/responses/successful-place-hold.json
  module/VuFind/tests/fixtures/folio/responses/unsuccessful-place-hold.json
Labels: bugfix, tests

#3355 FOLIO: smarter handling of request types in placeHold.
  config/vufind/Folio.ini
  module/VuFind/src/VuFind/ILS/Driver/Folio.php
  module/VuFind/tests/fixtures/folio/responses/request-type-fallback.json
  module/VuFind/tests/fixtures/folio/responses/successful-place-hold-legacy.json
  module/VuFind/tests/fixtures/folio/responses/successful-place-hold-no-expiration-date.json
  module/VuFind/tests/fixtures/folio/responses/successful-place-hold.json
  module/VuFind/tests/fixtures/folio/responses/unsuccessful-place-hold.json
  module/VuFind/tests/unit-tests/src/VuFindTest/ILS/Driver/FolioTest.php
Labels: improvement

#3390 Use a callback in ILSAuthenticator to get Auth Manager.
  module/VuFind/src/VuFind/Auth/ILSAuthenticator.php
  module/VuFind/src/VuFind/Auth/ILSAuthenticatorFactory.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AccountActionsTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/ILSAuthenticatorTest.php
Labels: bugfix

#3389 Fix showMessage deniedControllerBehavior setting.
  module/VuFind/src/VuFind/Controller/AbstractBase.php
  module/VuFind/src/VuFind/Controller/AbstractBaseFactory.php
  module/VuFind/src/VuFind/Controller/Feature/AccessPermissionInterface.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/PermissionsTest.php
Labels: bugfix

#3394 Fix parameter type annotation in GetFieldValueFixTrait.
  module/VuFind/src/VuFind/Mailer/GetFieldValueFixTrait.php
Labels: bugfix

#3396 Update node version in GitHub actions; v16 is deprecated.
  .github/workflows/ci.yaml
Labels: tooling

#3403 Update development tools; apply minor return type annotation fix.
  composer.json
  composer.lock
  module/VuFindAdmin/src/VuFindAdmin/Controller/FeedbackController.php
Labels: tooling

#3405 [9.1] Fix stray closing spans in checkout history.
  themes/bootstrap3/templates/checkouts/history.phtml
Labels: bugfix

#3406 Mink: Add methods for getting element data.
  module/VuFind/src/VuFindTest/Integration/MinkTestCase.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AccountActionsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AdvancedSearchTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AlphabrowseTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/ApiTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AuthorControllerTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AuthorSearchTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AutocompleteTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/BasicSearchTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/BasicTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/BlendedSearchTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/BulkTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/CartTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/ChannelsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/ChoiceAuthTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/CollectionsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/CombinedSearchTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/ExplainTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/FavoritesTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/FeedbackTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/HoldingsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/HoldsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/HomePageFacetsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/IlsActionsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/JumpToRecordTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/LibraryCardsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/MarkdownTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/NextPrevNavTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/OAuth2Test.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/PermissionsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/RecordActionsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/RecordTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/RecordVersionsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SavedSearchesTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchFacetsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchLimitTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchViewsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SsoTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/VisualizationTest.php
Labels: tests

#3391 Refactor pagination controls.
  module/VuFind/src/VuFind/Config/Feature/ExplodeSettingTrait.php
  module/VuFind/src/VuFind/Search/EDS/Options.php
  module/VuFind/src/VuFind/Search/Favorites/Options.php
  module/VuFind/src/VuFind/Search/LibGuides/Options.php
  module/VuFind/src/VuFind/Search/Primo/Options.php
  module/VuFind/src/VuFind/Search/Solr/Options.php
  module/VuFind/src/VuFind/Search/Summon/Options.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchLimitTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchSortTest.php
  themes/bootprint3/css/compiled.css
  themes/bootprint3/less/common.less
  themes/bootprint3/less/variables.less
  themes/bootprint3/scss/common.scss
  themes/bootprint3/scss/variables.scss
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/bootstrap.less
  themes/bootstrap3/less/components/search.less
  themes/bootstrap3/less/variables.less
  themes/bootstrap3/scss/bootstrap.scss
  themes/bootstrap3/scss/components/search.scss
  themes/bootstrap3/scss/variables.scss
  themes/bootstrap3/templates/Helpers/pagination-item.phtml
  themes/bootstrap3/templates/Helpers/pagination.phtml
  themes/bootstrap3/templates/search/pagination-item.phtml
  themes/bootstrap3/templates/search/pagination.phtml
  themes/bootstrap3/templates/search/pagination_simple.phtml
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal/less/common.less
  themes/sandal/scss/common.scss
Labels: improvement

#3408 Fix extra elements being added to pagination etc. when paging results.
  module/VuFind/src/VuFind/AjaxHandler/GetSearchResults.php
  themes/bootstrap3/js/search.js
  themes/bootstrap3/templates/search/pagination-top.phtml
  themes/bootstrap3/templates/search/pagination.phtml
  themes/bootstrap3/templates/search/results.phtml
Labels: bugfix

#3411 Use regex route for content pages
  module/VuFind/config/module.config.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/ContentControllerTest.php
Labels: improvement

#3414 Simplify Mink tests with support methods.
  module/VuFind/src/VuFindTest/Feature/AutocompleteTrait.php
  module/VuFind/src/VuFindTest/Integration/MinkTestCase.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AutocompleteTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/BasicTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/FavoritesTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/HomePageFacetsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/LinkResolverTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/ListViewsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/RecordActionsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchViewsTest.php
Labels: tests

#3419 Update yajra/laravel-pdo-via-oci8 to 3.4.2.
  composer.json
  composer.lock
Labels: improvement, tooling

#3420 Turn on cache for PHP_CodeSniffer.
  .github/workflows/ci.yaml
  .gitignore
  build.xml
Labels: tooling

#3426 Add "composer fix" to run php-cs-fixer and phpcbf.
  build.xml
  composer.json
Labels: tooling

#3417 Improve YAML merging by refactoring logic from ThemeInfo
  module/VuFind/src/VuFind/Config/YamlReader.php
  module/VuFind/src/VuFind/Feature/BulkActionTrait.php
  module/VuFind/src/VuFind/Feature/MergeRecursiveTrait.php
  module/VuFind/tests/fixtures/configs/yaml/config/vufind/yamlreader-child.yaml
  module/VuFind/tests/fixtures/configs/yaml/config/vufind/yamlreader-parent.yaml
  module/VuFind/tests/unit-tests/src/VuFindTest/Config/YamlReaderTest.php
  module/VuFindTheme/src/VuFindTheme/ThemeInfo.php
  module/VuFindTheme/tests/unit-tests/src/VuFindTest/ThemeInfoTest.php
Labels: improvement, architecture, small

#3431 Fix merge recursive for boolean values
  module/VuFind/src/VuFind/Feature/MergeRecursiveTrait.php
  module/VuFind/tests/fixtures/configs/yaml/config/vufind/yamlreader-child.yaml
  module/VuFind/tests/fixtures/configs/yaml/config/vufind/yamlreader-parent.yaml
  module/VuFind/tests/unit-tests/src/VuFindTest/Config/YamlReaderTest.php
Labels: bugfix

#3433 Updated laminas-recaptcha to 3.7.0
  composer.json
  composer.lock
Labels: dependencies

#3427 Fix sorting of favorites.
  module/VuFind/src/VuFind/Db/Row/Tags.php
  module/VuFind/src/VuFind/Db/Table/Resource.php
  module/VuFind/src/VuFind/Db/Table/Tags.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/FavoritesTest.php
Labels: bugfix

#3434 Improve logger initialization process.
  module/VuFind/src/VuFind/Log/Logger.php
  module/VuFind/src/VuFind/Log/LoggerFactory.php
Labels: bugfix

#3294 Updated loadHTML from jQuery to native Javascript
  themes/bootstrap3/js/combined-search.js
  themes/bootstrap3/js/common.js
  themes/bootstrap3/templates/Recommend/AbstractSearchObjectDeferred.phtml
  themes/bootstrap3/templates/combined/results-ajax.phtml
Labels: improvement, small

#3438 Add persistent login token to cookie consent.
  config/vufind/CookieConsent.yaml
  config/vufind/config.ini
  languages/CookieConsent/en.ini
  languages/CookieConsent/fi.ini
  languages/CookieConsent/sv.ini
  module/VuFind/src/VuFind/Auth/LoginTokenManager.php
  module/VuFind/src/VuFind/Cookie/CookieManager.php
  module/VuFind/src/VuFind/View/Helper/Root/CookieConsent.php
  module/VuFind/src/VuFind/View/Helper/Root/CookieConsentFactory.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/CookieConsentTest.php
Labels: improvement

#3437 Clarify PermissionManager method signatures
  module/VuFind/src/VuFind/Role/PermissionManager.php
Labels: improvement

#3439 Favorite sort test stability
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/FavoritesTest.php
Labels: tests

#3440 Use SSL to download Solr.
  build.xml
Labels: tooling

#3447 Fix setElementContents with outerHTML.
  themes/bootstrap3/js/common.js
Labels: bugfix

#2991 Add filtering capability to facet list pop-up
  config/vufind/facets.ini
  module/VuFind/src/VuFind/Controller/AbstractSearch.php
  module/VuFind/src/VuFind/Search/Base/Params.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchFacetsTest.php
  themes/bootstrap3/js/facets.js
  themes/bootstrap3/templates/search/facet-list-content.phtml
  themes/bootstrap3/templates/search/facet-list.phtml
Labels: new feature

#3413 Autocomplete: Fix Showing After Unfocus
  themes/bootstrap3/js/vendor/autocomplete.js
  themes/bootstrap3/package.json
Labels: bugfix

#3428 Convert all text to B&W in print view.
  themes/bootstrap3/css/print.css
Labels: bugfix

#3449 Add default_test_timeout Phing property.
  build.xml
Labels: tests

#3450 Minor improvements to SimilarCommandTest.
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Command/SimilarCommandTest.php
Labels: tests

#3381 fix: don't override toggleAttrs in menu-button.
  themes/bootstrap3/templates/_ui/components/menu-button.phtml
Labels: bugfix

#3451 FOLIO: make holdingsRecordId and itemID optional in getMyHoldings
  module/VuFind/src/VuFind/ILS/Driver/Folio.php
Labels: improvement

#3142 Multi page selection in favorite list
  config/vufind/config.ini
  languages/de.ini
  languages/en.ini
  module/VuFind/src/VuFind/Controller/CartController.php
  module/VuFind/src/VuFind/Controller/Feature/ListItemSelectionTrait.php
  module/VuFind/src/VuFind/Controller/MyResearchController.php
  module/VuFind/src/VuFind/Search/Favorites/Results.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/ListItemSelectionTest.php
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/js/cart.js
  themes/bootstrap3/js/common.js
  themes/bootstrap3/js/list_item_selection.js
  themes/bootstrap3/js/requests.js
  themes/bootstrap3/less/components/search.less
  themes/bootstrap3/scss/components/search.scss
  themes/bootstrap3/templates/checkouts/history.phtml
  themes/bootstrap3/templates/layout/js-translations.phtml
  themes/bootstrap3/templates/myresearch/bulk-action-buttons.phtml
  themes/bootstrap3/templates/myresearch/mylist.phtml
  themes/bootstrap3/templates/search/bulk-action-buttons.phtml
  themes/bootstrap3/theme.config.php
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal/less/search.less
  themes/sandal/scss/search.scss
Labels: improvement

#3393 Add support for Primo citations search.
  config/vufind/Primo.ini
  languages/en.ini
  languages/fi.ini
  languages/sv.ini
  module/VuFind/config/module.config.php
  module/VuFind/src/VuFind/Controller/PrimoController.php
  module/VuFind/src/VuFind/RecordDriver/Primo.php
  module/VuFind/src/VuFind/Search/Base/Options.php
  module/VuFind/src/VuFind/Search/Primo/Options.php
  module/VuFind/src/VuFind/Search/Primo/Params.php
  module/VuFind/src/VuFind/View/Helper/Root/RecordDataFormatterFactory.php
  module/VuFindSearch/src/VuFindSearch/Backend/Primo/Connector.php
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/components/search.less
  themes/bootstrap3/scss/components/search.scss
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/data-citations.phtml
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/link-citedBy.phtml
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/link-cites.phtml
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/list-entry.phtml
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/result-list.phtml
  themes/bootstrap3/templates/primo/citation_results.phtml
  themes/bootstrap3/templates/primo/citedby.phtml
  themes/bootstrap3/templates/primo/cites.phtml
  themes/bootstrap3/templates/record/view.phtml
  themes/bootstrap3/templates/search/no-input-searchbox.phtml
  themes/bootstrap3/templates/search/results.phtml
  themes/bootstrap3/templates/search/versions-searchbox.phtml
  themes/bootstrap3/theme.config.php
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
Labels: new feature

#3455 HeadLink helper: Fix invalid types in doc comments.
  module/VuFindTheme/src/VuFindTheme/View/Helper/HeadLink.php
Labels: bugfix
