Repository vufind-org/vufind, pull requests merged in 2025-03, with the labels that each got.

#4277 Expand/modernize test for VuFind\Config\PluginFactory
  module/VuFind/tests/fixtures/configs/inheritance/unit-test-parent.ini
  module/VuFind/tests/unit-tests/src/VuFindTest/Config/PluginFactoryTest.php
Labels: tests

#4279 Move firebase/php-jwt to normal dependencies.
  composer.json
  composer.lock
Labels: bugfix, dependencies

#4225 Add option to use resumptionToken in REST
  config/vufind/searches.ini
  module/VuFind/sql/migrations/pgsql/11.0/002-modify-oai-resumption-columns.sql
  module/VuFind/sql/mysql.sql
  module/VuFind/sql/pgsql.sql
  module/VuFind/src/VuFind/Db/Entity/OaiResumptionEntityInterface.php
  module/VuFind/src/VuFind/Db/Row/OaiResumption.php
  module/VuFind/src/VuFind/Db/Service/AbstractDbService.php
  module/VuFind/src/VuFind/Db/Service/OaiResumptionService.php
  module/VuFind/src/VuFind/Db/Service/OaiResumptionServiceInterface.php
  module/VuFind/src/VuFind/Db/Table/OaiResumption.php
  module/VuFind/src/VuFind/OAI/Server.php
  module/VuFind/src/VuFind/ResumptionToken/ResumptionTokenTrait.php
  module/VuFind/src/VuFind/Search/SearchRunner.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Db/Service/OaiResumptionServiceTest.php
  module/VuFindApi/src/VuFindApi/Controller/ApiException.php
  module/VuFindApi/src/VuFindApi/Controller/SearchApiController.php
  themes/root/templates/searchapi/openapi.phtml
Labels: new feature

#4280 Fix some issues in the OpenID Connect client.
  module/VuFind/src/VuFind/Auth/OpenIDConnect.php
Labels: improvement

#4109 Multi facet selection - Record last user state
  module/VuFind/src/VuFindTest/Feature/SearchFacetFilterTrait.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchFacetsTest.php
  themes/bootstrap5/js/facets.js
Labels: improvement

#4286 Remove Solr v3 error listener.
  module/VuFind/src/VuFind/Search/Factory/AbstractSolrBackendFactory.php
  module/VuFind/src/VuFind/Search/SearchRunner.php
  module/VuFind/src/VuFind/Search/Solr/AbstractErrorListener.php
  module/VuFind/src/VuFind/Search/Solr/ErrorListener.php
  module/VuFind/src/VuFind/Search/Solr/Results.php
  module/VuFind/src/VuFind/Search/Solr/V3/ErrorListener.php
  module/VuFind/tests/fixtures/response/solr/solr3-alphabrowse-error
  module/VuFind/tests/fixtures/response/solr/solr3-parse-error
  module/VuFind/tests/fixtures/response/solr/solr3-undefined-field-error
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/Solr/ErrorListenerTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/Solr/V4/ErrorListenerTest.php
Labels: architecture

#4290 Remove AddThis support; service was discontinued in 2023.
  config/vufind/config.ini
  module/VuFind/src/VuFind/View/Helper/Root/AddThis.php
  module/VuFind/src/VuFind/View/Helper/Root/AddThisFactory.php
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/toolbar.phtml
  themes/bootstrap5/theme.config.php
  themes/root/theme.config.php
Labels: small

#4296 Fix search-filter-dropdown button icon
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/scss/components/search.scss
  themes/bootstrap5/templates/search/filters.phtml
  themes/local_theme_example/css/compiled.css
  themes/sandal5/css/compiled.css
Labels: bugfix

#4292 Add Solr account handling and clean up output of deb package
  build.xml
  module/VuFindConsole/src/VuFindConsole/Command/Install/InstallCommand.php
  module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Install/InstallCommandTest.php
  packages/DEBIAN/config
  packages/DEBIAN/postinst
  packages/DEBIAN/postrm
  packages/DEBIAN/templates
Labels: tooling

#4298 Fix bug: delete language command incompatible with single-quotes
  module/VuFindConsole/src/VuFindConsole/Command/Language/DeleteCommand.php
  module/VuFindConsole/tests/fixtures/language/foo-quoted/en.ini
  module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Language/DeleteCommandTest.php
Labels: bugfix

#4299 Configuration upgrade fixes.
  module/VuFind/src/VuFind/Config/Upgrade.php
  module/VuFind/src/VuFind/Controller/UpgradeController.php
  module/VuFind/tests/fixtures/configs/database-both-formats/config.ini
  module/VuFind/tests/fixtures/configs/database-legacy-format/config.ini
  module/VuFind/tests/fixtures/configs/database-new-format-password-file/config.ini
  module/VuFind/tests/fixtures/configs/database-new-format/config.ini
  module/VuFind/tests/unit-tests/src/VuFindTest/Config/UpgradeTest.php
Labels: bugfix

#4300 Fix the reset search button to reset only the text input and not the dropdown
  themes/bootstrap5/js/searchbox_controls.js
  themes/bootstrap5/templates/search/searchbox.phtml
Labels: improvement

#4301 Fix bug: prevent undefined variable.
  themes/bootstrap3/templates/search/filters.phtml
  themes/bootstrap5/templates/search/filters.phtml
Labels: bugfix

#4304 Ensure that back-compatible logic is commented with the word "legacy"
  module/VuFind/src/VuFind/AjaxHandler/IdentifierLinksLookup.php
  module/VuFind/src/VuFind/Cache/Manager.php
  module/VuFind/src/VuFind/Cart.php
  module/VuFind/src/VuFind/Content/Covers/Deprecated.php
  module/VuFind/src/VuFind/Content/Deprecated.php
  module/VuFind/src/VuFind/Controller/AbstractBase.php
  module/VuFind/src/VuFind/Controller/HoldsTrait.php
  module/VuFind/src/VuFind/Controller/ILLRequestsTrait.php
  module/VuFind/src/VuFind/Controller/MyResearchController.php
  module/VuFind/src/VuFind/Controller/Plugin/Holds.php
  module/VuFind/src/VuFind/Controller/StorageRetrievalRequestsTrait.php
  module/VuFind/src/VuFind/Hierarchy/TreeRenderer/PluginManager.php
  module/VuFind/src/VuFind/ILS/Connection.php
  module/VuFind/src/VuFind/ILS/Driver/Alma.php
  module/VuFind/src/VuFind/ILS/Driver/Folio.php
  module/VuFind/src/VuFind/ILS/Driver/Unicorn.php
  module/VuFind/src/VuFind/ILS/Logic/Holds.php
  module/VuFind/src/VuFind/IdentifierLinker/BrowZineFactory.php
  module/VuFind/src/VuFind/Navigation/AccountMenu.php
  module/VuFind/src/VuFind/Search/Base/Params.php
  module/VuFind/src/VuFind/Search/QueryAdapter.php
  module/VuFind/src/VuFind/Search/Solr/HierarchicalFacetHelper.php
  module/VuFind/src/VuFind/View/Helper/Root/AccountMenu.php
  module/VuFind/src/VuFind/View/Helper/Root/GoogleAnalytics.php
  module/VuFind/src/VuFind/View/Helper/Root/IdentifierLinkerFactory.php
  module/VuFind/src/VuFind/View/Helper/Root/Piwik.php
  module/VuFind/src/VuFind/View/Helper/Root/RecordDataFormatterFactory.php
  module/VuFindSearch/src/VuFindSearch/Backend/Solr/Connector.php
  module/VuFindSearch/src/VuFindSearch/Feature/SearchBackendEventManagerTrait.php
  themes/bootstrap5/templates/RecordTab/holdingsils.phtml
  themes/bootstrap5/theme.config.php
Labels: documentation

#4310 Optionally allow unicode in api
  module/VuFindApi/src/VuFindApi/Controller/ApiTrait.php
Labels: improvement

#4311 Hide edit actions on public favorite list entries
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/list-entry.phtml
Labels: bugfix
