Repository vufind-org/vufind, pull requests merged in 2025-01, with the labels that each got.

#4177 Remove useless and invalid pagination color overrides.
  themes/bootstrap3/less/variables.less
  themes/bootstrap3/scss/variables.scss
  themes/bootstrap5/scss/bootstrap-variable-overrides.scss
  themes/bootstrap5/scss/variables.scss
Labels: bugfix

#4176 Apply BS3 data attribute mappings to added child elements too.
  themes/bootstrap5/js/bs3-compat.js
Labels: improvement

#4180 Fix broken combined search jump menu.
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/CombinedSearchTest.php
  themes/bootstrap3/templates/combined/results-list.phtml
  themes/bootstrap5/templates/combined/results-list.phtml
Labels: bugfix

#4182 Fix setElementContents for outerHTML
  themes/bootstrap3/js/common.js
  themes/bootstrap5/js/common.js
Labels: bugfix

#4184 Add label translations for EDS
  languages/de.ini
  languages/en.ini
Labels: new language strings

#4188 Fix bug: multi-select search confused by non-canonicalized array query parameters
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchFacetsTest.php
  themes/bootstrap3/js/facets.js
  themes/bootstrap5/js/facets.js
Labels: bugfix

#4064 RateLimiter: Allow grouping of IP addresses to share a quota
  config/vufind/RateLimiter.yaml
  module/VuFind/src/VuFind/Net/IpAddressUtils.php
  module/VuFind/src/VuFind/RateLimiter/RateLimiterManagerFactory.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Net/IpAddressUtilsTest.php
Labels: new feature

#4198 Fix limit options for EDS if unset
  module/VuFind/src/VuFind/Search/Base/Options.php
Labels: bugfix

#4181 Combined jump links: configurable linking modes
  config/vufind/combined.ini
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/CombinedSearchTest.php
  themes/bootstrap3/templates/combined/jump-links.phtml
  themes/bootstrap3/templates/combined/results-list.phtml
  themes/bootstrap3/templates/combined/results.phtml
  themes/bootstrap5/templates/combined/jump-links.phtml
  themes/bootstrap5/templates/combined/results-list.phtml
  themes/bootstrap5/templates/combined/results.phtml
Labels: new feature

#4190 Prevent "new item" hidden filters from bleeding beyond scope
  module/VuFind/src/VuFind/Controller/SearchController.php
  module/VuFind/src/VuFind/Search/Base/Params.php
  module/VuFind/src/VuFind/Search/UrlQueryHelper.php
  module/VuFind/src/VuFind/View/Helper/Root/SearchTabs.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/NewItemsTest.php
  themes/bootstrap3/templates/search/home.phtml
  themes/bootstrap3/templates/search/results.phtml
  themes/bootstrap3/templates/search/searchbox.phtml
  themes/bootstrap5/templates/search/home.phtml
  themes/bootstrap5/templates/search/results.phtml
  themes/bootstrap5/templates/search/searchbox.phtml
Labels: bugfix

#4178 Add Mink test for fallback loader functionality.
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/FallbackLoaderTest.php
Labels: tests

#4191 Use better indexes in login_token table.
  module/VuFind/sql/migrations/pgsql/11.0/001-modify-login-token-indexes.sql
  module/VuFind/sql/mysql.sql
  module/VuFind/sql/pgsql.sql
Labels: improvement

#4194 Fix broken admin theme option
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AdminTest.php
  module/VuFindTheme/src/VuFindTheme/Initializer.php
Labels: bugfix

#4203 Fix checkbox facet duplication multi-select facet bug
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchFacetsTest.php
  themes/bootstrap3/js/facets.js
  themes/bootstrap5/js/facets.js
Labels: bugfix

#4179 Remove direct dependency on laminas/laminas-text.
  composer.json
  composer.lock
Labels: dependencies

#4206 Style: add missing semi-colons to generated JS code.
  themes/bootstrap3/templates/layout/layout.phtml
  themes/bootstrap5/templates/layout/layout.phtml
Labels: bugfix

#4207 Simplify/reduce config.ini test fixtures.
  module/VuFind/tests/fixtures/configs/amazoncover/config.ini
  module/VuFind/tests/fixtures/configs/amazonreview/config.ini
  module/VuFind/tests/fixtures/configs/recaptcha/config.ini
Labels: tests

#4208 Adding restricted view warning for EDS
  config/vufind/EDS.ini
  languages/de.ini
  languages/en.ini
  module/VuFind/src/VuFind/Search/Base/Options.php
  module/VuFind/src/VuFind/Search/Base/Results.php
  module/VuFind/src/VuFind/Search/EDS/Results.php
  module/VuFindSearch/src/VuFindSearch/Backend/EDS/Backend.php
  module/VuFindSearch/src/VuFindSearch/Backend/EDS/Response/RecordCollection.php
  themes/bootstrap3/templates/RecordDriver/EDS/core.phtml
  themes/bootstrap3/templates/RecordDriver/EDS/result-list.phtml
  themes/bootstrap3/templates/combined/results-list.phtml
  themes/bootstrap3/templates/error/loginForAccess.phtml
  themes/bootstrap3/templates/error/restrictedViewWarning.phtml
  themes/bootstrap3/templates/search/results.phtml
  themes/bootstrap5/templates/RecordDriver/EDS/core.phtml
  themes/bootstrap5/templates/RecordDriver/EDS/result-list.phtml
  themes/bootstrap5/templates/combined/results-list.phtml
  themes/bootstrap5/templates/error/loginForAccess.phtml
  themes/bootstrap5/templates/error/restrictedViewWarning.phtml
  themes/bootstrap5/templates/search/results.phtml
Labels: improvement

#4165 Add record tab for displaying channels.
  config/vufind/RecordTabs.ini
  config/vufind/channels.ini
  languages/en.ini
  module/VuFind/src/VuFind/ChannelProvider/ChannelLoader.php
  module/VuFind/src/VuFind/RecordTab/Channels.php
  module/VuFind/src/VuFind/RecordTab/ChannelsFactory.php
  module/VuFind/src/VuFind/RecordTab/PluginManager.php
  module/VuFind/tests/unit-tests/src/VuFindTest/ChannelProvider/ChannelLoaderTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordTab/ChannelsTest.php
  themes/bootstrap3/templates/RecordTab/channels.phtml
  themes/bootstrap3/templates/channels/channelList.phtml
  themes/bootstrap5/templates/RecordTab/channels.phtml
  themes/bootstrap5/templates/channels/channelList.phtml
Labels: new feature, new language strings

#4218 Modified ShibbolethTest to use the entity interface
  module/VuFind/tests/integration-tests/src/VuFindTest/Auth/ShibbolethTest.php
Labels: tests

#4220 Deal with bad theme config more gracefully.
  module/VuFind/src/VuFind/Bootstrapper.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/BasicTest.php
  module/VuFindTheme/src/VuFindTheme/ThemeInfoFactory.php
Labels: bugfix

#4217 Fix keyboard position for rtl languages
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/components/keyboard.less
  themes/bootstrap3/scss/components/keyboard.scss
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/scss/components/keyboard.scss
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal5/css/compiled.css
Labels: bugfix

#4216 Fix several rtl design bugs
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/scss/bootstrap.scss
  themes/bootstrap5/scss/bs3-compat.scss
  themes/bootstrap5/scss/components/keyboard.scss
  themes/bootstrap5/scss/components/search.scss
  themes/local_theme_example/css/compiled.css
  themes/sandal5/css/compiled.css
Labels: bugfix

#4223 Fix initial focus handling in lightbox with Bootstrap 5.
  themes/bootstrap5/js/lightbox.js
Labels: bugfix

#4215 JsDoc: account_ajax, relais and search
  .eslintrc.jsdoc.js
  themes/bootstrap5/js/account_ajax.js
  themes/bootstrap5/js/relais.js
  themes/bootstrap5/js/search.js
Labels: documentation

#4221 [VUFIND-1726] Fix top heading to h1 on advanced search
  themes/bootstrap5/templates/search/advanced/layout.phtml
Labels: accessibility
