Repository vufind-org/vufind, pull requests merged in 2025-06, with the labels that each got.

#4403 Minor correction to Mongolian translations
  languages/mn.ini
Labels: i18n

#4384 Refactor session initiator handling
  module/VuFind/src/VuFind/Auth/AbstractBase.php
  module/VuFind/src/VuFind/Auth/AuthInterface.php
  module/VuFind/src/VuFind/Auth/CAS.php
  module/VuFind/src/VuFind/Auth/ChoiceAuth.php
  module/VuFind/src/VuFind/Auth/Facebook.php
  module/VuFind/src/VuFind/Auth/Manager.php
  module/VuFind/src/VuFind/Auth/ManagerFactory.php
  module/VuFind/src/VuFind/Auth/OpenIDConnect.php
  module/VuFind/src/VuFind/Auth/Shibboleth.php
  module/VuFind/src/VuFind/Auth/SimulatedSSO.php
  module/VuFind/src/VuFind/Controller/MyResearchController.php
  module/VuFind/src/VuFind/View/Helper/Root/Auth.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/ChoiceAuthTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/ManagerTest.php
  themes/bootstrap5/templates/Auth/AbstractBase/login.phtml
  themes/bootstrap5/templates/RecordTab/usercomments.phtml
  themes/bootstrap5/templates/header.phtml
  themes/bootstrap5/templates/record/rating.phtml
Labels: architecture

#4373 Fix incorrect helper arguments when displaying short summary.
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/core.phtml
Labels: bugfix

#4374 Add unit test for Summon search options.
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/Summon/OptionsTest.php
Labels: tests

#4314 Upgrade to Solr 9.8.1
  build.xml
  import/browse-indexing.jar
  solr.bat
  solr.sh
  solr/vufind/authority/conf/solrconfig.xml
  solr/vufind/biblio/conf/solrconfig.xml
  solr/vufind/jars/browse-handler.jar
  solr/vufind/reserves/conf/solrconfig.xml
  solr/vufind/website/conf/solrconfig.xml
Labels: dependencies

#4409 Remove deprecated static config locator
  module/VuFind/src/VuFind/Config/Locator.php
  module/VuFind/src/VuFind/Config/SearchSpecsReader.php
  module/VuFind/src/VuFind/Config/YamlReader.php
  module/VuFind/src/VuFind/Config/YamlReaderFactory.php
  module/VuFind/src/VuFind/ILS/Driver/XCNCIP2.php
  module/VuFind/src/VuFind/RecordTab/Map.php
  module/VuFind/src/VuFind/RecordTab/MapFactory.php
  module/VuFind/src/VuFindTest/Feature/LiveSolrTrait.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Config/LocatorTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Config/SearchSpecsReaderTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Config/YamlReaderTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Form/FormTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/ILS/Driver/XCNCIP2Test.php
  module/VuFind/tests/unit-tests/src/VuFindTest/ILS/OAuth2TokenTraitTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordTab/MapTest.php
  module/VuFindConsole/src/VuFindConsole/Command/Harvest/HarvestOaiCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Harvest/HarvestOaiCommandFactory.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/SwitchDbHashCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/SwitchDbHashCommandFactory.php
  module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Harvest/HarvestOaiCommandTest.php
  module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Util/SwitchDbHashCommandTest.php
  module/VuFindTheme/src/VuFindTheme/ThemeGenerator.php
Labels: architecture

#4413 Fix bug: passing non-numeric edit parameter caused fatal error.
  module/VuFind/src/VuFind/Controller/AbstractSearch.php
Labels: bugfix

#4423 Update translations for 10.2 release - Hindi
  languages/RecordAttribute/hi.ini
  languages/Reserves/hi.ini
  languages/hi.ini
Labels: i18n

#4424 Update translations for 10.2 release - Northern Sámi
  languages/Reserves/se.ini
  languages/se.ini
Labels: i18n

#4426 Update translations for 10.2 release - Japanese
  languages/KeyboardLayout/ja.ini
  languages/RecordAttribute/ja.ini
  languages/Reserves/ja.ini
  languages/ja.ini
Labels: i18n

#4427 KohaRest: Fix hold expiration date conversion when placing a hold.
  module/VuFind/src/VuFind/ILS/Driver/KohaRest.php
Labels: bugfix

#4428 Reduce redundant printing code.
  themes/bootstrap3/js/common.js
  themes/bootstrap5/js/common.js
Labels: improvement

#4291 Fix screen reader issues in hierarchy tree
  themes/bootstrap5/templates/hierarchy/tree.phtml
Labels: accessibility

#4433 Update translations for 10.2 release - Spanish
  languages/CreatorRoles/es.ini
  languages/ISO639-3/es.ini
  languages/RecordAttribute/es.ini
  languages/Reserves/es.ini
  languages/es.ini
Labels: i18n

#4434 Update translations for 10.2 release - Turkish
  languages/CreatorRoles/tr.ini
  languages/RecordAttribute/tr.ini
  languages/Reserves/tr.ini
  languages/tr.ini
Labels: i18n

#4432 Update translations for 10.2 release - Swedish
  languages/RecordAttribute/sv.ini
  languages/Reserves/sv.ini
  languages/sv.ini
Labels: i18n

#4438 Update translations for 10.2 release - French
  languages/CookieConsent/fr.ini
  languages/HoldingStatus/fr.ini
  languages/ILSMessages/fr.ini
  languages/ISO639-3/fr.ini
  languages/IndexFieldDescription/fr.ini
  languages/KeyboardLayout/fr.ini
  languages/RecordAttribute/fr.ini
  languages/Reserves/fr.ini
  languages/ServiceType/fr.ini
  languages/WorldCatFormats/fr.ini
  languages/fr.ini
Labels: i18n

#4439 Update translations for 10.2 release - Italian
  languages/CreatorRoles/it.ini
  languages/RecordAttribute/it.ini
  languages/Reserves/it.ini
Labels: i18n

#4446 Minor additions and corrections to French language translations
  languages/fr.ini
Labels: i18n

#4447 Fix escaping of ampersands in translation keys
  languages/ar.ini
  languages/bn.ini
  languages/ca.ini
  languages/de.ini
  languages/el.ini
  languages/en.ini
  languages/es.ini
  languages/fi.ini
  languages/fr.ini
  languages/ga.ini
  languages/hi.ini
  languages/hy.ini
  languages/ja.ini
  languages/mn.ini
  languages/pt-br.ini
  languages/ru.ini
  languages/se.ini
  languages/sv.ini
  languages/tr.ini
  languages/uk.ini
  module/VuFind/src/VuFind/I18n/Translator/TranslatorAwareTrait.php
Labels: i18n

#4448 Deduplicate some creator role translations
  languages/CreatorRoles/aliases.ini
  languages/CreatorRoles/ar.ini
  languages/CreatorRoles/ca.ini
  languages/CreatorRoles/cs.ini
  languages/CreatorRoles/cy.ini
  languages/CreatorRoles/de.ini
  languages/CreatorRoles/el.ini
  languages/CreatorRoles/en.ini
  languages/CreatorRoles/es.ini
  languages/CreatorRoles/eu.ini
  languages/CreatorRoles/fr.ini
  languages/CreatorRoles/ga.ini
  languages/CreatorRoles/hi.ini
  languages/CreatorRoles/hr.ini
  languages/CreatorRoles/hy.ini
  languages/CreatorRoles/it.ini
  languages/CreatorRoles/ja.ini
  languages/CreatorRoles/mn.ini
  languages/CreatorRoles/nl.ini
  languages/CreatorRoles/pl.ini
  languages/CreatorRoles/pt-br.ini
  languages/CreatorRoles/ru.ini
  languages/CreatorRoles/tr.ini
  languages/CreatorRoles/uk.ini
  languages/CreatorRoles/vi.ini
Labels: i18n

#4451 Added Greek translation for Laser Disc
  languages/el.ini
Labels: i18n

#4457 Fix and tweak export mechanism.
  module/VuFind/src/VuFind/Controller/CartController.php
  module/VuFind/src/VuFind/Export.php
  module/VuFind/src/VuFind/ExportFactory.php
  module/VuFind/tests/unit-tests/src/VuFindTest/ExportTest.php
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/toolbar.phtml
  themes/bootstrap5/templates/cart/export.phtml
Labels: architecture

#4458 Fix multi-facet init when multi-filters-text element is not available.
  themes/bootstrap5/js/facets.js
Labels: bugfix

#4461 Remove <bdi> tag in RecordDataFormatter combineAlt render type
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/combine-alt.phtml
Labels: bugfix
