Repository vufind-org/vufind, pull requests merged in 2025-02, with the labels that each got.

#4228 Fix ChoiceAuth getUsernamePolicy and getPasswordPolicy when not logged in.
  module/VuFind/src/VuFind/Auth/ChoiceAuth.php
Labels: bugfix

#4227 [release-10.1] Fix form validation
  module/VuFind/src/VuFindTest/Integration/MinkTestCase.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/RecordActionsTest.php
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/js/common.js
  themes/bootstrap3/js/validation.js
  themes/bootstrap3/js/vendor/validator.min.js
  themes/bootstrap3/less/bootstrap.less
  themes/bootstrap3/scss/bootstrap.scss
  themes/bootstrap3/templates/Auth/AbstractBase/newpassword.phtml
  themes/bootstrap3/templates/Auth/Database/create.phtml
  themes/bootstrap3/templates/myresearch/account.phtml
  themes/bootstrap3/templates/myresearch/changeemail.phtml
  themes/bootstrap3/templates/myresearch/newpassword.phtml
  themes/bootstrap3/templates/record/sms.phtml
  themes/bootstrap3/theme.config.php
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/js/common.js
  themes/bootstrap5/js/validation.js
  themes/bootstrap5/js/vendor/validator.min.js
  themes/bootstrap5/scss/bootstrap.scss
  themes/bootstrap5/templates/Auth/AbstractBase/newpassword.phtml
  themes/bootstrap5/templates/Auth/Database/create.phtml
  themes/bootstrap5/templates/myresearch/account.phtml
  themes/bootstrap5/templates/myresearch/changeemail.phtml
  themes/bootstrap5/templates/myresearch/newpassword.phtml
  themes/bootstrap5/templates/record/sms.phtml
  themes/bootstrap5/theme.config.php
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal5/css/compiled.css
Labels: bugfix

#3991 Add backend: ProQuest Federated Search Gateway
  config/vufind/ProQuestFSG.ini
  config/vufind/RecordTabs.ini
  config/vufind/searches.ini
  languages/en.ini
  module/VuFind/config/module.config.php
  module/VuFind/src/VuFind/Controller/Feature/CheckEnabledTrait.php
  module/VuFind/src/VuFind/Controller/ProQuestFSGController.php
  module/VuFind/src/VuFind/Controller/ProQuestFSGrecordController.php
  module/VuFind/src/VuFind/Recommend/PluginManager.php
  module/VuFind/src/VuFind/Recommend/ProQuestFSGResults.php
  module/VuFind/src/VuFind/Recommend/ProQuestFSGResultsDeferred.php
  module/VuFind/src/VuFind/RecordDriver/PluginManager.php
  module/VuFind/src/VuFind/RecordDriver/ProQuestFSG.php
  module/VuFind/src/VuFind/Search/BackendRegistry.php
  module/VuFind/src/VuFind/Search/Base/Results.php
  module/VuFind/src/VuFind/Search/Factory/ProQuestFSGBackendFactory.php
  module/VuFind/src/VuFind/Search/Options/PluginManager.php
  module/VuFind/src/VuFind/Search/Params/PluginManager.php
  module/VuFind/src/VuFind/Search/ProQuestFSG/Options.php
  module/VuFind/src/VuFind/Search/ProQuestFSG/Params.php
  module/VuFind/src/VuFind/Search/ProQuestFSG/Results.php
  module/VuFind/src/VuFind/Search/Results/PluginManager.php
  module/VuFind/src/VuFind/View/Helper/Root/RecordDataFormatterFactory.php
  module/VuFind/tests/fixtures/proquestfsg/connector_record.json
  module/VuFind/tests/fixtures/proquestfsg/connector_searchresult.json
  module/VuFind/tests/fixtures/proquestfsg/record.xml
  module/VuFind/tests/fixtures/proquestfsg/searchresult.xml
  module/VuFind/tests/unit-tests/src/VuFindTest/Recommend/ProQuestFSGResultsDeferredTest.php
  module/VuFind/xsl/sru-convert-simple.xsl
  module/VuFind/xsl/sru-convert.xsl
  module/VuFindSearch/src/VuFindSearch/Backend/ProQuestFSG/Backend.php
  module/VuFindSearch/src/VuFindSearch/Backend/ProQuestFSG/Connector.php
  module/VuFindSearch/src/VuFindSearch/Backend/ProQuestFSG/QueryBuilder.php
  module/VuFindSearch/src/VuFindSearch/Backend/ProQuestFSG/Response/XML/Record.php
  module/VuFindSearch/src/VuFindSearch/Backend/ProQuestFSG/Response/XML/RecordCollection.php
  module/VuFindSearch/src/VuFindSearch/Backend/ProQuestFSG/Response/XML/RecordCollectionFactory.php
  module/VuFindSearch/src/VuFindSearch/Backend/SRU/Connector.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/ProQuestFSG/BackendTest.php
  module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/ProQuestFSG/ConnectorTest.php
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/scss/components/record.scss
  themes/bootstrap5/templates/Recommend/ProQuestFSGResults.phtml
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/result-list.phtml
  themes/bootstrap5/templates/RecordDriver/ProQuestFSG/data-publicationDetails.phtml
  themes/bootstrap5/templates/RecordDriver/ProQuestFSG/link-author.phtml
  themes/bootstrap5/templates/RecordDriver/ProQuestFSG/link-journaltitle.phtml
  themes/bootstrap5/templates/RecordDriver/ProQuestFSG/link-subject.phtml
  themes/bootstrap5/templates/proquestfsg/advanced.phtml
  themes/bootstrap5/templates/proquestfsg/home.phtml
  themes/bootstrap5/templates/proquestfsg/results.phtml
  themes/local_theme_example/css/compiled.css
  themes/sandal5/css/compiled.css
Labels: new feature, new language strings

#4205 [VUFIND-1722] Add tests for web index
  build.xml
  import/raw.properties
  import/xsl/raw.xsl
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/WebSearchTest.php
  tests/data/website/solr.xml
Labels: tests

#4229 Revise TopRecommendations config defaults.
  config/vufind/searches.ini
Labels: improvement

#4195 Refactoring RecordDataFormatter spec provision
  module/VuFind/config/module.config.php
  module/VuFind/src/VuFind/RecordDataFormatter/Specs/AbstractBase.php
  module/VuFind/src/VuFind/RecordDataFormatter/Specs/DefaultRecord.php
  module/VuFind/src/VuFind/RecordDataFormatter/Specs/DefaultRecordFactory.php
  module/VuFind/src/VuFind/RecordDataFormatter/Specs/PluginManager.php
  module/VuFind/src/VuFind/RecordDataFormatter/Specs/SpecInterface.php
  module/VuFind/src/VuFind/RecordDriver/AbstractBase.php
  module/VuFind/src/VuFind/RecordDriver/DefaultRecord.php
  module/VuFind/src/VuFind/View/Helper/Root/RecordDataFormatter.php
  module/VuFind/src/VuFind/View/Helper/Root/RecordDataFormatterFactory.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/RecordDataFormatterTest.php
Labels: improvement, architecture

#4183 Display loan types from FOLIO
  config/vufind/config.ini
  languages/en.ini
  module/VuFind/src/VuFind/ILS/Driver/Demo.php
  module/VuFind/src/VuFind/ILS/Driver/Folio.php
  module/VuFind/src/VuFind/View/Helper/Root/Config.php
  module/VuFind/tests/unit-tests/src/VuFindTest/ILS/Driver/FolioTest.php
  themes/bootstrap5/templates/RecordTab/holdingsils/standard.phtml
Labels: new feature, discussion

#4232 ExtendClass generator: Strip leading slashes from class names
  module/VuFindConsole/src/VuFindConsole/Command/Generate/ExtendClassCommand.php
Labels: improvement

#4234 Drop legacy 1.x compatibility from SolrMarc code.
  import/index_java/src/org/vufind/index/ConfigManager.java
  import/vufind.properties
Labels: indexing

#4108 Fixed first/last_indexed, improved import perf, support for mariadb connector
  config/vufind/config.ini
  import/index_java/src/org/vufind/index/DatabaseManager.java
  import/index_java/src/org/vufind/index/UpdateDateTracker.java
  import/lib_local/mariadb-java-client-3.5.1.jar
  module/VuFind/src/VuFind/Controller/InstallController.php
  module/VuFind/src/VuFind/Db/AdapterFactory.php
  themes/bootstrap5/templates/install/fixdatabase.phtml
Labels: indexing

#4214 Update relator codes from Library of Congress
  config/vufind/author-classification.ini
  languages/CreatorRoles/aliases.ini
  languages/CreatorRoles/ar.ini
  languages/CreatorRoles/bn.ini
  languages/CreatorRoles/ca.ini
  languages/CreatorRoles/cs.ini
  languages/CreatorRoles/cy.ini
  languages/CreatorRoles/de.ini
  languages/CreatorRoles/el.ini
  languages/CreatorRoles/en.ini
  languages/CreatorRoles/es.ini
  languages/CreatorRoles/eu.ini
  languages/CreatorRoles/fi.ini
  languages/CreatorRoles/fr.ini
  languages/CreatorRoles/ga.ini
  languages/CreatorRoles/hi.ini
  languages/CreatorRoles/hr.ini
  languages/CreatorRoles/hy.ini
  languages/CreatorRoles/it.ini
  languages/CreatorRoles/ja.ini
  languages/CreatorRoles/mn.ini
  languages/CreatorRoles/nl.ini
  languages/CreatorRoles/pl.ini
  languages/CreatorRoles/pt-br.ini
  languages/CreatorRoles/ru.ini
  languages/CreatorRoles/se.ini
  languages/CreatorRoles/sv.ini
  languages/CreatorRoles/tr.ini
  languages/CreatorRoles/uk.ini
  languages/CreatorRoles/vi.ini
Labels: improvement

#4226 BrowZine covers: skip over default images.
  config/vufind/BrowZine.ini
  module/VuFind/src/VuFind/Content/Covers/BrowZine.php
  module/VuFind/src/VuFind/Content/Covers/BrowZineFactory.php
  module/VuFind/tests/fixtures/browzine/cover-default.json
  module/VuFind/tests/fixtures/browzine/cover-non-default.json
  module/VuFind/tests/unit-tests/src/VuFindTest/Content/Covers/BrowZineTest.php
Labels: improvement

#4241 Combined search: add setting to disable default filters.
  config/vufind/combined.ini
  module/VuFind/src/VuFind/Controller/CombinedController.php
Labels: new feature

#4247 Make it easier to override sort order in scheduled search notify command.
  module/VuFindConsole/src/VuFindConsole/Command/ScheduledSearch/NotifyCommand.php
Labels: improvement

#4244 [VUFIND-1755] Allow FOLIO token sharing between sessions.
  config/vufind/Folio.ini
  module/VuFind/src/VuFind/ILS/Driver/Folio.php
Labels: bugfix

#4222 Add tests to cover bottom button functionality.
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/BulkTest.php
Labels: tests

#4251 [10.1] Ensure that sort list always contains a selected sort option.
  languages/ar.ini
  languages/bn.ini
  languages/ca.ini
  languages/cs.ini
  languages/cy.ini
  languages/de.ini
  languages/el.ini
  languages/en.ini
  languages/es.ini
  languages/eu.ini
  languages/fi.ini
  languages/fr.ini
  languages/ga.ini
  languages/hi.ini
  languages/hr.ini
  languages/hy.ini
  languages/it.ini
  languages/ja.ini
  languages/mi.ini
  languages/mn.ini
  languages/nl.ini
  languages/pl.ini
  languages/pt-br.ini
  languages/pt.ini
  languages/ru.ini
  languages/se.ini
  languages/sv.ini
  languages/tr.ini
  languages/uk.ini
  languages/vi.ini
  module/VuFind/src/VuFind/Search/Base/Params.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/Solr/ParamsTest.php
Labels: bugfix

#4245 Fix and unify record toolbar entries.
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/scss/bootstrap.scss
  themes/bootstrap5/scss/components/record.scss
  themes/bootstrap5/scss/components/search.scss
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/toolbar.phtml
  themes/bootstrap5/templates/record/cart-buttons.phtml
  themes/local_theme_example/css/compiled.css
  themes/sandal5/css/compiled.css
  themes/sandal5/scss/sandal.scss
Labels: bugfix, improvement

#4253 Bottom button tests: fallback with Javascript.
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/BulkTest.php
Labels: tests

#4249 Fix book bag buttons and divider
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/scss/bootstrap.scss
  themes/bootstrap5/scss/components/search.scss
  themes/bootstrap5/templates/cart/cart.phtml
  themes/bootstrap5/templates/cart/contents.phtml
  themes/local_theme_example/css/compiled.css
  themes/sandal5/css/compiled.css
Labels: improvement

#4254 testBulkExport: improve reliability.
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/BulkTest.php
Labels: tests

#4257 Prevent malformed links in export-menu.phtml.
  themes/bootstrap3/templates/record/export-menu.phtml
  themes/bootstrap5/templates/record/export-menu.phtml
Labels: bugfix

#4259 Add option to ignore email addresses in linkify view helper
  module/VuFind/src/VuFind/View/Helper/Root/Linkify.php
  module/VuFind/src/VuFind/View/Helper/Root/LinkifyFactory.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/LinkifyTest.php
Labels: improvement

#4248 Tweak navbar and search tabs.
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/scss/bootstrap.scss
  themes/bootstrap5/scss/bs3-compat.scss
  themes/bootstrap5/scss/components/variables.scss
  themes/bootstrap5/templates/header.phtml
  themes/bootstrap5/templates/search/searchTabs.phtml
  themes/bootstrap5/templates/search/searchbox.phtml
  themes/local_theme_example/css/compiled.css
  themes/local_theme_example/templates/search/home.phtml
  themes/sandal5/css/compiled.css
  themes/sandal5/scss/search.scss
Labels: improvement, accessibility

#4261 Fix form submission in facet sidebar to not include any hash in the URL.
  themes/bootstrap5/js/facets.js
Labels: improvement

#4264 Make FallbackLoaderTest more robust.
  module/VuFind/src/VuFindTest/Feature/RetryClickTrait.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/BulkTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/FallbackLoaderTest.php
Labels: bugfix, tests

#3918 Generalize DOI linker system to support other identifier types
  .eslintrc.jsdoc.js
  config/vufind/BrowZine.ini
  config/vufind/config.ini
  languages/en.ini
  module/VuFind/config/module.config.php
  module/VuFind/src/VuFind/AjaxHandler/IdentifierLinksLookup.php
  module/VuFind/src/VuFind/AjaxHandler/IdentifierLinksLookupFactory.php
  module/VuFind/src/VuFind/AjaxHandler/PluginManager.php
  module/VuFind/src/VuFind/DoiLinker/BrowZine.php
  module/VuFind/src/VuFind/IdentifierLinker/BrowZine.php
  module/VuFind/src/VuFind/IdentifierLinker/BrowZineFactory.php
  module/VuFind/src/VuFind/IdentifierLinker/Demo.php
  module/VuFind/src/VuFind/IdentifierLinker/IdentifierLinkerInterface.php
  module/VuFind/src/VuFind/IdentifierLinker/PluginManager.php
  module/VuFind/src/VuFind/IdentifierLinker/Unpaywall.php
  module/VuFind/src/VuFind/IdentifierLinker/UnpaywallFactory.php
  module/VuFind/src/VuFind/View/Helper/Root/Doi.php
  module/VuFind/src/VuFind/View/Helper/Root/IdentifierLinker.php
  module/VuFind/src/VuFind/View/Helper/Root/IdentifierLinkerFactory.php
  module/VuFind/src/VuFindTest/Unit/AjaxHandlerTestCase.php
  module/VuFind/tests/fixtures/browzine/issn.json
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/CombinedSearchTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/IdentifierLinkerTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/AjaxHandler/IdentifierLinksLookupTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/DoiLinker/BrowZineTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/IdentifierLinker/BrowZineTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/IdentifierLinker/UnpaywallTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/RecordDataFormatterTest.php
  module/VuFindSearch/src/VuFindSearch/Backend/BrowZine/Connector.php
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/js/doi.js
  themes/bootstrap5/js/identifierLinks.js
  themes/bootstrap5/scss/components/icons.scss
  themes/bootstrap5/templates/Helpers/doi.phtml
  themes/bootstrap5/templates/Helpers/identifierLinks.phtml
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/data-onlineAccess.phtml
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/list-entry.phtml
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/result-grid.phtml
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/result-list.phtml
  themes/bootstrap5/templates/RecordDriver/EDS/core.phtml
  themes/bootstrap5/templates/RecordDriver/EDS/result-list.phtml
  themes/bootstrap5/templates/RecordDriver/Pazpar2/result-list.phtml
  themes/bootstrap5/templates/RecordDriver/SolrOverdrive/result-list.phtml
  themes/bootstrap5/templates/RecordTab/holdingsils.phtml
  themes/bootstrap5/templates/ajax/identifierLinks.phtml
  themes/local_theme_example/css/compiled.css
  themes/root/theme.config.php
  themes/sandal/css/compiled.css
  themes/sandal5/css/compiled.css
Labels: improvement, architecture

#4265 Fix bug: dashes in theme names could break SCSS build.
  Gruntfile.js
Labels: bugfix

#4262 Prevent empty breadcrumb when record title is missing.
  module/VuFind/src/VuFind/View/Helper/Root/RecordLinker.php
Labels: improvement

#4260 Fix HTML validation of profile page.
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/bootstrap.less
  themes/bootstrap3/scss/bootstrap.scss
  themes/bootstrap3/templates/librarycards/selectcard.phtml
  themes/bootstrap3/templates/myresearch/profile.phtml
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/scss/bootstrap.scss
  themes/bootstrap5/templates/librarycards/selectcard.phtml
  themes/bootstrap5/templates/myresearch/profile.phtml
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal5/css/compiled.css
Labels: bugfix

#4263 Clean up screen width variables and media queries.
  module/VuFind/src/VuFindTest/Feature/SearchFacetFilterTrait.php
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/scss/bootstrap.scss
  themes/bootstrap5/scss/bs3-compat.scss
  themes/bootstrap5/scss/components/advanced-search.scss
  themes/bootstrap5/scss/components/channels.scss
  themes/bootstrap5/scss/components/explain.scss
  themes/bootstrap5/scss/components/keyboard.scss
  themes/bootstrap5/scss/components/lightbox.scss
  themes/bootstrap5/scss/components/offcanvas.scss
  themes/bootstrap5/scss/components/record.scss
  themes/bootstrap5/scss/components/search.scss
  themes/bootstrap5/scss/components/sidebar.scss
  themes/bootstrap5/scss/components/trees.scss
  themes/bootstrap5/templates/Recommend/TopFacets.phtml
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/collection-info.phtml
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/controls/qrcode.phtml
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/core.phtml
  themes/bootstrap5/templates/RecordTab/collectionhierarchytree.phtml
  themes/bootstrap5/templates/browse/home.phtml
  themes/bootstrap5/templates/devtools/language.phtml
  themes/bootstrap5/templates/eds/advanced.phtml
  themes/bootstrap5/templates/search/controls/view.phtml
  themes/bootstrap5/templates/search/filters.phtml
  themes/local_theme_example/css/compiled.css
  themes/sandal5/css/compiled.css
  themes/sandal5/scss/sandal.scss
  themes/sandal5/scss/search.scss
  themes/sandal5/scss/variables.scss
Labels: architecture

#4266 OAI server: improve exception handling
  module/VuFind/src/VuFind/Controller/OaiController.php
  module/VuFind/src/VuFind/OAI/Server.php
Labels: bugfix

#4268 Update RecordDataFormatter comment
  config/vufind/RecordDataFormatter.ini
Labels: documentation

#4250 [VUFIND-1700] Use record-tab-init event instead of registerTabEvents and remove jQuery
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/RecordActionsTest.php
  themes/bootstrap5/js/common.js
  themes/bootstrap5/js/embedded_record.js
  themes/bootstrap5/js/lightbox.js
  themes/bootstrap5/js/openurl.js
  themes/bootstrap5/js/record.js
Labels: architecture

#4238 [VUFIND-1731] Aria hide sliders and replace slider library
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/css/vendor/bootstrap-slider.min.css
  themes/bootstrap5/css/vendor/nouislider.min.css
  themes/bootstrap5/js/advanced_search.js
  themes/bootstrap5/js/date_range_slider.js
  themes/bootstrap5/js/facets.js
  themes/bootstrap5/js/vendor/bootstrap-slider.min.js
  themes/bootstrap5/js/vendor/nouislider.min.js
  themes/bootstrap5/js/vendor/nouislider_LICENSE.md
  themes/bootstrap5/package.json
  themes/bootstrap5/scss/components/sliders.scss
  themes/bootstrap5/templates/Recommend/SideFacets/range-slider.phtml
  themes/bootstrap5/templates/Recommend/SideFacetsDeferred.phtml
  themes/bootstrap5/templates/_ui/components/date-range-slider.phtml
  themes/bootstrap5/templates/search/advanced/eds.phtml
  themes/bootstrap5/templates/search/advanced/ranges.phtml
  themes/bootstrap5/tools/copyDependencies.mjs
  themes/local_theme_example/css/compiled.css
  themes/sandal5/css/compiled.css
Labels: accessibility, architecture

#1230 Open ID Connect implementation
  config/vufind/OpenIDConnectClient.ini
  config/vufind/config.ini
  module/VuFind/src/VuFind/Auth/OpenIDConnect.php
  module/VuFind/src/VuFind/Auth/OpenIDConnectFactory.php
  module/VuFind/src/VuFind/Auth/PluginManager.php
  module/VuFind/tests/fixtures/auth/openidconnectprovider.json
  module/VuFind/tests/fixtures/auth/openidconnectprovider404.json
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/OpenIDConnectTest.php
Labels: new feature

#4269 Refactor the details dialog of feedback admin to use normal lightbox.
  module/VuFindAdmin/config/module.config.php
  module/VuFindAdmin/src/VuFindAdmin/Controller/FeedbackController.php
  themes/bootstrap5/templates/admin/feedback/details.phtml
  themes/bootstrap5/templates/admin/feedback/home.phtml
Labels: improvement

#4273 Hide additional controls from print version.
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/data-tags.phtml
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/result-list.phtml
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/versions-link.phtml
  themes/bootstrap5/templates/RecordDriver/SolrOverdrive/result-list.phtml
  themes/bootstrap5/templates/RecordTab/holdingsils.phtml
Labels: improvement
