Repository vufind-org/vufind, pull requests merged in 2025-08, with the labels that each got.

#4515 Add JSDoc for hold.js
  .eslintrc.jsdoc.js
  themes/bootstrap5/js/hold.js
Labels: documentation

#4518 Add JSDoc for combined-search.js
  .eslintrc.jsdoc.js
  themes/bootstrap5/js/combined-search.js
Labels: documentation

#4519 Add JSDoc to map_selection_leaflet.js
  .eslintrc.jsdoc.js
  themes/bootstrap5/js/map_selection_leaflet.js
Labels: documentation

#4520 Add JSDoc to ill.js
  .eslintrc.jsdoc.js
  themes/bootstrap5/js/ill.js
Labels: documentation

#4523 Specify DismaxHandler within ExactSettings (comments)
  config/vufind/searchspecs.yaml
Labels: documentation

#4525 Add JSDoc to record_versions.js
  .eslintrc.jsdoc.js
  themes/bootstrap5/js/record_versions.js
Labels: documentation

#4526 Add JSDoc to preview.js
  .eslintrc.jsdoc.js
  themes/bootstrap5/js/preview.js
Labels: documentation

#4527 Add JSDoc to embedded_record.js
  .eslintrc.jsdoc.js
  themes/bootstrap5/js/embedded_record.js
Labels: documentation

#4529 Add JSDoc to sticky_elements.js
  .eslintrc.jsdoc.js
  themes/bootstrap5/js/sticky_elements.js
Labels: documentation

#4531 Add JSDoc to advanced_search.js
  .eslintrc.jsdoc.js
  themes/bootstrap5/js/advanced_search.js
Labels: documentation

#4532 Add JSDoc to checkouts.js
  .eslintrc.jsdoc.js
  themes/bootstrap5/js/checkouts.js
Labels: documentation

#4535 Add JSDoc to cart.js
  .eslintrc.jsdoc.js
  themes/bootstrap5/js/cart.js
Labels: documentation

#4536 Add JSDoc to explain.js
  .eslintrc.jsdoc.js
  themes/bootstrap5/js/explain.js
Labels: documentation

#4538 Add JSDoc for hierarchy_tree.js
  .eslintrc.jsdoc.js
  themes/bootstrap5/js/hierarchy_tree.js
Labels: documentation

#4546 Add JSDoc for lightbox.js
  .eslintrc.jsdoc.js
  themes/bootstrap5/js/lightbox.js
Labels: documentation

#4545 Add JSDoc for record.js
  .eslintrc.jsdoc.js
  themes/bootstrap5/js/record.js
Labels: documentation

#4558 Add FiscalTransactionDescription to fines in XCNCIP2 ILS driver
  module/VuFind/src/VuFind/ILS/Driver/XCNCIP2.php
  module/VuFind/tests/unit-tests/src/VuFindTest/ILS/Driver/XCNCIP2Test.php
Labels: improvement

#4560 Prevent duplicates in alphabrowse useInstead and seeAlso headings
  themes/bootstrap5/templates/alphabrowse/home.phtml
Labels: improvement

#4565 Improve output of DoctrineSchemaValidationTest.
  module/VuFind/tests/integration-tests/src/VuFindTest/Db/Service/DoctrineSchemaValidationTest.php
Labels: tests

#4567 Fix German translation for ils_connection_failed
  languages/de.ini
Labels: i18n

#4572 [VUFIND-1789] Use EDS default setting for searchmode in advanced search
  module/VuFind/src/VuFind/Controller/EdsController.php
Labels: bugfix

#4553 RateLimiter: Add RejectAll policy
  config/vufind/RateLimiter.yaml
  module/VuFind/src/VuFind/RateLimiter/RateLimiterManagerFactory.php
  module/VuFind/src/VuFind/RateLimiter/RejectAll.php
  module/VuFind/tests/unit-tests/src/VuFindTest/RateLimiter/RejectAllTest.php
Labels: new feature
