Repository vufind-org/vufind, pull requests merged in 2025-07, with the labels that each got.

#4459 Disable hidden sort for new searches
  module/VuFind/src/VuFind/Search/Base/Params.php
  themes/bootstrap5/templates/search/searchbox.phtml
Labels: improvement

#4463 [VUFIND-1763] Fix underlined icons in results on mobile
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/scss/components/search.scss
  themes/local_theme_example/css/compiled.css
  themes/sandal5/css/compiled.css
Labels: bugfix

#4462 Fix covers with disabled browser cache if thumbnail is string
  config/vufind/config.ini
  module/VuFind/src/VuFind/Cover/Router.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/RecordCoverImageTest.php
Labels: bugfix

#4465 Clean up orphans when deleting tags.
  module/VuFind/src/VuFind/Controller/TagController.php
Labels: improvement

#4467 Remove returned sandal theme files
  themes/sandal/css/compiled.css
  themes/sandal/less/sandal.less
  themes/sandal/scss/sandal.scss
Labels: bugfix

#4255 Update first/second/non-creative roles
  config/vufind/author-classification.ini
Labels: improvement

#4471 Use a symlinked local directory for tests with defaultconfigs=true
  build.xml
Labels: tests

#4344 Add more relator codes from Library of Congress
  config/vufind/author-classification.ini
Labels: improvement

#4408 Add a page-title component
  module/VuFind/src/VuFind/View/Helper/Root/Component.php
  themes/bootstrap5/templates/_ui/components/page-title.phtml
  themes/bootstrap5/templates/admin/config/home.phtml
  themes/bootstrap5/templates/admin/feedback/home.phtml
  themes/bootstrap5/templates/admin/home.phtml
  themes/bootstrap5/templates/admin/maintenance/home.phtml
  themes/bootstrap5/templates/admin/socialstats/home.phtml
  themes/bootstrap5/templates/admin/tags/home.phtml
  themes/bootstrap5/templates/admin/tags/list.phtml
  themes/bootstrap5/templates/admin/tags/manage.phtml
  themes/bootstrap5/templates/cart/cart.phtml
  themes/bootstrap5/templates/cart/export.phtml
  themes/bootstrap5/templates/cart/save.phtml
  themes/bootstrap5/templates/checkouts/history.phtml
  themes/bootstrap5/templates/collections/home.phtml
  themes/bootstrap5/templates/error/permissiondenied.phtml
  themes/bootstrap5/templates/error/unavailable.phtml
  themes/bootstrap5/templates/feedback/form.phtml
  themes/bootstrap5/templates/feedback/response.phtml
  themes/bootstrap5/templates/holds/edit.phtml
  themes/bootstrap5/templates/install/disabled.phtml
  themes/bootstrap5/templates/install/done.phtml
  themes/bootstrap5/templates/install/fixbasicconfig.phtml
  themes/bootstrap5/templates/install/fixcache.phtml
  themes/bootstrap5/templates/install/fixdatabase.phtml
  themes/bootstrap5/templates/install/fixdependencies.phtml
  themes/bootstrap5/templates/install/fixils.phtml
  themes/bootstrap5/templates/install/fixsecurity.phtml
  themes/bootstrap5/templates/install/fixsolr.phtml
  themes/bootstrap5/templates/install/fixsslcerts.phtml
  themes/bootstrap5/templates/install/home.phtml
  themes/bootstrap5/templates/install/showsql.phtml
  themes/bootstrap5/templates/librarycards/home.phtml
  themes/bootstrap5/templates/myresearch/account.phtml
  themes/bootstrap5/templates/myresearch/checkedout.phtml
  themes/bootstrap5/templates/myresearch/delete.phtml
  themes/bootstrap5/templates/myresearch/fines.phtml
  themes/bootstrap5/templates/myresearch/profile.phtml
  themes/bootstrap5/templates/oai/home.phtml
  themes/bootstrap5/templates/record/hold.phtml
  themes/bootstrap5/templates/record/illrequest.phtml
  themes/bootstrap5/templates/record/rating.phtml
  themes/bootstrap5/templates/record/storageretrievalrequest.phtml
  themes/bootstrap5/templates/search/newitem.phtml
  themes/bootstrap5/templates/upgrade/error.phtml
  themes/bootstrap5/templates/upgrade/fixanonymoustags.phtml
  themes/bootstrap5/templates/upgrade/fixduplicatetags.phtml
  themes/bootstrap5/templates/upgrade/fixmetadata.phtml
  themes/bootstrap5/templates/upgrade/getdbcredentials.phtml
  themes/bootstrap5/templates/upgrade/getsourceversion.phtml
  themes/bootstrap5/templates/upgrade/home.phtml
  themes/bootstrap5/templates/upgrade/showsql.phtml
Labels: accessibility, small

#4475 Add spinners to comments tab
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/js/common.js
  themes/bootstrap5/js/lightbox.js
  themes/bootstrap5/js/record.js
  themes/bootstrap5/js/search.js
  themes/bootstrap5/scss/components/lightbox.scss
  themes/bootstrap5/scss/components/record.scss
  themes/bootstrap5/scss/components/search.scss
  themes/bootstrap5/scss/mixins/loading-overlay.scss
  themes/bootstrap5/scss/mixins/mixins.scss
  themes/bootstrap5/templates/RecordTab/usercomments.phtml
  themes/local_theme_example/css/compiled.css
  themes/sandal5/css/compiled.css
  themes/sandal5/scss/sandal.scss
Labels: improvement

#4482 Import Lokalise command: detect missing Lokalise keys.
  module/VuFindConsole/src/VuFindConsole/Command/Language/ImportLokaliseCommand.php
  module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Language/ImportLokaliseCommandTest.php
Labels: tooling, i18n

#4481 Upgrade all configurations
  module/VuFind/src/VuFind/Config/Upgrade.php
  module/VuFind/tests/fixtures/configs/default-upgrade/authority.ini
  module/VuFind/tests/unit-tests/src/VuFindTest/Config/UpgradeTest.php
Labels: improvement

#4490 Remove deprecated Auth::isLoggedIn() method.
  module/VuFind/src/VuFind/View/Helper/Root/Auth.php
Labels: architecture

#4491 Remove deprecated tag methods from record drivers.
  module/VuFind/src/VuFind/RecordDriver/AbstractBase.php
Labels: architecture

#4492 Remove deprecated CspHeaderGenerator::getHeader() method.
  module/VuFind/src/VuFind/Security/CspHeaderGenerator.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/CspTest.php
Labels: architecture

#4496 Fix config location doc comments
  module/VuFind/src/VuFind/Config/Location/AbstractConfigLocation.php
  module/VuFind/src/VuFind/Config/Location/ConfigLocationInterface.php
Labels: bugfix, documentation

#4499 Use handleParentConfig in Dir config handler
  module/VuFind/src/VuFind/Config/Handler/Dir.php
  module/VuFind/tests/fixtures/configs/inheritance/dir-config/subdir-child.ini
  module/VuFind/tests/unit-tests/src/VuFindTest/Config/ConfigManagerTest.php
Labels: improvement

#4497 Move RecordDataFormatter config to subdir
  config/vufind/RecordDataFormatter/DefaultRecord.ini
  module/VuFind/src/VuFind/Config/Upgrade.php
  module/VuFind/src/VuFind/RecordDataFormatter/Specs/DefaultRecordFactory.php
  module/VuFind/tests/fixtures/configs/legacy-record-data-formatter-config/RecordDataFormatter.ini
  module/VuFind/tests/integration-tests/src/VuFindTest/Config/ConfigUpgradeTest.php
Labels: improvement

#4503 Fix dropdown menu alignment
  themes/bootstrap5/js/facets.js
  themes/bootstrap5/templates/_ui/components/confirm-button.phtml
Labels: bugfix

#4504 Fix incorrect placeholders in Arabic translation.
  languages/ar.ini
Labels: bugfix, i18n

#4502 Add JSDoc for embedGBS.js.
  .eslintrc.jsdoc.js
  themes/bootstrap5/js/embedGBS.js
Labels: documentation

#4505 Add inheritance for Dir configs
  module/VuFind/src/VuFind/Config/Handler/Dir.php
  module/VuFind/src/VuFind/Config/PathResolver.php
  module/VuFind/tests/fixtures/configs/pathstack/base/config/vufind/all.ini
  module/VuFind/tests/fixtures/configs/pathstack/base/config/vufind/base-secondary.ini
  module/VuFind/tests/fixtures/configs/pathstack/base/config/vufind/base.ini
  module/VuFind/tests/fixtures/configs/pathstack/base/config/vufind/dir_config/all-sub.ini
  module/VuFind/tests/fixtures/configs/pathstack/base/config/vufind/dir_config/base-secondary-sub.ini
  module/VuFind/tests/fixtures/configs/pathstack/base/config/vufind/dir_config/base-sub.ini
  module/VuFind/tests/fixtures/configs/pathstack/primary/config/vufind/all.ini
  module/VuFind/tests/fixtures/configs/pathstack/primary/config/vufind/both.ini
  module/VuFind/tests/fixtures/configs/pathstack/primary/config/vufind/dir_config/all-sub.ini
  module/VuFind/tests/fixtures/configs/pathstack/primary/config/vufind/dir_config/primary-sub.ini
  module/VuFind/tests/fixtures/configs/pathstack/primary/config/vufind/only-primary.ini
  module/VuFind/tests/fixtures/configs/pathstack/primary/config/vufind/primary.ini
  module/VuFind/tests/fixtures/configs/pathstack/secondary/config/custom/all.ini
  module/VuFind/tests/fixtures/configs/pathstack/secondary/config/custom/base-secondary.ini
  module/VuFind/tests/fixtures/configs/pathstack/secondary/config/custom/both.ini
  module/VuFind/tests/fixtures/configs/pathstack/secondary/config/custom/dir_config/all-sub.ini
  module/VuFind/tests/fixtures/configs/pathstack/secondary/config/custom/dir_config/base-secondary-sub.ini
  module/VuFind/tests/fixtures/configs/pathstack/secondary/config/custom/facets.ini
  module/VuFind/tests/unit-tests/src/VuFindTest/Config/ConfigManagerTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Config/PathResolverTest.php
Labels: improvement

#4509 Add JSDoc for truncate.js
  .eslintrc.jsdoc.js
  themes/bootstrap5/js/truncate.js
Labels: documentation

#4510 Add JSDoc for config.js
  .eslintrc.jsdoc.js
  themes/bootstrap5/js/config.js
Labels: documentation

#4511 Add JSDoc for requests.js
  .eslintrc.jsdoc.js
  themes/bootstrap5/js/requests.js
Labels: documentation
