Repository vufind-org/vufind, pull requests merged in 2025-04, with the labels that each got.

#4316 Check configured extraHoldFields to skip unused API calls in HoldsTrait
  module/VuFind/src/VuFind/Controller/HoldsTrait.php
Labels: improvement

#4321 PropertyString: decode HTML entities appropriately.
  module/VuFind/src/VuFind/String/PropertyString.php
  module/VuFind/tests/unit-tests/src/VuFindTest/String/PropertyStringTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/EscapeOrCleanHtmlTest.php
Labels: bugfix

#4322 Fix inappropriate null returns in DefaultRecord driver.
  module/VuFind/src/VuFind/RecordDriver/DefaultRecord.php
Labels: bugfix

#4320 Remove unnecessary functionality from escapeOrCleanHtml
  module/VuFind/src/VuFind/View/Helper/Root/EscapeOrCleanHtml.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/EscapeOrCleanHtmlTest.php
Labels: bugfix

#4174 Add a configurable console menu for ease of use
  config/vufind/ConsoleMenu.yaml
  menu.php
  module/VuFindConsole/src/VuFindConsole/Command/Menu/MenuCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Menu/MenuCommandFactory.php
  module/VuFindConsole/src/VuFindConsole/Command/PluginManager.php
  module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Menu/MenuCommandTest.php
Labels: new feature, tooling

#4329 EDS and EPF: Remove unused getView() methods
  module/VuFind/src/VuFind/Search/EDS/Options.php
  module/VuFind/src/VuFind/Search/EPF/Options.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/EPF/OptionsTest.php
Labels: improvement

#4330 Fix bug: missing lookfor parameter caused type to be ignored.
  module/VuFind/src/VuFind/Search/QueryAdapter.php
Labels: bugfix

#4213 [VUFIND-1677] Prepare for laminas-view v3
  composer.json
  composer.lock
  config/vufind/config.ini
  module/VuFind/src/VuFind/View/Helper/Root/GoogleAnalytics.php
  module/VuFind/src/VuFind/View/Helper/Root/GoogleTagManager.php
  module/VuFind/src/VuFind/View/Helper/Root/Matomo.php
  module/VuFind/src/VuFind/View/Helper/Root/Piwik.php
  module/VuFind/src/VuFindTest/Feature/ViewTrait.php
  module/VuFindTheme/Module.php
  module/VuFindTheme/src/VuFindTheme/AssetPipeline.php
  module/VuFindTheme/src/VuFindTheme/AssetPipelineFactory.php
  module/VuFindTheme/src/VuFindTheme/View/Helper/AssetManager.php
  module/VuFindTheme/src/VuFindTheme/View/Helper/AssetManagerFactory.php
  module/VuFindTheme/src/VuFindTheme/View/Helper/ConcatTrait.php
  module/VuFindTheme/src/VuFindTheme/View/Helper/FootScript.php
  module/VuFindTheme/src/VuFindTheme/View/Helper/HeadLink.php
  module/VuFindTheme/src/VuFindTheme/View/Helper/HeadScript.php
  module/VuFindTheme/src/VuFindTheme/View/Helper/InlineScript.php
  module/VuFindTheme/src/VuFindTheme/View/Helper/SetupThemeResources.php
  module/VuFindTheme/tests/unit-tests/src/VuFindTest/AssetPipelineTest.php
  module/VuFindTheme/tests/unit-tests/src/VuFindTest/View/Helper/AssetManagerTest.php
  module/VuFindTheme/tests/unit-tests/src/VuFindTest/View/Helper/SetupThemeResourcesTest.php
Labels: architecture

#4331 Add support for extracting subject from email body in Mailer.
  module/VuFind/src/VuFind/Form/Handler/Email.php
  module/VuFind/src/VuFind/Mailer/Mailer.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Mailer/MailerTest.php
Labels: improvement

#4219 [VUFIND-1745] Drop remaining support for compiling scss files in PHP.
  composer.json
  composer.lock
  module/VuFindConsole/src/VuFindConsole/Command/PluginManager.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/AbstractCssBuilderCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/ScssBuilderCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/ScssBuilderCommandFactory.php
  module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Util/ScssBuilderCommandTest.php
  module/VuFindTheme/src/VuFindTheme/AbstractCssPreCompiler.php
  module/VuFindTheme/src/VuFindTheme/ScssCompiler.php
  module/VuFindTheme/tests/unit-tests/src/VuFindTest/CssPreCompilerTest.php
Labels: architecture

#4334 Improve error logging in Mailer.
  module/VuFind/src/VuFind/Mailer/Mailer.php
Labels: improvement

#4336 Disable loading of results with JS for reserves search.
  module/VuFind/src/VuFind/Search/Base/Options.php
  themes/bootstrap3/templates/search/reservesresults.phtml
  themes/bootstrap5/templates/search/reservesresults.phtml
Labels: bugfix

#4325 Add type declarations to auth manager
  module/VuFind/src/VuFind/Auth/AbstractBase.php
  module/VuFind/src/VuFind/Auth/AuthInterface.php
  module/VuFind/src/VuFind/Auth/CAS.php
  module/VuFind/src/VuFind/Auth/ChoiceAuth.php
  module/VuFind/src/VuFind/Auth/Manager.php
  module/VuFind/src/VuFind/Auth/MultiILS.php
  module/VuFind/src/VuFind/Auth/PluginManager.php
  module/VuFind/src/VuFind/Auth/Shibboleth.php
  module/VuFind/src/VuFind/Controller/MyResearchController.php
  module/VuFind/src/VuFind/Db/Entity/UserEntityInterface.php
  module/VuFind/src/VuFind/Db/Row/User.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/CASTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/ChoiceAuthTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/ManagerTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/MultiAuthTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Auth/PluginManagerTest.php
Labels: architecture

#4333 Use RecordDataFormatter.ini instead of hard coded function mapping
  config/vufind/RecordDataFormatter.ini
  module/VuFind/src/VuFind/Config/Upgrade.php
  module/VuFind/src/VuFind/RecordDataFormatter/Specs/AbstractBase.php
Labels: improvement

#4303 Add support for filtered backends in the combined search drop-down.
  config/vufind/searchbox.ini
  module/VuFind/src/VuFind/Controller/CombinedController.php
  module/VuFind/src/VuFind/View/Helper/Root/SearchBox.php
  themes/bootstrap5/templates/search/searchbox.phtml
Labels: improvement

#4337 Use UserEntityInterface in list template.
  themes/bootstrap3/templates/RecordDriver/DefaultRecord/list-entry.phtml
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/list-entry.phtml
Labels: bugfix

#4338 Clean up extraneous whitespace with htmlAttributes helper.
  themes/bootstrap5/templates/Auth/AbstractBase/newpassword.phtml
  themes/bootstrap5/templates/Auth/Database/create.phtml
  themes/bootstrap5/templates/Helpers/copy-to-clipboard-button.phtml
  themes/bootstrap5/templates/Helpers/identifierLinks.phtml
  themes/bootstrap5/templates/Recommend/PubDateVisAjax.phtml
  themes/bootstrap5/templates/RecordTab/collectionhierarchytree.phtml
  themes/bootstrap5/templates/_ui/components/date-range-slider.phtml
  themes/bootstrap5/templates/myresearch/bulk-action-buttons.phtml
  themes/bootstrap5/templates/search/bulk-action-buttons.phtml
  themes/root/templates/Helpers/bulk-action-button.phtml
Labels: improvement

#4346 Remove support of Extra_Config from Upgrader
  module/VuFind/src/VuFind/Config/Upgrade.php
Labels: architecture

#4317 Create star rating component.
  themes/bootstrap5/templates/RecordDriver/DefaultRecord/rating.phtml
  themes/bootstrap5/templates/RecordTab/usercomments.phtml
  themes/bootstrap5/templates/_ui/components/star-rating.phtml
  themes/bootstrap5/templates/record/comments-list.phtml
  themes/bootstrap5/templates/record/rating.phtml
Labels: architecture

#4350 Fix identifier link lookup for multiple items.
  themes/bootstrap5/js/identifierLinks.js
Labels: bugfix

#4348 Fix minor issues with breadcrumbs.
  themes/bootstrap5/templates/author/home.phtml
  themes/bootstrap5/templates/cart/cart.phtml
  themes/bootstrap5/templates/collection/view.phtml
  themes/bootstrap5/templates/librarycards/editcard.phtml
  themes/bootstrap5/templates/myresearch/editlist.phtml
  themes/bootstrap5/templates/record/view.phtml
Labels: bugfix

#4313 Switch to migration-based database upgrades.
  module/VuFind/sql/migrations/mysql/11.0/001-modify-login-token-indexes.sql
  module/VuFind/sql/migrations/mysql/11.0/002-modify-oai-resumption-columns.sql
  module/VuFind/sql/migrations/pgsql/10.0/001-add-login-token-table.sql
  module/VuFind/sql/migrations/pgsql/10.0/002-modify-search-user-column.sql
  module/VuFind/sql/migrations/pgsql/10.0/003-add-user-indexes.sql
  module/VuFind/sql/migrations/pgsql/2.5/001-add-user-card-table.sql
  module/VuFind/sql/migrations/pgsql/2.5/002-modify-user-columns.sql
  module/VuFind/sql/migrations/pgsql/3.0/001-modify-user-columns.sql
  module/VuFind/sql/migrations/pgsql/3.0/002-modify-resource-columns.sql
  module/VuFind/sql/migrations/pgsql/3.0/003-add-record-table.sql
  module/VuFind/sql/migrations/pgsql/3.0/004-modify-seach-columns.sql
  module/VuFind/sql/migrations/pgsql/4.0/001-add-external-session-table.sql
  module/VuFind/sql/migrations/pgsql/4.0/002-modify-user-columns.sql
  module/VuFind/sql/migrations/pgsql/5.0/001-modify-comments-user-ref.sql
  module/VuFind/sql/migrations/pgsql/5.0/002-modify-user-columns.sql
  module/VuFind/sql/migrations/pgsql/5.1/001-modify-resource-columns.sql
  module/VuFind/sql/migrations/pgsql/5.1/002-modify-user-columns.sql
  module/VuFind/sql/migrations/pgsql/6.0/001-add-shortlinks-table.sql
  module/VuFind/sql/migrations/pgsql/6.0/001-modify-user-columns.sql
  module/VuFind/sql/migrations/pgsql/6.1/001-modify-user-columns.sql
  module/VuFind/sql/migrations/pgsql/6.1/002-modify-id-columns.sql
  module/VuFind/sql/migrations/pgsql/6.1/003-modify-search-table.sql
  module/VuFind/sql/migrations/pgsql/6.1/004-add-auth-hash-table.sql
  module/VuFind/sql/migrations/pgsql/7.0/001-modify-shortlinks.sql
  module/VuFind/sql/migrations/pgsql/7.1/001-allow-list-tags.sql
  module/VuFind/sql/migrations/pgsql/9.0/001-add-ratings-table.sql
  module/VuFind/sql/migrations/pgsql/9.0/001-add-search-index.sql
  module/VuFind/sql/migrations/pgsql/9.0/002-add-feedback-table.sql
  module/VuFind/sql/migrations/pgsql/9.0/003-add-access_token-table.sql
  module/VuFind/sql/migrations/pgsql/9.0/004-modify-user-columns.sql
  module/VuFind/sql/migrations/pgsql/9.0/005-modify-user-card-columns.sql
  module/VuFind/sql/migrations/pgsql/9.0/006-modify-boolean-fields.sql
  module/VuFind/sql/migrations/pgsql/9.0/007-drop-search-folder-id.sql
  module/VuFind/src/VuFind/Controller/AbstractBase.php
  module/VuFind/src/VuFind/Controller/Plugin/DbUpgrade.php
  module/VuFind/src/VuFind/Controller/UpgradeController.php
  module/VuFind/src/VuFind/Db/MigrationManager.php
  themes/bootstrap5/templates/upgrade/getdbcredentials.phtml
Labels: tooling
