Repository vufind-org/vufind, pull requests merged in 2025-09, with the labels that each got.

#4579 Fix several English typos (most of them found by codespell)
  config/vufind/config.ini
  module/VuFind/src/VuFind/Auth/AlmaDatabase.php
  module/VuFind/src/VuFind/Auth/OpenIDConnect.php
Labels: bugfix

#4585 Remember selected bulk export option in session storage.
  themes/bootstrap5/templates/cart/export.phtml
Labels: improvement

#4588 Fix and tweak password recovery.
  module/VuFind/src/VuFind/Auth/ILS.php
  module/VuFind/src/VuFind/Auth/MultiILS.php
  module/VuFind/src/VuFind/ILS/Driver/Demo.php
  module/VuFind/src/VuFind/ILS/Driver/KohaRest.php
  module/VuFind/src/VuFind/ILS/Driver/SierraRest.php
  module/VuFind/src/VuFindTest/Integration/MinkTestCase.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AccountActionsTest.php
  themes/bootstrap5/templates/myresearch/resetpassword.phtml
Labels: bugfix, improvement

#4592 Add test for getCourses of Alma ILS driver and fix implementation
  module/VuFind/src/VuFind/ILS/Driver/Alma.php
  module/VuFind/tests/fixtures/alma/responses/get-courses.json
  module/VuFind/tests/fixtures/alma/responses/get-courses.xml
  module/VuFind/tests/unit-tests/src/VuFindTest/ILS/Driver/AlmaTest.php
Labels: bugfix

#4479 Add support for Solr's DateRange fields and use for publish date
  config/constants.config.php
  config/vufind/BlenderMappings.yaml
  config/vufind/Collection.ini
  config/vufind/Search2.ini
  config/vufind/config.ini
  config/vufind/facets.ini
  config/vufind/searches.ini
  import/csv-scopus.ini
  import/index_java/src/org/vufind/index/DateTools.java
  import/marc.properties
  import/xsl/archivesspace.xsl
  import/xsl/doaj.xsl
  import/xsl/dspace-dim.xsl
  import/xsl/dspace.xsl
  import/xsl/gsdl.xsl
  import/xsl/intech.xsl
  import/xsl/ndltd.xsl
  import/xsl/nlm_ojs.xsl
  import/xsl/ojs.xsl
  import/xsl/subjectsplus.xsl
  import/xsl/vudl_FOXML.xsl
  module/VuFind/src/VuFind/AjaxHandler/GetVisData.php
  module/VuFind/src/VuFind/Recommend/SideFacets.php
  module/VuFind/src/VuFind/Search/Base/DateRangeOptionsInterface.php
  module/VuFind/src/VuFind/Search/Base/Params.php
  module/VuFind/src/VuFind/Search/Base/Results.php
  module/VuFind/src/VuFind/Search/Solr/Options.php
  module/VuFind/src/VuFind/Search/Solr/Params.php
  module/VuFind/src/VuFindTest/Feature/SearchSortTrait.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AdvancedSearchTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchFacetsTest.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchSortTest.php
  module/VuFindSearch/src/VuFindSearch/Backend/Solr/Response/Json/RecordCollection.php
  solr/vufind/biblio/conf/schema.xml
  tests/data/really_old.xml
  tests/data/really_old.xml.properties
  tests/phpstan-constants.php
  themes/bootstrap5/templates/Recommend/SideFacets/range-slider.phtml
  themes/bootstrap5/templates/_ui/components/date-range-slider.phtml
Labels: new feature

#4586 Refactor database building to a separate class; add console database generator.
  build.xml
  module/VuFind/config/module.config.php
  module/VuFind/src/VuFind/Controller/InstallController.php
  module/VuFind/src/VuFind/Db/DbBuilder.php
  module/VuFind/src/VuFind/Db/DbBuilderFactory.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Db/DbBuilderTest.php
  module/VuFindConsole/src/VuFindConsole/Command/Install/DatabaseCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Install/DatabaseCommandFactory.php
  module/VuFindConsole/src/VuFindConsole/Command/PluginManager.php
  module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Install/DatabaseCommandTest.php
Labels: new feature, improvement, architecture, tooling

#4590 PubDateVisAjax: Remove incorrectly refactored argument.
  themes/bootstrap3/templates/Recommend/PubDateVisAjax.phtml
  themes/bootstrap5/templates/Recommend/PubDateVisAjax.phtml
Labels: bugfix

#4601 Add implementation and test for getFunds with Alma ILS driver
  module/VuFind/src/VuFind/ILS/Driver/Alma.php
  module/VuFind/tests/fixtures/alma/responses/get-funds.json
  module/VuFind/tests/fixtures/alma/responses/get-funds.xml
  module/VuFind/tests/unit-tests/src/VuFindTest/ILS/Driver/AlmaTest.php
Labels: improvement

#4608 Add unit test coverage for basic search handler Options methods.
  module/VuFind/src/VuFindTest/Feature/MockSearchOptionsTrait.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/Base/OptionsTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Search/Base/ParamsTest.php
Labels: tests

#4610 Remove deprecated supportsFirstLastNavigation() method.
  module/VuFind/src/VuFind/Search/Base/Options.php
Labels: architecture, small

#4612 Switch to ConfigManagerInterface for bulk action related classes
  module/VuFind/src/VuFind/Controller/CartController.php
  module/VuFind/src/VuFind/Controller/CartControllerFactory.php
  module/VuFind/src/VuFind/Controller/Feature/BulkActionControllerTrait.php
  module/VuFind/src/VuFind/Controller/MyResearchController.php
  module/VuFind/src/VuFind/Controller/MyResearchControllerFactory.php
  module/VuFind/src/VuFind/Feature/BulkActionTrait.php
  module/VuFind/src/VuFind/View/Helper/Root/BulkAction.php
Labels: architecture

#4626 Updated non-dev dependencies in preparation for 11.0 release
  composer.json
  composer.lock
Labels: dependencies

#4632 [VUFIND-1792] Fix inappropriate hard-coded route name in redirect.
  module/VuFind/src/VuFind/Controller/AbstractSearch.php
  module/VuFind/tests/integration-tests/src/VuFindTest/Mink/Search2Test.php
Labels: bugfix

#4636 Enable passthru and checkreturn in more commands in phing.
  build.xml
Labels: tooling

#4638 Enable caching for phpmd.
  .gitignore
  build.xml
Labels: tooling

#4625 Add upgrade/database console utility.
  config/vufind/ConsoleMenu.yaml
  module/VuFind/src/VuFind/Db/Migration/MigrationManager.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Db/Migration/MigrationManagerTest.php
  module/VuFindConsole/src/VuFindConsole/Command/PluginManager.php
  module/VuFindConsole/src/VuFindConsole/Command/Upgrade/DatabaseCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Upgrade/DatabaseCommandFactory.php
  module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Upgrade/DatabaseCommandTest.php
Labels: new feature

#4641 Add limit for number of autocomplete items shown in drop down list
  config/vufind/searches.ini
  module/VuFind/src/VuFind/Search/Base/Options.php
  module/VuFind/src/VuFind/View/Helper/Root/SearchBox.php
  themes/bootstrap5/js/searchbox_controls.js
  themes/bootstrap5/templates/search/searchbox.phtml
Labels: improvement

#4665 Replace config PluginManager for search recommendations
  module/VuFind/src/VuFind/Recommend/AbstractSearchObject.php
  module/VuFind/src/VuFind/Recommend/AbstractSearchObjectFactory.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Recommend/SummonResultsTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Recommend/WebResultsTest.php
Labels: architecture
