Repository vufind-org/vufind, pull requests merged in 2025-05, with the labels that each got.

#4360 Fix: no null coalescing on a non-nullable value.
  module/VuFind/src/VuFind/Search/Base/Options.php
Labels: bugfix

#4352 Fix advanced search add group button size
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/components/advanced-search.less
  themes/bootstrap3/scss/components/advanced-search.scss
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/scss/components/advanced-search.scss
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal5/css/compiled.css
Labels: bugfix

#4366 Add a check for duplicate library cards.
  module/VuFind/src/VuFind/Db/Service/UserCardService.php
Labels: bugfix

#4365 Modernize search code to entity/search service standards.
  module/VuFind/src/VuFind/Controller/MyResearchController.php
  module/VuFind/src/VuFind/Db/Service/SearchService.php
  module/VuFind/src/VuFind/Db/Service/SearchServiceInterface.php
  themes/bootstrap3/templates/myresearch/schedulesearch.phtml
  themes/bootstrap5/templates/myresearch/schedulesearch.phtml
Labels: architecture

#4368 [VUFIND-1772] Fix accordion view in Bootstrap 5 themes.
  build.xml
  themes/bootstrap5/templates/record/ajaxview-accordion.phtml
Labels: bugfix

#4364 Disable empty searches for EDS
  module/VuFind/src/VuFind/Search/Base/Results.php
  module/VuFind/src/VuFind/Search/EDS/Results.php
  module/VuFind/src/VuFind/Search/WorldCat2/Results.php
Labels: improvement

#4370 Add comment about EDS API behavior change.
  module/VuFindSearch/src/VuFindSearch/Backend/EDS/QueryBuilder.php
Labels: documentation

#4349 Add Upgrade integration test
  .gitignore
  module/VuFind/src/VuFind/Config/PathResolver.php
  module/VuFind/src/VuFind/Feature/DirUtilityTrait.php
  module/VuFind/tests/fixtures/configs/backup/config.ini
  module/VuFind/tests/integration-tests/src/VuFindTest/Config/ConfigUpgradeTest.php
  module/VuFindTheme/src/VuFindTheme/AbstractThemeUtility.php
Labels: tests

#4363 Use parent storeErrorResponse method for ProQuestFSG
  module/VuFind/src/VuFind/Search/ProQuestFSG/Results.php
Labels: improvement, small

#4367 Fix remaining select fields that had the form-control class.
  themes/bootstrap5/templates/Auth/MultiILS/loginfields.phtml
  themes/bootstrap5/templates/blender/advanced.phtml
  themes/bootstrap5/templates/eds/advanced.phtml
  themes/bootstrap5/templates/primo/advanced.phtml
  themes/bootstrap5/templates/record/hold.phtml
  themes/bootstrap5/templates/search/advanced/eds.phtml
Labels: bugfix

#4353 Clean up constructors of search Options classes.
  module/VuFind/src/VuFind/Search/Base/Options.php
  module/VuFind/src/VuFind/Search/Blender/Options.php
  module/VuFind/src/VuFind/Search/BrowZine/Options.php
  module/VuFind/src/VuFind/Search/Combined/Options.php
  module/VuFind/src/VuFind/Search/EDS/Options.php
  module/VuFind/src/VuFind/Search/EIT/Options.php
  module/VuFind/src/VuFind/Search/EPF/Options.php
  module/VuFind/src/VuFind/Search/Favorites/Options.php
  module/VuFind/src/VuFind/Search/LibGuides/Options.php
  module/VuFind/src/VuFind/Search/Options/ViewOptionsTrait.php
  module/VuFind/src/VuFind/Search/Primo/Options.php
  module/VuFind/src/VuFind/Search/ProQuestFSG/Options.php
  module/VuFind/src/VuFind/Search/Solr/Options.php
  module/VuFind/src/VuFind/Search/SolrCollection/Options.php
  module/VuFind/src/VuFind/Search/SolrReserves/Options.php
  module/VuFind/src/VuFind/Search/Summon/Options.php
  module/VuFind/src/VuFind/Search/Tags/Options.php
  module/VuFind/src/VuFind/Search/WorldCat2/Options.php
Labels: architecture

#4376 Fix bug: multi-select facets broke course reserves sort.
  themes/bootstrap5/js/facets.js
  themes/bootstrap5/templates/Recommend/SideFacets.phtml
Labels: bugfix

#4378 Improve the look of comments and ratings.
  themes/bootprint3/css/compiled.css
  themes/bootstrap3/css/compiled.css
  themes/bootstrap3/less/components/record.less
  themes/bootstrap3/scss/components/record.scss
  themes/bootstrap3/templates/record/comments-list.phtml
  themes/bootstrap5/css/compiled.css
  themes/bootstrap5/scss/bs3-compat.scss
  themes/bootstrap5/scss/components/record.scss
  themes/bootstrap5/templates/record/comments-list.phtml
  themes/local_theme_example/css/compiled.css
  themes/sandal/css/compiled.css
  themes/sandal5/css/compiled.css
Labels: bugfix

#4380 Fix incorrect log_table example definition.
  config/vufind/config.ini
Labels: bugfix, documentation

#4382 Fix/simplify database upgrade workflow.
  module/VuFind/src/VuFind/Controller/UpgradeController.php
  themes/bootstrap5/templates/upgrade/showsql.phtml
Labels: bugfix

#4347 Several smaller improvements for EDS HTML Full Text Rendering
  module/VuFind/src/VuFind/RecordDriver/EDS.php
  module/VuFind/tests/fixtures/eds/eds_mathml_table.html
  module/VuFind/tests/fixtures/eds/eds_retrieve_ft_html.json
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordDriver/EDSTest.php
Labels: improvement

#4390 Update translations for 10.2 release - Armenian
  languages/CreatorRoles/hy.ini
  languages/RecordAttribute/hy.ini
  languages/Reserves/hy.ini
  languages/hy.ini
Labels: i18n
