Repository vufind-org/vufind, pull requests merged in 2025-10, with the labels that each got.

#4674 Replace config PluginManager for TabManager
  module/VuFind/src/VuFind/RecordTab/TabManager.php
  module/VuFind/src/VuFind/RecordTab/TabManagerFactory.php
  module/VuFind/tests/unit-tests/src/VuFindTest/RecordTab/TabManagerTest.php
Labels: architecture

#4651 Add logout function for OpenID Connect and clean existing code
  config/vufind/OpenIDConnectClient.ini
  module/VuFind/src/VuFind/Auth/OpenIDConnect.php
Labels: improvement

#4584 Add support for export to Zotero Web Library.
  composer.json
  composer.lock
  config/vufind/config.ini
  config/vufind/export.ini
  languages/en.ini
  languages/fi.ini
  languages/sv.ini
  module/VuFind/config/module.config.php
  module/VuFind/src/VuFind/Controller/ZoteroController.php
  module/VuFind/src/VuFind/Controller/ZoteroControllerFactory.php
  module/VuFind/src/VuFind/Db/Service/AccessTokenService.php
  module/VuFind/src/VuFind/Db/Service/AccessTokenServiceInterface.php
  module/VuFind/src/VuFind/Exception/ZoteroException.php
  module/VuFind/src/VuFind/Export.php
  module/VuFind/src/VuFind/Export/Zotero/ZoteroOAuth.php
  module/VuFind/src/VuFind/Export/Zotero/ZoteroService.php
  module/VuFind/src/VuFind/Export/Zotero/ZoteroServiceFactory.php
  module/VuFind/src/VuFind/Export/Zotero/ZoteroTokenCredentials.php
  module/VuFind/tests/fixtures/zotero/partial-schema.json
  module/VuFind/tests/unit-tests/src/VuFindTest/Service/ZoteroTest.php
  themes/bootstrap5/templates/zotero/export.phtml
  themes/root/templates/RecordDriver/AbstractBase/export-zoteroweblibrary.phtml
Labels: new feature

#4688 Replace config PluginManager for Relate/Bookplate
  module/VuFind/src/VuFind/Related/Bookplate.php
  module/VuFind/src/VuFind/Related/BookplateFactory.php
  module/VuFind/tests/unit-tests/src/VuFindTest/Related/BookplateTest.php
Labels: architecture

#4686 Add missing functions to Sample ILS driver
  module/VuFind/src/VuFind/ILS/Driver/Sample.php
Labels: improvement

#4550 Add support for timed ILS function blocking
  config/vufind/Demo.ini
  config/vufind/KohaRest.ini
  config/vufind/SierraRest.ini
  languages/en.ini
  module/VuFind/src/VuFind/ILS/Connection.php
  module/VuFind/src/VuFind/ILS/Driver/Demo.php
  module/VuFind/src/VuFind/View/Helper/Root/MethodTimedBlocks.php
  module/VuFind/tests/unit-tests/src/VuFindTest/ILS/ConnectionTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/FlashmessagesTest.php
  module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/MethodTimedBlocksTest.php
  themes/bootstrap5/templates/myresearch/checkedout.phtml
  themes/root/theme.config.php
Labels: new feature, new language strings

#4662 Add a download utility and use it to download Solr packages.
  build.xml
  config/vufind/ConsoleMenu.yaml
  module/VuFind/src/VuFind/Http/GuzzleService.php
  module/VuFindConsole/src/VuFindConsole/Command/PluginManager.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/DownloadCommand.php
  module/VuFindConsole/src/VuFindConsole/Command/Util/DownloadCommandFactory.php
Labels: tooling
